<p class="volume">
  Volume 8 | September 2015
</p>
<h6><a href="http://www.internationalhispanicmedia.org/wp-content/uploads/2017/01/Volume-8_04-AnUnimaginableCombination.pdf">[ Download PDF ]</a></h6>
<section class="authors">
  <h4>Authors</h4>
  <p>
    <strong>Ronald Bishop, Ph.D.</strong>
    Drexel University
    Email: <a href="mailto:rcbsam@comcast.net">rcbsam@comcast.net</a>
  </p>
</section>
<hr />
<section>
  <h2>Abstract</h2>
  <p>During an August 2015 press conference in Iowa, Univision anchor Jorge Ramos attempted to ask the frontrunner for the Republican presidential nomination, Donald Trump, a question about Trump’s proposal to deport undocumented immigrants from the United States. Trump accused Ramos of asking his question out of turn, then told him to “sit down” and “go back to Univision.” Ramos was removed from the room by a member of Trump’s security team but later was invited back to the press conference after Ramos’ colleagues questioned Trump’s actions. This narrative analysis of the coverage of the Ramos-Trump clash reveals that where a journalist who confronts an evasive official might have earned praise once, he now receives a lecture on press conference decorum. Even if Ramos had only faked being adversarial, the narrative condemned him for flouting a relatively new journalistic tradition of impartiality that does not anger advertisers or alienate audience. The field may have reached the point where reporting aggressively is a troublesome anachronism.</p>
  <p>
    <strong>Keywords:</strong> Jorge Ramos, Donald Trump, press conference, 2016 U.S. election, immigration, objectivity, advocacy, narrative analysis
  </p>
  <p>
    “This is a press conference – the last thing I want to do is answer a lot of questions.”<br />
    - Gen. Maynard M. Mitchell, M*A*S*H, “The Incubator” (TV episode)
  </p>
</section>
<hr />
<section>
  <h2>Introduction</h2>
  <p>On August 25, 2015, during a press conference in Dubuque, Iowa, the veteran journalist and popular Univision anchor Jorge Ramos attempted to ask Donald Trump, then the frontrunner in the race for the 2016 Republican nomination for president, a question about Trump’s proposal to deport all of the nation’s 11 million undocumented immigrants. Trump accused Ramos of asking his question out of turn, and then told him to “sit down” and “go back to Univision.” Ramos was removed from the room by a member of Trump’s security team but later was invited back to the press conference after MSNBC’s Kasie Hunt and Tom Llamas of ABC News questioned Trump’s actions (Gross, 2015; Stelter, 2015). Trump claimed in a subsequent interview that he would have “very quickly” (Lauer, 2015) moved through the other reporters’ questions to call on Ramos, but that suddenly “this man gets up and starts ranting and raving and screaming” (Lauer, 2015). </p>
  <p>Expelled to an adjacent hallway, Ramos heard a Trump supporter tell him to “get out of my country” (Rolly, 2015); Ramos asserted that he was a U.S. citizen––to which the Trump supporter responded, “Well, whatever. No, Univision, no. It’s not about you” (Newton, 2015; Terkel, 2015). Ramos challenged Trump’s account of what occurred, claiming that he had, in fact, raised his hand in order to ask his question (Glenza, 2015; Gross, 2015). Trump’s brusque and dismissive treatment of Ramos in the ensuing months generated a pocket of intense publicity. </p>
  <p>Two months prior to the press conference, Ramos had written a letter to Trump in which he asked for an interview. Trump rejected Ramos’ request. Ramos traveled to Iowa to continue his pursuit of an interview. Ramos’ employer, Univision, had recently severed its business relationship with Trump, citing Trump’s bigoted comments about undocumented immigrants from Mexico. Trump subsequently put up a photo of Ramos’ letter—which included his cell phone number—on his Instagram account (Finnegan, 2015). A week before the press conference, Ramos tweeted that while Trump’s ideas on immigration were similar to those developed by other GOP candidates, Trump “just expresses them in an extreme way” (“Univision Anchor,” 2015). Two days before the press conference, Trump continued his pointed criticism of Fox News anchor Megyn Kelly—begun after Kelly, in Trump’s estimation, asked unfair questions during the first GOP debate about his tendency to disparage women—by retweeting a characterization of Kelly as a “bimbo,” reiterating his opinion of her as unprofessional and, most infamously, referencing Kelly’s menstrual cycle in comments about the controversy. </p>
  <p>Trump’s ejection of Ramos from the Dubuque press conference further antagonized the Latino community. When he announced in June 2015 his plans to run for president, Trump, as referenced earlier, notoriously asserted that undocumented immigrants from Mexico with “lots of problems” were flooding into the United States. He later proposed building a wall on the U.S.-Mexico border to keep undocumented immigrants from entering the U.S. Trump also announced his mass deportation plans and said that he would deny birthright citizenship, guaranteed under the 14th Amendment to the U.S. Constitution, to children of undocumented immigrants born here (García-Ríos, 2015). Univision responded to Trump’s comments by refusing to air the Miss Universe pageant. Trump, who is part owner of the pageant (Katz, 2015, p. 11), subsequently sued the network for $500 million. In late October 2015, he tried to deny Univision reporters access to a campaign rally in Florida, citing the lawsuit (Jerde, 2015). Trump has also instructed his employees to deny service to Univision employees at his golf courses in South Florida (Scherer, 2015). </p>
  <p>This article reports a narrative analysis of news media coverage, not of Trump, his candidacy, or of his hateful view of undocumented immigrants, but of Ramos’ attempt to ask Trump about his immigration policy. The article attempts to answer these research questions: How did Ramos’ colleagues evaluate and explain his conduct in the clash with Trump? Was he lauded for his persistence—for acting in true “watchdog” fashion—or was he criticized for being too confrontational for violating the field’s and the audience’s expectations of how roles are played during a press conference?</p>
</section>
<section>
  <h2>Theoretical Terrain</h2>
  <p>The “watchdog” function of the press has its roots in the democratic elite theory of the media, which suggests that a democracy functions efficaciously if led by “highly educated elites and specialized technicians” (Benson, 2008, p. 2,594). The theory sits ideologically between social responsibility theory, under which journalists embrace a duty to report objectively and accurately while maintaining their neutrality—all to promote robust debate—and democratic participatory theory, in which journalists are enlisted to persuade citizens to become more politically involved, even if that sometimes means adopting distasteful reporting practices to do it (pp. 2,593-2,594). </p>
  <p>The journalist’s primary tasks under the democratic elite theory are to present the perspectives offered up by dominant social institutions and to keep tabs on their behavior for signs of ineffectiveness and corruption—by acting as society’s “watchdog.” Bennett and Serrin (2005) define watchdog journalism as “(1) independent scrutiny by the press of the activities of the government, business, and other public institutions, with an aim toward (2) documenting, questioning, and investigating those activities, in order to (3) provide publics and officials with timely information on issues of public concern” (p. 169). The “guard dog” theory of journalism, developed in the mid-1990s by Donahue, Tichenor, and Olien (1995), rejects the watchdog function; instead, the authors contend, reporters act as “sentry” for powerful institutions that are quite capable of playing that role without assistance. The news media, they claim, are not autonomous. They are not subservient “lapdogs” (p. 120), obliviously defending those in power. Instead, they operate as part of the power structure, although they lack both the “inclination” and the “power to challenge those dominant groups, unless they are already under challenge by other forces” (p. 119). They slip into the “guard dog” role “when external forces present a threat to local leadership” (p. 116), and then report on the conflict. Their dependence on officials for information has in effect trained them to be on the lookout for potential intruders; they may “sound the alarm” (p. 116) for reasons that leaders initially do not understand.</p>
  <p>Bennett and Serrin (2005) lay out something of a theoretical middle ground. Convinced of their own celebrity, “drawn to the glitter of the Georgetown social circuit and the White House,” and focused on burnishing their “brands,” today’s journalists have reinvented the watchdog role; it is now “overly stylized and ritualized” (p. 179), Bennett and Serrin contend. Journalists adopt the investigative reporter pose and fail to gird their stories with evidence or offer solutions to society’s problems. If in an initial round of reporting a journalist describes significant official misconduct, colleagues typically do not follow up (p. 179). It certainly does not help, the authors argue, that a growing number of journalists were raised in middle- and upper-class families. “They belong to the culture for which the American political system works exceedingly well,” wrote the famed columnist Russell Baker in 2003 (quoted in Bennett &amp; Serrin, 2005, p. 181). </p>
  <p>Not that the inclination for the theatrical and contrived is a new development in journalism. In his classic work <em>The Image: A Guide to Pseudo-Events in America</em>, Daniel Boorstin (1962) asserted that it was the public’s burgeoning demand for a steady stream of timely and compelling news that led journalists to rely more often on “pseudo-events” in the coverage of their beats. “If there is no news visible to the naked eye, or to the average citizen,” he wrote, “we still expect it to be there for the enterprising newsman” (p. 8). The public began to demand more “news” of the world than the world could provide. “We require that something be fabricated to make up for the world’s deficiency,” (p. 8) Boorstin noted. Journalists responded by presenting their growing readership with more stories based on events concocted solely to attract coverage and only dubiously connected to what actually was transpiring. </p>
  <p>Thus, journalists have long had an unquenchable “thirst for a readily available, reliable flow of information” (Schudson, 2003, p. 134). They seek stories “that offer the greatest dramatic potential and hold the greatest promise of continuing plot development” (Bennett &amp; Serrin, 2005, p. 174). Often these stories “end up being manufactured out of little more than spin, staging, and the efforts of the press pack to inject life to the political routine” (p. 174). As a result, as Baym (2005) explains, “the discourses of news, politics, entertainment, and marketing have grown deeply inseparable; the languages and practices of each have lost their distinctiveness and are being melded into previously unimaginable combinations” (p. 262).</p>
  <p>A press conference is an event staged by an individual, a corporate executive, or public official—with the help of public relations professionals—to manage the flow of information about their actions made available to journalists and to the public. It has long been a tool of political expediency. They are typically held to develop, sustain, or restore an individual’s or an institution’s public image. Officials and executives extensively prepare for them, rehearsing their answers to potential questions (Graber, 2010, pp. 240-241). While the possibility always exists that an official or executive might misstate facts, go “off script,” engage in self-aggrandizing behavior, or become unable to respond coherently, the goal remains to control the release of news. </p>
  <p>Allen (1993) explains that while president, Woodrow Wilson used private Oval Office gatherings of reporters “as a sounding board for U.S. intervention in the Mexican Revolution” (p. 15), while Harry Truman moved the events to a larger space to accommodate the growing White House press corps (p. 15). Dwight Eisenhower, frustrated with criticism by reporters and by their “superficial analysis” (p. 17) of Senator Joseph McCarthy’s actions, and unable to recreate the “warm and non-confrontational relations” (p. 16) he had enjoyed with the press during World War II, came to see the press conference as an effective means to disseminate his ideas. Eisenhower’s press secretary, James Hagerty, a former journalist, heartily endorsed communicating “directly with the people who can hear exactly what [the] president said without reading warped and slanted stories” (p. 20). For their part, television networks took advantage of the fact that press conferences were cheaper to produce than FDR’s “fireside chats” and did not trigger the FCC’s “equal time” provision. Hagerty diffused criticism by reporters that news conference footage was heavily edited prior to broadcast by pointing out that White House officials had edited material for some time, and noting the financial advantages to be gained by accepting that news conferences were “inevitable” (p. 23).</p>
  <p>By the late 1960s, journalists were more aggressive in their interactions with the president, becoming “testy” and “more likely to challenge official claims and push politicians off message” (Bennett, 2009, p. 132). As Heritage and Clayman (2013) explain, questions from journalists had “become more opinionated or assertive, more adversarial in content, and more apt to hold the president accountable for his policies” (p. 482). Today, exercising “an increasingly prominent and independent voice” in coverage of politics, journalists are “more interpretive, more negative, and more preoccupied with political strategy over policy substance,” Heritage and Clayman claim (p. 482). </p>
  <p>Nevertheless, the journalist who endures long stretches in these “controlled institutional settings” (Bennett &amp; Livingston, 2003, p. 361) does so to satisfy our “demand for illusions” (Boorstin, 1962, p. 9). They do so as their ranks shrink and the number of public relations professionals grows; PR professionals now outnumber journalists three to one (Sullivan, 2011). Even though they are staged to facilitate interaction (Tuchman, 1978, p. 114), press conferences “are routinely treated as news” (Jamieson &amp; Campbell, 1997, p. 136). Most of the news we consume now originates in “planned, intentional events, press releases, press conferences, and scheduled interviews” (Schudson, 2003, p. 6). Press conferences provide “the dramatic, visual, concise characteristics” that journalists desire and to which their readers respond (Jamieson &amp; Campbell, 1997, p. 136). The reporter trades context for convenience; he or she “minimizes the amount of background information needed and the amount of time it takes to assemble a story” (p. 136). The press conference is a stage-managed distraction. As one veteran reporter told Schudson (2003), “there’s always something going on that deprives one of the time to dig underneath” (p. 137). Instead of providing context or reporting aggressively, a reporter covers what is in front of him or her, and, having been enticed by “proximity to power” (Schudson, 2003, p. 142), typically “accepts the assumptions of those managing the event” (Jamieson &amp; Campbell, 1997, p. 136). </p>
  <p>These choices have given rise to the criticism that journalists too often act theatrically––and goad the person holding the press conference to do the same—as opposed to asking thoughtful questions. Colleagues and the audience expect journalists to follow this part of the sourcing “protocol” (Boorstin, 1962, p. 32). Journalists seemingly have lost the inclination felt during the Watergate era to expose official prevarication—and to do the reporting necessary to produce that exposure (Schudson, 1978, pp. 171-176). Having ceded their cultural authority to everything from car advertisements (Bishop, 2012/13) to <em>Entertainment Tonight</em>, journalists are now prone to lauding the “watchdog” ideal “without having a firm sense of how to put into practice” (Bennett &amp; Serrin, 2005, p. 173). Motivated perhaps by their field’s precarious financial state, they enthusiastically “substitute the spectacle or the posture of adversarialism for the sort of journalism that might better the public interest” (p. 173). As Meltzer (2009) explains, even though print journalists still consider themselves “the arbiters of professional decency and standards” (p. 64) and their broadcast colleagues still occupy a less favorable position in the “journalistic hierarchy of credibility and prestige,” they tolerate the celebrity that attaches to anchors like Jorge Ramos because it so visibly affirms the field’s authority. But if a colleague’s conduct severely breaches the field’s ideals, paradigm repair (Hindman, 2005) will be undertaken—although as will be discussed, barriers erected as part of that repair in Ramos’ case protected a model of journalism vigorously criticized in segments of journalism’s interpretive community (Zelizer, 1993).  </p>
  <p>But even if Jorge Ramos was posturing when he tried to ask Trump about his immigration policies, their exchange provides a compelling opportunity to explore how journalists explain to the public the conduct of a colleague who has for whatever reason embraced the “watchdog” role and rejected the oft-criticized “he said-she said” approach to reporting that critics claim allows false equivalencies to germinate and public officials—and top-tier political candidates—to escape scrutiny.</p>
</section>
<section>
  <h2>Method</h2>
  <p>Searches of the Lexis-Nexis and Google News databases were conducted in October 2015 to obtain, for analysis, news articles and commentary about the Ramos-Trump confrontation. Articles were included if they were published between August 25 (the date of the press conference) and September 8, 2015, by which point coverage of the confrontation had significantly diminished. Accumulation of articles continued until enough evidence was obtained to formulate “a sufficient number of arguments of sufficient quality,” as Wood and Kroger (2000, p. 81) advise. Gathering of texts was then discontinued. The searches produced 96 texts for analysis. Ramos’ report for the Fusion television network about his journey to Iowa, as well as his appearances subsequent to the confrontation with Trump on morning network news shows and Fox News’ <em>The O’Reilly Factor</em>, were also analyzed since they accompanied many of the texts. </p>
  <p>The author performed a careful narrative analysis on the texts. A “long preliminary soak” (Hall, 1975, p. 15) was followed by numerous subsequent readings conducted to unpack key narrative elements—plot, settings, characters, narration, temporal relations, causal relations, audience (Foss, 2009, pp. 312-315) —and to identify and refine the primary narrative themes. Extensive notes were taken as the analysis unfolded; they were carefully reviewed as the narrative elements were identified and themes emerged.</p>
  <p>Walter Fisher’s (1989) seminal work on the centrality of narrative drove the analysis. Fisher asserts that narrative “is the basic and essential genre for the characterization of human action” (p. 58). Communication does not have to be “argumentative in form” (p. 58) in order to have impact. In fact, rationality is sustained by the narratives we develop to explain our lives to others and to ourselves. “By creating stories out of the raw material of our lives,” explains Klapproth (2004), “we manage not only to establish coherence for ourselves, but also to create meaningful discursive structures that can be communicated and shared” (p. 3). Narrative is thus a tool of organization; it helps us “make sense of the people, places, events, and actions of our lives” (Foss, 2009, p. 307). Telling and retelling stories enables us to determine “what a particular experience is about and how the various elements of our experience are connected” (p. 307). </p>
  <p>We strive as much for coherence as for accuracy in compiling and revising the stories that Fisher believes empower us to meaningfully take part in our lives. As Walter Benjamin (1982) argued, a narrative “preserves and concentrates its strength and is capable of releasing it even after a long time” (p. 90). In fact, as Bruner (1991) asserts, an expert storyteller is able to persuade an audience that only one interpretation of a story is possible (p. 9). By exploring the “linguistic and cultural resources” from which coverage of the Ramos-Trump disagreement was built, we can assess how journalists attempted to convince their readers that the event was “something that can be told about” (Manoff, 1987, p. 226), and that their reading of it is the only valid one.</p>
  <p>Journalists craft narratives to explain events to readers, finding “in the unfamiliar…that which is familiar, a story type made available by culture,” as Eason (1981) explains. Journalists have freedom to select the materials with which they assemble their stories, but the assembly typically takes place on an existing—and well-known—narrative framework. As they hone their craft, journalists learn that narratives “bring order to events by making them something that can be told about; they have power because they make the world make sense,” as Manoff (1987, pp. 228-229) contends. A journalist comes to depend on “a mental catalogue of news story themes, including how the ‘plot’ will actually unravel and who the key actors are likely to be” (Berkowitz, 1997, p. 363). They have little, if any, choice in the matter, since their editors—and readers—expect they will explain events using familiar narratives. In the end, a successful news story is one in which “events seem to tell themselves” (Kitch, 2002, p. 296).</p>
</section>
<section>
  <h2>The Ramos-Trump Narrative</h2>
  <p>The narrators’ primary objective in explaining Ramos’ conduct was to affirm the legitimacy of how journalism is now practiced. Even if Ramos had, as Bennett and Serrin (2005) claim, substituted “the spectacle or the posture of adversarialism for the sort of journalism that might better serve the public interest” (p. 173), his colleagues seized an opportunity to inform the audience that even a dramatized invocation of journalism’s “watchdog” function would not be tolerated. One cannot even play a crusading journalist and escape criticism from colleagues so heavily invested in a model of reporting that among its many flaws, favors infotainment and promoting false equivalencies. Journalistic ethics, paradigm repair, the significance of the First Amendment—all were deployed by journalists across these texts to sustain an election drama built on their decision to report Trump’s every vacuous, boorish, and bigoted statement largely without challenge. To meet their objective, they positioned Ramos as an outlier––primarily for the threat he posed to the Trump drama, not to journalism.</p>
  <p>Trump and Ramos, the narrative’s primary characters, were portrayed as foes locked in the latest battle between Trump and reporters, whom Trump repeatedly accused of not treating him fairly. A <em>Los Angeles Times</em> reporter called the confrontation Trump’s “latest showdown” (Mai-Duc, 2015a) with the news media. The two men “sparred” (Cornish, 2015; Garbe, 2015); their exchange, although brief, was contentious—“heated,” noted one reporter (Garbe, 2015). Even after Ramos was allowed back into the press conference, “the crossfire continued” (Garbe, 2015). It was “a testy back and forth exchange” (Peyronnin, 2015) that “dominated the rest of the event” (Ross, 2015). Trump, whose bravado is a key element of his appeal to voters (Przybyla, 2015) is, according to this narrative, a master at managing the press despite his several “high-profile tiffs” with reporters. He would not, <em>The Washington Post</em> asserted, “be tamed” (Rucker &amp; Costa, 2015). Trump “has found yet another journalist to bully on the playground,” wrote <em>The Huffington Post</em>’s Gabriel Arana (2015a). He showed no signs of “ceding any ground” in his feuds with Megyn Kelly and with Ramos—his “new media nemesis” (Battaglio, 2015). The disagreement was just the “latest media mayhem” created by Trump (Nichols, 2015). His comments about undocumented immigrants “brought him head-to-head” with Ramos, suggested NPR’s Audie Cornish (2015). The two men then “engaged in a public tangle” (Ross, 2015). The mood in the room was “electric” (Miller, 2015). </p>
  <p>Ramos was characterized as persistent and dogged, but also as rude and pugnacious. He had “a history of combativeness” (Kurtz, 2015) when it came to confronting elected leaders, as though this was an erratic or even criminal act. Ramos “came loaded to press Trump,” said a National Public Radio reporter (Inskeep, 2015). In his lead-up to a question about Trump, ABC’s George Stephanopoulos (2015) asserted that Ramos “pressed hard with those questions and…had tough things to say” about Trump. Journalists portrayed the disagreement as “simmering for a while” (Cornish, 2015).</p>
  <p>Ramos was criticized for interrupting (e.g. Schultz, 2015) or trying to “buttonhole” the candidate (Guthrie, 2015). While Ramos “didn’t back down” (Mai-Duc, 2015a) and may have flustered Trump, some journalists suggested he was misguided if he thought he could somehow defeat Trump. “The idea that you can out-maneuver/out-yell/out-talk Trump,” asserted a Newsweek reporter, “is wrong-headed when taking the candidate’s previous behavior into account” (Martínez, 2015). More than once, Ramos was positioned as having to defend his “aggressive approach” (Schultz, 2015) to questioning. In fact, for some the attempt to hold Trump accountable was a journalistic aberration—“bizarre,” wrote one (Schultz, 2015). Reporters also gave Trump time and space to boast about his practice of seeking revenge on those who wrong him. <em>Today’s</em> Matt Lauer (2015) reminded Trump during a television interview the morning after the confrontation that he had once said, “When people treat me unfairly, I don’t let them forget me.”</p>
  <p>Ramos did not shrink from confrontation, however. “With little blood on the floor, both combatants actually prevailed,” explained one columnist (Hill, 2015, p. A7). The noted columnist Clarence Page (2015) concluded, “both men got something out of this face-off. Both looked tough and uncompromising to his fan base” (p. A7). For media companies, the “<em>mano-a-mano</em> media showdown made for gripping entertainment” (Miller, 2015) that would carry over into the campaign. The conflict “isn’t going away anytime soon,” one reporter predicted (Miller, 2015). Furthermore, facing off against Ramos was not without risk for Trump, as will be discussed. Ramos’ stature as a trusted expert in the Latino community should have caused Trump not to just “chalk up his scuffle” with the anchor “as yet another win in taking on the media” (García-Ríos, 2015). Still, readers were left with the distinct impression that Trump relishes his “feuds” with reporters. “He loves to brawl with people and journalists in particular,” asserted the <em>USA Today’s</em> Rem Rieder (2015, p. 2B). </p>
  <p>The Ramos-Trump narrative included a minor subplot in which some reporters took their colleagues to task for so eagerly covering Trump. “They have to stop showing up for, and lapping up, every ridiculous, insulting statement that he makes,” wrote a guest columnist for <em>The Huffington Post</em>, continuing, “these so-called legitimate media people are providing Trump with unwarranted credibility by covering him” (Phillips, 2015). <em>The New York Times</em>’ Mark Leibovich (2015) discounted the likelihood that such a moratorium could ever take place. Gaining access to Trump, he wrote, is “nothing like the teeth-pulling exercise that it can be to get any meaningful exposure to a candidate like, say, Hillary Clinton.” Trump’s bellicosity “is a seductive departure” for journalists “accustomed to being ignored, patronized, and offered sound bites to a point of lobotomy by typical politicians and the human straitjackets that surround them,” Leibovich claimed. But instead of seizing an opportunity for paradigm repair or to meaningfully debate the First Amendment issues at stake, reporters who covered the Ramos-Trump confrontation were content to chide Ramos—and to congratulate Trump for gaming the system. “[H]e’s not just scoring points by beating up the media,” said David Folkenflik, “he’s getting the media to cover him” (Inskeep, 2015). In “reinforcing his antics,” reporters enabled Trump to blur the “lines among politics, news, and entertainment” (Guthrie, 2015). </p>
  <p>Several journalists, including Megyn Kelly, played less important roles in the Ramos-Trump narrative. Following Trump’s insults, then-Fox News president Roger Ailes demanded an apology from the candidate, claiming that Kelly represented “the very best of American journalism” (Schultz, 2015). Trump relented, telling the <em>New York Daily News</em> in late August he was “no longer interested in crushing” Kelly (Wagner &amp; Katz, 2015). Moreover, in July 2015, Trump was “very dismissive of a certain line of questioning” from Telemundo anchor José Díaz-Balart during an appearance in Laredo, Texas, “that also honed in on gaps in what Trump had to offer” (Cornish, 2015). Díaz-Balart had begun to lay out a question challenging Trump’s bigoted characterization of undocumented immigrants when the candidate cut him off and accused him, and the rest of the news media, of “misinterpretation” (Campbell, 2015). When Díaz-Balart asked for the chance to finish his question, Trump shot back, “you’re finished” (Campbell, 2015). Also included were journalists from <em>The Des Moines Register</em>, who endured harsh criticism from Trump and were banned from a Trump event after the paper ran an editorial in which it urged Trump to suspend his campaign (Lemieux, 2015, p. 9A). Kasie Hunt and Tom Llamas, the journalists who according to Ramos “confronted” (Berg, 2015) Trump about the ejection, played minor roles, as did their colleagues, who according to one account (Cuomo, 2015) were angry at Ramos. The late, legendary CBS anchor Walter Cronkite was repeatedly referenced (Arana, 2015; Rieder, 2015), but only to affirm Ramos’ popularity with the Univision audience, not his skill as an anchor and reporter. </p>
  <p>Other critical voices were also heard. Univision CEO Randy Falco said that Trump’s treatment of Ramos was “beneath contempt” (Sherman, 2015). The National Association of Hispanic Journalists weighed in, announcing that it stood “with journalists everywhere who are simply working to pursue the truth and hold people in power accountable” (Nichols, 2015). The singer Ricky Martin (Lawler, 2015) criticized Trump for his treatment of Ramos in a “scathing op-ed.” The former GOP presidential candidate Jeb Bush claimed Ramos should have been “treated with a little more respect and dignity” (Mazzei, 2015).</p>
</section>
<section>
  <h2>Primary Narrative Themes</h2>
  <p>We now turn our attention to the prevailing narrative themes in reports that discuss Jorge Ramos’ actions.</p>

  <h3>Ramos the Activist</h3>
  <p>Ramos was characterized in numerous texts as a longtime “unabashed” (Rieder, 2015) and self-righteous activist—a “crusader” (Inskeep, 2015) for the rights of undocumented immigrants who has no compunction flouting journalistic conventions like maintaining objectivity if the cause demands he do so. He conflated the roles of anchor and advocate. Ramos “seems to think activism and advocacy are not incompatible with journalism” (Wright, 2015). Moreover, he has for some time been an “outspoken detractor” of Trump (Barbaro, 2015, p. A11). The conservative <em>National Review</em> (Tuttle, 2015) called him a “professional partisan.” He wields the freedom of expression he earned by becoming a U.S. citizen as a cudgel as he “interrogates” (Martínez, 2015; Miller, 2015; Tuttle, 2015) the subjects of his interviews. During an appearance on Fox News, “fellow Trump nemesis” (Earle, 2015) Megyn Kelly asked Ramos if his “combative approach” had led to the “spat” (Carroll, 2015). </p>
  <p>Ramos admitted that the issue of immigration was “personal” (e.g. Miller, 2015). NBC News explained that to Trump’s supporters, Ramos is “an agenda-driving activist” (Dann &amp; Rafferty, 2015). Ramos decided “to use his platform as an advocate for immigration reform, which separates him from traditional TV news anchors,” two <em>Los Angeles Times</em> reporters explained (Battaglio &amp; Linthicum, 2015, p. E1). Characterizing criticism of Ramos from the Republican National Committee strategist Sean Spicer (Miller, 2015), George Stephanopoulos (2015) of ABC News suggested Ramos was “more advocate than journalist.” To a communication consultant (Hill, 2015) writing for the <em>Pittsburgh Post-Gazette</em>, “it became clear pretty quickly that Mr. Ramos was on a mission” (p. A7). A <em>Politico</em> reporter quoted in <em>The Huffington Post</em> said firmly, “[T]his is bias: taking the news personally, explicitly advocating an agenda” (Arana, 2015b). Ramos had recast himself, according to Bill O’Reilly (2015) as “an advocate for people who enter the U.S.A. illegally. And that has superseded his job as a journalist.” </p>
  <p>Ramos’ activism was not a recent development. He is well known for a “confrontational interview style,” (Page, 2015, p. A7) and “has a history of holding presidential candidates very close to the fire on issues he believes to be of deep concern to Latinos” (Ross, 2015). <em>The Washington Post</em>’s Michael Miller (2015) clarified the history, noting that it was “only in the past dozen years that Ramos has allowed himself to become an advocate” on immigration—to the point, said a conservative lobbyist quoted by Miller (2015), that “he reports like a lobbyist for the National Council of La Raza or a democratic pundit.” In the days after the confrontation and his ejection, Ramos was “on the defensive,” wrote a Los Angeles Times reporter (Mai-Duc, 2015b). He spent a great deal of time “trying to explain how his self-proclaimed position as an advocate for immigration reform does not undercut his role as a journalist” (Mai-Duc, 2015b). </p>
  <p>The emergence of this theme is not surprising in light of how journalists typically treat activism—even if it originates in one of their own. Gitlin (1980) claimed that the media “process” (p. 5) activism by carefully controlling the activist’s image. Reporters “absorb what can be absorbed into the dominant structure and push the rest to the margins of social life” (p. 5). They tend to focus on easily addressable “single grievances” that in no way threaten the “fundamental social relations” (p. 122) at work. Missing is a systemic examination of what compelled the activists to protest. Journalists cover “the event, not the condition, not the consensus; the fact that ‘advances the story,’ not the one that explains it” (p. 122). Stories revolve around information provided by officials and suggest that activists constantly struggle to disseminate their message. Activists appear in stories only if they match the journalist’s “prefabricated images of what an oppositional leader should look and sound like: theatrical, bombastic, and inventive in the ways of packaging messages” (p. 154). More recent research reveals that activists for unpopular causes are treated as bothersome nuisances (DiCicco, 2010) who must be able to stage dramatic events of professional caliber (Bishop, 2012/13) that draw the journalist’s attention and reach a distracted public. Activists must offer to reporters a steady diet of “novelty, polemic, confrontation, and controversy” (Jha, 2008). But despite the more professional approach, reporters continue to marginalize groups that espouse unpopular causes or that challenge hallowed values and ideas. “Don’t try to hijack a press conference unless you’re wearing a ‘Code Pink’ or ‘Black Lives Matter’ t-shirt,” admonished a Georgia newspaper (“Facts,” 2015). By confronting Trump, Ramos challenged a newly-hallowed idea: infotainment. </p>

  <h3>Ramos the Journalist</h3>
  <p>While some colleagues lauded Ramos for his persistence, a central narrative theme of his confrontation with Trump suggested he had clearly breached the field’s ethics. “He was editorializing the entire time,” argued MSNBC’s Joe Scarborough, “write an editorial, all right?” News anchors, claimed the <em>USA Today’s</em> Rieder (2015), “are supposed to be down the middle,” and should keep “their personal opinions and ideologies to themselves.” According to a <em>Providence Journal</em> columnist, Ramos’ “unnecessary theatrics stole the oxygen from everyone else’s efforts to challenge Trump” (Patinkin, 2015, p. B9).  He “found himself at the center of the story” (Mazzei, 2015). The “form of journalism” practiced by Ramos “that day was neither hard-hitting nor responsible” (Patinkin, 2015, p. B9). By “pretending he was bullied and pretending he was thrown out of the room? He’s making himself the story,” asserted <em>Morning Joe’s</em> Mika Brzezinski (Mai-Duc, 2015b), apparently forgetting that many of her colleagues routinely commit the same ethical violation. </p>
  <p>Journalists also gave readers a refresher course in press conference protocol. “At an orderly news conference,” opined the <em>Providence Journal’s</em> Patinkin (2015), “it’s simple-minded to think shouting chaotically is hard-hitting. Or responsible. It’s neither” (p. B9). The media critic Howard Kurtz (2015) scolded Ramos, whom he claimed “wanted to force a confrontation.” About Ramos’ alleged failure to wait to be called on, he said “I’m sorry—that’s not some polite society rule.” Even one of Ramos’ defenders, the attorney Raúl Reyes (2015), acknowledged that it was “Trump’s news conference, and he had the right to run it as he pleased.”</p>
  <p>The popular conservative talk show host Bill O’Reilly (2015) asserted that candidates have the right to “regulate” press conferences—“and if they don’t, chaos will ensue,” he said. O’Reilly also contended that Ramos was too close to the story. “You should excuse yourself from it…or become like me, a commentator,” he said during Ramos’ appearance on <em>The O’Reilly Factor</em> (Mai-Duc, 2015b). <em>USA Today’s</em> Rem Rieder (2015) contended that it was “hard to imagine a prominent network anchor—Tom Brokaw say—use such outspoken and opinionated language.”</p>
  <p>Some colleagues did defend Ramos, saying that “the best journalism happens when you take a stand” (e.g. Peralta, 2015) and that his “only weapon is a question” (e.g. Tuttle, 2015), but at times their defense was framed in order to make his approach seem outdated, even anachronistic. Ramos “did something that’s not totally uncommon for reporters to do, which is to stand up and keep asking a question, even if the person you’re asking doesn’t really want to answer it,” said CNN’s Sara Murray (Hartmann, 2015). “Think of him as a combination of Peter Jennings, Anderson Cooper, CNN, with a little bit of an edge to him, and maybe something like <em>Mother Jones</em>,” opined NPR’s David Folkenflik (Inskeep, 2015). Yet even some of those defenders criticized Ramos for being rude. Trump “wasn’t dodging anyone that day,” wrote one journalist. “It was a news conference, for goodness sake;” an impatient Ramos “chose to butt in line…and ambush when there was no need to” </p>
  <p>(Patinkin, 2015). </p>

  <h3>Ramos the Kingmaker</h3>
  <p>While the Ramos-Trump narrative generally praised Trump’s ability to manage the press, several journalists noted that he tangled with Ramos at his peril, given the high esteem with which Ramos is held by the Latino community. Trusted, credible—even “venerated” (Glenza, 2015) by “millions of Hispanic Americans” (Reyes, 2015), Ramos is “[r]egularly included on lists of the most influential Latino American politicians, pundits, and journalists” (Glenza, 2015). Several journalists (e.g. Sherman, 2015) labeled it “the Jorge Ramos effect.” Writing in <em>USA Today</em>, Raúl Reyes (2015) noted it is “difficult to understate the importance of Ramos in the Hispanic community.” The clash, claimed a <em>Fortune</em> reporter, could have “more lasting repercussions for [Trump’s] presidential aspirations,” (Sherman, 2015) thanks to the reverence felt for Ramos by his television audience. “The problem” for Trump was Ramos’ “enormous pulpit,” argued one journalist (Tuttle, 2015).</p>
  <p>The discussion of Ramos’ celebrity mitigated his impact as an anchor and reporter, even as he was called the “most powerful journalist in Spanish-language television” (Battaglio, 2015) and, as mentioned above, the “Walter Cronkite” of Latino journalists (e.g. Przybyla, 2015). The narrative suggests Ramos was well aware of his role, even arrogant. He expected “a certain degree of respect and, if not, deference” (Cornish, 2015) because of his influence on Latino voters. </p>

  <h3>Ramos the Other</h3>
  <p>Texts devalued Ramos’ approach to reporting by subtly and unsubtly othering him. Kurtz (2015), for example, reminded readers that Ramos was a “legal Mexican immigrant.” Several of his colleagues noted Ramos’ dual citizenship. “Every four years, the English-speaking world discovers Jorge Ramos,” wrote reporters for the <em>Los Angeles Times</em> (Battaglio &amp; Linthicum, 2015). The clash gave many white readers their first exposure to Ramos, one reporter (Miller, 2015) explained. Few of the journalists (e.g. Glenza, 2015) whose work was analyzed for this article noted the racist tone of Trump’s call for Ramos to “go back to Univision.” Yet Ramos was seen to represent a Latino media, which to that point had covered Trump “more aggressively than their mainstream counterparts” (Parker, 2015). Ramos, said NPR’s David Folkenflik, “comes out of a slightly different tradition” (Inskeep, 2015) of reporting. Ramos’ oft-criticized advocacy “has been much more common in the ethnic media,” according to <em>USA Today’s</em> ombudsperson Rem Rieder (2015). Even claiming, as one columnist did, that Trump “unleashed a shot that would echo through the media—particularly Hispanic media” (Page, 2015, p. A7) suggests that Ramos reaches only part of the broader audience. </p>
  <p>Right-wing news sources delivered the kind of bigoted assertions their critics have come to expect. Fox News commentator Jesse Watters said Ramos “acted like an illegal alien and got treated like one” (Wemple, 2015). A <em>New York Daily News</em> story published the day after the confrontation was headlined “TV Reporter Gets Adios-ed in Iowa” (Katz, 2015). “Trump just found his new best amigo” as a result of the dispute, wrote a <em>Denver Post</em> columnist (Navarrette, 2015a, p. Z2). In fact, one cited the opinion held by “many folks” that “an anchor, reporter, or columnist named ‘Sánchez,’ ‘Rodríguez,’ or ‘Navarrette’ is Hispanic first, journalist second” (Navarrette, 2015a, p. Z2). Writing in September for <em>The Daily Beast</em>, Navarrette (2015b), asserted Ramos actually played “into every negative stereotype that Americans subscribe to about Mexicans” who illegally enter the U.S. Those who believe undocumented immigrants are “pushy rule breakers who don’t wait their turn” would have that belief confirmed by Ramos’ “filibuster.” Crusading for immigration reform but not advocating how individuals should vote struck one journalist (Tuttle, 2015) as disingenuous: “That level of fraud takes <em>cojones</em> [reporter’s italics],” he wrote, Ramos’ “daily crusade” is “a sort of made-for-television La Raza protest” (Tuttle, 2015). </p>
  <p>One reporter suggested that Ramos might have a violent personality. After holding Obama’s feet to the fire in an earlier interview about the failure to pass an immigration reform bill, Ramos had said, “Now is the turn of Republicans.” The clash with Trump showed Ramos is “now living up to his threat” (Miller, 2015). Othering was evident even when articles were critical of Trump; a <em>Salon</em> writer summarized the confrontation in the hallway after Ramos’ ejection: “We have a white American telling a brown American to get out of <em>his</em> (author’s italics) country.” To the Trump supporter, Ramos was “an outsider, an alien” (Illing, 2015). </p>

  <h3>Ramos the Publicity Hound</h3>
  <p>Some reports suggested that Ramos was anything but genuine in his attempt to put his view of immigration reform on the nation’s agenda, that the confrontation with Trump was little more than play-acting. “Isn’t he just about the biggest name of that network?” asked NPR’s Steve Inskeep (2015), referring to Univision. <em>Newsweek</em> (Martínez, 2015) noted that “hogging the microphone isn’t free speech.” The <em>National Review</em> noted that Ramos was “not above a good publicity stunt,” (Wright, 2015) referring to Ramos swimming across the Rio Grande in July 2014 to dramatize the dangers faced by undocumented immigrants as they try to enter the United States. The post-clash exchange with Trump was “the kind of interview that would be a TV ratings boon for a celebrity anchor” (Mazzei, 2015).</p>
  <p>Ramos’ persistent questioning at Trump’s press conference was “a stunt, one that virtually guaranteed” that he “would be making the TV rounds,” asserted Howard Kurtz (2015). After the confrontation, Ramos “went into heavy rotation” on the following day’s news programs (Battaglio &amp; Linthicum, 2015). Bill O’Reilly (2015) said Ramos clearly “grandstanded the situation,” in the hope of improving his own public image, something “frowned upon” (Martínez, 2015) by journalists. Ramos’ appearances on talk shows after the clash were framed as opportunities to generate publicity for his cause, not as chances for Ramos to explain his side of what took place in Dubuque. He was an opportunist, just another made-for-TV personality shilling for his causes.</p>

  <h3>Ramos the Trump Clone</h3>
  <p>Perhaps the most unexpected theme to emerge from the texts revolved around the idea that Ramos and Trump are in fact a great deal alike, that they share personality attributes. The two men are “notoriously adversarial by nature…and view argument as a form of public combat” (Miller, 2015).  They had developed a “creepy co-dependent relationship” (Navarrette, 2015a, p. Z2). An official with a conservative group that reaches out to Latino voters observed that “the collision of the two no-holds-barred styles made for a ‘surreal’ political spectacle”; neither Ramos nor Trump, he said, “do things in a normal way” (McLaughlin, 2015).  </p>
  <p>Through his actions, Ramos “wanted to achieve the same kind of grandstanding effect Trump is sometimes accused of” (Patinkin, 2015, p. B9). A <em>Denver Post</em> columnist concluded that Ramos is an “egomaniac who loves the sound of his own voice as much as Trump adores his,” and that both men “simply wanted to attract attention to themselves” (Navarrette, 2015a, p. Z2).  Indeed, both Trump and Ramos “came out winners” (Navarrette, 2015b) in this “clash of conflict junkies” (Miller, 2015) —Trump affirmed his toughness with the press, while Ramos generated awareness for his cause.</p>
</section>
<section>
  <h3>Conclusions</h3>
  <p>A key limitation of this study is the fact that the Ramos-Trump clash took place when reporters were particularly fascinated with Trump––with “the absence of anything resembling a conventional political filter” on him (Barbaro, 2015). One admitted that she “no longer pretend to cover” Trump in a balanced and objective fashion (Parker, 2015). By late fall 2015, after the tragic terrorist attacks in Paris and in San Bernardino, California, journalists more frequently called out Trump for his bigotry, particularly after he advocated a ban on Muslims entering the United States and failed to disavow an endorsement from former Ku Klux Klan leader David Duke. Yet despite increased scrutiny, Trump’s poll numbers improved, much to the chagrin of many in the Republican Party. Trump then amassed a string of impressive primary victories. Journalists were again content to make the most of the “ratings bonanza in the form of a bombastic reality television star” (Parker, 2015). Only a few, like Charles Blow (2015) of <em>The New York Times</em>, acknowledged the field’s “complicity in the shallow farce.” Most of Blow’s colleagues continued to be mesmerized by the “irresistible spectacle” (Barbaro, 2015) of Trump’s campaign, despite the concern expressed in several texts that the clash might derail Trump’s presidential aspirations. </p>
  <p>Only Ramos fully knows his motivations for pursuing Trump with such vigor. But it is telling that where a journalist who “assertively ambushes” (Miller, 2015) a reluctant or evasive official might have once earned praise—from colleagues, if not from the public—Ramos, determined to have Trump justify his immigration policy, became the catalyst for a round of ersatz paradigm repair. The texts analyzed here coalesce into a collective overreaction, a lecture on proper press-conference decorum from self-appointed arbiters of journalistic practice done—ironically—to reaffirm today’s much maligned model of false equivalency-based journalism. Ramos’ colleagues put rhetorical distance between themselves and him. His “aggressive style” (Scherer, 2015) was recast as the behavior of a self-important, zealous, possibly violent, activist. Even if Ramos had assumed only “the posture of adversarialism” (Meltzer, 2009, p. 73) as he grappled with Trump (and his security detail), this narrative asserts that he had flouted the new journalistic tradition of “he said-she said” impartiality that does not anger advertisers or alienate even a single audience member. Ramos’ reversion to the watchdog role “makes the traditionalists uneasy,” argued Rieder (2015). Ramos refused to aimlessly heighten the drama that has swirled around Trump since he announced his candidacy. He wanted actual answers. Thus, the field may now have reached the point where a “stylized and ritualized” (Bennett &amp; Serrin, 2005, p. 179) take on “pulling no punches” (Rieder, 2015) is a troublesome anachronism, where even the appearance of dogged reporting is a “rupture” (Zelizer, 1993, p. 224), and its practitioners rude and overzealous nuisances.</p>
</section>
<hr />
<section>
  <h2>References</h2>
  <p class="references">Allen, C. (1993). News conferences on TV: Ike-age politics revisited. <em>Journalism Quarterly, 70</em>, 13-25. </p>
  <p class="references">Arana, G. (2015a, August 26). Trump doubles down, tells Lauer that Ramos ‘was totally out of line.’ <em>The Huffington Post</em>. Retrieved from <a href="http://www.huffingtonpost.com" target="_blank">http://www.huffingtonpost.com</a>. </p>
  <p class="references">Arana, G. (2015b, August 27). Jorge Ramos producer speaks out about press conference incident. <em>The Huffington Post</em>. Retrieved from <a href="http://www.huffingtonpost.com" target="_blank">http://www.huffingtonpost.com</a>. </p>
  <p class="references">Arana, G. (2015c, September 3). Jorge Ramos schools Bill O’Reilly: On human rights, ‘you have to take a stand.’ <em>The Huffington Post</em>. Retrieved from <a href="http://www.huffingtonpost.com" target="_blank">http://www.huffingtonpost.com</a>.  </p>
  <p class="references">Barbaro, M. (2015, August 27). Testy news conference exchange puts Trump quirks on display. <em>The New York Times</em>, p. A11. </p>
  <p class="references">Battaglio, S. (2015, August 27). Trump unapologetic in scraps with media; Republican boots Univision reporter from event, keeps aiming barbs at Fox anchor. <em>Providence Journal</em>, p. A9.</p>
  <p class="references">Battaglio, S., &amp; Linthicum, K. (2015, August 27). Trump tangles with Jorge Ramos; Univision anchor has pushed the issue of immigration before. <em>Los Angeles Times</em>, p. E1. </p>
  <p class="references">Baym, G. (2005). <em>The Daily Show</em>: Discursive imagination and the reinvention of political journalism. <em>Political Communication, 22</em>, 259-276. </p>
  <p class="references">Benjamin, W. (1982). Unpacking my library. In H. Arendt (Ed.), <em>Illuminations: Essays and reflections</em>. New York: Schocken. </p>
  <p class="references">Bennett, W. L. (2009). <em>News: The politics of illusion</em>. New York: Pearson. </p>
  <p class="references">Bennett, W. L., &amp; Livingston, S. (2003). A semi-independent press: Government control of journalistic autonomy in the political construction of news. <em>Political Communication, 20</em>, 359-362. </p>
  <p class="references">Bennett, W. L., &amp; Serrin, W. (2005). The watchdog role. In G. Overholser &amp; K. H. Jamieson (Eds.), <em>The Press</em> (pp. 169-188). New York: Oxford University Press.</p>
  <p class="references">Benson, R. (2008). Journalism: Normative theories. In W. Donsbach (Ed.), <em>The international encyclopedia of communication</em> (pp. 2,591-2,597). Malden, MA: Wiley-Blackwell. </p>
  <p class="references">Berg, K. (2015, August 26). Donald Trump, Jorge Ramos feud heats up on ‘Today,’ ‘GMA.’ <em>The Hollywood Reporter</em>. Retrieved from <a href="http://www.hollywoodreporter.com" target="_blank">http://www.hollywoodreporter.com</a>.</p>
  <p class="references">Berkowitz, D. (1997). Non-routine news and newswork: Exploring a what-a-story. In D. Berkowitz (Ed.), <em>Social meanings of news</em> (pp. 362-375). Thousand Oaks, CA: Sage. </p>
  <p class="references">Bishop, R. (2012/13). A textual analysis of Ford’s “Drive One” campaign: Introduction of the domesticated journalist. <em>The Image of the Journalist in Popular Culture Journal, 4</em>, 1-31. </p>
  <p class="references">Blow, C. (2015, August 27). Enough is enough. <em>The New York Times</em>. Retrieved from <a href="http://www.nytimes.com" target="_blank">http://www.nytimes.com</a>. </p>
  <p class="references">Boorstin, D. (1962). <em>The Image: A guide to pseudo-events in America</em>. New York: Vintage. </p>
  <p class="references">Bruner, J. (1991). The narrative construction of reality. <em>Critical Inquiry, 18</em>, 1-21. </p>
  <p class="references">Brzezinski, M., &amp; Scarborough, J. (Hosts). (2015, August 26). <em>Morning Joe</em> [Television broadcast]. Secaucus, N.J.: MSNBC. </p>
  <p class="references">Campbell, C. (2015, July 23). ‘You’re finished’: Watch Donald Trump tell a reporter he should be ashamed of his question. <em>Business Insider</em>. Retrieved from <a href="http://www.businessinsider.com" target="_blank">http://www.businessinsider.com</a>. </p>
  <p class="references">Campbell, M. (2015, August 26). The question Jorge Ramos tried to ask—and why more reporters should ask it, too. <em>The World</em>. Minneapolis: Public Radio International. Retrieved from <a href="http://www.pri.org" target="_blank">http://www.pri.org</a>. </p>
  <p class="references">Carroll, R. (2015, August 26). Jorge Ramos tells Megyn Kelly: Trump a would-be dictator with dangerous ideas. <em>The Guardian</em>. Retrieved from <a href="http://www.theguardian.com" target="_blank">http://www.theguardian.com</a>. </p>
  <p class="references">Christians, C., Glasser, T., McQuail, D., Nordenstreng, K., &amp; White, R. (2009). <em>Normative theories of the media</em>. Champaign, IL: University of Illinois Press. </p>
  <p class="references">Cooper, A. (Host). (2015, August 27). Trump: Ramos is an ‘advocate,’ not a journalist. [Television broadcast]. Atlanta: Cable News Network. Retrieved from <a href="http://www.cnn.com" target="_blank">http://www.cnn.com</a>. </p>
  <p class="references">Cooper, B. (2015, September 1). ‘Presser’ tempest: It’s protocol, not politics. Dubuque <em>Telegraph-Herald</em>, p. A4. </p>
  <p class="references">Cornish, A. (Host). (2015, August 27). Univision anchor Jorge Ramos removed from Trump press conference. <em>All Things Considered</em>. Washington, D.C.: National  Public Radio. Retrieved from <a href="http://www.npr.org" target="_blank">http://www.npr.org</a>. </p>
  <p class="references">Cuomo, C. (Host). (2015, August 27). Ramos reacts to Trump clash. <em>New Day</em> [Television broadcast]. Atlanta: Cable News Network. Retrieved from <a href="http://www.cnn.com" target="_blank">http://www.cnn.com</a>. </p>
  <p class="references">Dann, C., &amp; Rafferty, A. (2015, August 25). The Lid: You’re outta here. <em>NBCNews.com</em>. Retrieved from <a href="http://www.nbcnews.com" target="_blank">http://www.nbcnews.com</a>. </p>
  <p class="references">Diamond, H. (2015, August 27). Donald Trump: Jorge Ramos ‘like a madman.’ <em>CNN.com</em>. Retrieved from <a href="http://www.cnn.com" target="_blank">http://www.cnn.com</a>. </p>
  <p class="references">DiCicco, D. (2010). The public nuisance paradigm: Changes in mass media coverage of political protest since the 1960s. <em>Journalism &amp; Mass Communication Quarterly, 87</em>, 135-153. </p>
  <p class="references">Donahue, G., Tichenor, P., &amp; Olien, C. (1995). A guard dog perspective on the role of the media. <em>Journal of Communication, 45</em>, 115-132.   </p>
  <p class="references">Earle, G. (2015, August 27). Donald Trump booted Univision anchor for ‘raving like a madman.’ <em>New York Post</em>. Retrieved from <a href="http://www.nypost.com" target="_blank">http://www.nypost.com</a>.</p>
  <p class="references">Eason, D. (1981). Telling stories and making sense. <em>Journal of Popular Culture, 1</em>, 125-129. </p>
  <p class="references">Facts, not accuracy: Reporter’s immigration harangue against Trump backfired. (2015, August 27). <em>The Augusta Chronicle</em>, p. A4. </p>
  <p class="references">Finnegan, W. (2015, October 5). The man who wouldn’t sit down. <em>The New Yorker</em>. Retrieved from <a href="http://www.newyorker.com" target="_blank">http://www.newyorker.com</a>. </p>
  <p class="references">Fisher, W. (1989). <em>Human communication as action: Toward a philosophy of reason, value, and action</em>. Columbia, SC: University of South Carolina Press. </p>
  <p class="references">Foley, E. (2015, August 25). Donald Trump kicks Jorge Ramos out of press conference. <em>The Huffington Post</em>. Retrieved from <a href="http://www.huffingtonpost.com" target="_blank">http://www.huffingtonpost.com</a>. </p>
  <p class="references">Foss, S. (2009). <em>Rhetorical criticism: Exploration and practice</em>. Long Grove, IL: Waveland Press. </p>
  <p class="references">Garbe, W. (2015, August 26). Trump: U.S. needs strength. Dubuque <em>Telegraph-Herald</em>, p. A1. </p>
  <p class="references">García-Ríos, S. (2015, August 28). The ‘Jorge Ramos effect’ could hurt Donald Trump. <em>Time</em>. Retrieved from <a href="http://www.time.com" target="_blank">http://www.time.com</a>. </p>
  <p class="references">Gitlin, T. (1980). <em>The whole world is watching: Mass media in the making and the unmaking of the New Left</em>. Berkeley, CA: University of California Press. </p>
  <p class="references">Glenza, J. (2015, August 26). Spanish language media condemn Donald Trump over reporter’s ejection. <em>The Guardian</em>. Retrieved from <a href="http://www.theguardian.com" target="_blank">http://www.theguardian.com</a>. </p>
  <p class="references">Graber, D. (2010). <em>Mass media and American politics</em> (8th ed.). Washington, D.C.: Congressional Quarterly Press. </p>
  <p class="references">Gross, T. (Host). (2015, October 5). Univision’s Jorge Ramos discusses journalism and that Donald Trump news conference. <em>Fresh Air</em> [radio broadcast]. Philadelphia: WHYY-FM. </p>
  <p class="references">Guthrie, M. (2015, August 26). Donald Trump vs. the media: Who’s winning the war of words? <em>The Hollywood Reporter</em>. Retrieved from <a href="http://www.hollywoodreporter.com" target="_blank">http://www.hollywoodreporter.com</a>.</p>
  <p class="references">Hall, S. (1975). Introduction. In A. C. H. Smith (Ed.), <em>Paper voices: The popular press and social change</em> (pp. 11-24). London: Chatto and Windus. </p>
  <p class="references">Hannity, S. (Host). (2015, August 26). <em>The Sean Hannity Show</em>. [Television broadcast]. New York: Fox News Network. </p>
  <p class="references">Hartmann, E. (2015, August 26). ‘Go back to Univision’: Trump boots journalist Jorge Ramos from press conference. <em>New York</em>. Retrieved from <a href="http://www.nymag.com" target="_blank">http://www.nymag.com</a>. </p>
  <p class="references">Heritage, J., &amp; Clayman, S. (2013). The changing tenor of questioning over time: Tracking a question form across U.S. presidential press conferences, 1953-2000. <em>Journalism Practice, 7</em>, 481-501. </p>
  <p class="references">Hill, R. (2015, August 31). Media mash-up; both Trump and Ramos prevailed in a battle for the floor. <em>Pittsburgh Post-Gazette</em>, p. A7. </p>
  <p class="references">Hindman, E. (2005). Jayson Blair, it>The New York Times, and paradigm repair. <em>Journal of Communication, 55</em>, 225-241. </p>
  <p class="references">Illing, S. (2015, August 28). Donald Trump plays a dangerous game: The dark side of making America great again. <em>Salon</em>. Retrieved from <a href="http://www.salon.com" target="_blank">http://www.salon.com</a>. </p>
  <p class="references">Inskeep, S. (Host). (2015, August 26). Donald Trump escalates his fight with the media. <em>Morning Edition</em> [Radio broadcast]. Washington, D.C.: National Public Radio. </p>
  <p class="references">Jacobs, B. (2015, August 26). Donald Trump ejects Latino anchor as Iowa campaign gains ground. <em>The Guardian</em> (U.S. Edition). Retrieved from <a href="http://www.theguardian.com" target="_blank">http://www.theguardian.com</a>. </p>
  <p class="references">Jamieson, K. H., &amp; Campbell, K. K. (1997). <em>The interplay of influence: News, advertising, politics, and the mass media</em>. Belmont, CA: Wadsworth. </p>
  <p class="references">Jerde, S. (2015, October 26). Trump camp tries to justify barring Univision reporters from Florida rally. <em>Talking Points Memo</em>. Retrieved from <a href="http://www.talkingpointsmemo.com" target="_blank">http://www.talkingpointsmemo.com</a>. </p>
  <p class="references">Jha, S. (2008). Why they wouldn’t cite from sites: A study of journalists’ perceptions of social movement websites and their impact on their coverage of social protest. <em>Journalism, 9</em>, 711-732. </p>
  <p class="references">Katz, C. (2015, August 26). TV reporter gets adios-ed in Iowa. <em>New York Daily News</em>, p. 11. </p>
  <p class="references">Kaufman, S. (2015, September 3). Jorge Ramos puts Bill O’Reilly in his place: You’re not the right person to lecture me on advocacy and journalism. Retrieved from <a href="http://www.salon.com" target="_blank">http://www.salon.com</a>. </p>
  <p class="references">Kitch, C. (2002). A death in the American family: Myth, memory, and national values in the media mourning of John F. Kennedy Jr. <em>Journalism &amp; Mass Communication Quarterly, 79</em>, 294-309. </p>
  <p class="references">Klapproth, D. (2004). <em>Narrative as social practice: Anglo-Western and Australian aboriginal oral traditions</em>. New York: Morton de Gruyer. </p>
  <p class="references">Kurtz, H. (2015, August 27). Why Jorge Ramos crossed the line in confronting Donald Trump. <em>Fox News</em>. Retrieved from <a href="http://www.foxnews.com" target="_blank">http://www.foxnews.com</a>. </p>
  <p class="references">Lauer, M. (Host). (2015, August 26). Donald Trump speaks out. <em>Today</em> [Television broadcast]. New York: National Broadcasting Company. </p>
  <p class="references">Lawler, K. (2015, August 28). Ricky Martin slams Trump’s treatment of Latinos. <em>USA Today</em>, p. 11B. </p>
  <p class="references">Lee, K. (2015, August 26). News anchor evicted from Trump event. <em>Los Angeles Times</em>, p. A10. Retrieved from <a href="http://www.latimes.com" target="_blank">http://www.latimes.com</a>.</p>
  <p class="references">Leibovich, M. (2015, September 29). Donald Trump is not going anywhere. <em>The New York Times Magazine</em>. Retrieved from <a href="http://www.nytimes.com" target="_blank">http://www.nytimes.com</a>. </p>
  <p class="references">Lemieux, G. (2015, September 2). Recognizing Trump before it’s too late. <em>Tampa Bay Times</em>, p. 9A. </p>
  <p class="references">Lewis, H. (2015, August 27). Jimmy Kimmel, Conan O’Brien mock Donald Trump-Jorge Ramos tiff. <em>The Hollywood Reporter</em>. Retrieved from <a href="http://www.hollywoodreporter.com" target="_blank">http://www.hollywoodreporter.com</a>. </p>
  <p class="references">Mai-Duc, C. (2015a, August 26). In taking on Jorge Ramos, Donald Trump may have tussled with the wrong media star. <em>Los Angeles Times</em>. Retrieved from <a href="http://www.latimes.com" target="_blank">http://www.latimes.com</a>. </p>
  <p class="references">Mai-Duc, C. (2015b, September 3). Jorge Ramos is on the defensive over his role as journalist and immigrant advocate. <em>Los Angeles Times</em>. Retrieved from <a href="http://www.latimes.com" target="_blank">http://www.latimes.com</a>. </p>
  <p class="references">Manoff, R. (1987). Writing the news (by ‘telling’ the story). In R. Manoff &amp; M. Schudson (Eds.), <em>Reading the news</em> (pp. 197-229). New York: Pantheon. </p>
  <p class="references">Martínez, J. (2015, August 26). Donald Trump and Jorge Ramos: Who was right? <em>Newsweek</em>. Retrieved from <a href="http://www.newsweek.com" target="_blank">http://www.newsweek.com</a>. </p>
  <p class="references">Mazzei, P. (2015, August 26). Donald Trump and Jorge Ramos, redux. <em>The Miami Herald</em>. Retrieved from <a href="http://www.miamiherald.com" target="_blank">http://www.miamiherald.com</a>. </p>
  <p class="references">McLaughlin, S. (2015, August 26). Activist anchor Jorge Ramos uses influence to push immigration agenda. <em>The Washington Times</em>. Retrieved from <a href="http://www.washingtontimes.com" target="_blank">http://www.washingtontimes.com</a>. </p>
  <p class="references">Meltzer, K. (2009). The hierarchy of journalistic cultural authority: Journalists’ perspectives according to news medium. <em>Journalism Practice, 3</em>, 59-74. </p>
  <p class="references">Miller, M. (2015, August 26). Jorge Ramos is a conflict junkie just like his latest target: Donald Trump. <em>The Washington Post</em>. Retrieved from <a href="http://www.washingtonpost.com" target="_blank">http://www.washingtonpost.com</a>. </p>
  <p class="references">Navarrette, R. (2015a, August 31). Trump and Ramos are meant for each other. <em>The Denver Post</em>, p. Z2. </p>
  <p class="references">Navarrette, R. (2015b, September 4). The Jorge Ramos Rorschach test. <em>The Daily Beast</em>. Retrieved from <a href="http://www.thedailybeast.com" target="_blank">http://www.thedailybeast.com</a>. </p>
  <p class="references">Newton, K. (2015, August 30). Ken Newton column. <em>St. Joseph News-Press</em>. Retrieved from <a href="http://www.newspressnow.com" target="_blank">http://www.newspressnow.com</a>.</p>
  <p class="references">Nichols, J. (2015, August 26). Jorge Ramos challenged both Trump and an increasingly absurd debate. <em>The Nation</em>. Retrieved from <a href="http://www.thenation.org" target="_blank">http://www.thenation.org</a>. </p>
  <p class="references">O’Reilly, B. (Host). (2015, August 27). Bill O’Reilly: Donald Trump vs. Jorge Ramos. <em>The O’Reilly Factor</em> [Television broadcast]. New York: Fox News Network. </p>
  <p class="references">Page, C. (2015, September 2). Trump, Ramos square off in clash of 2 major icons; from the left. <em>Dayton Daily News</em>, p. A7. </p>
  <p class="references">Parker, A. (2015, August 27). Trump gets earful in Spanish as Latino outlets air disdain. <em>The New York Times</em>, p. A1.  </p>
  <p class="references">Patinkin, M. (2015, September 2). In challenging Trump, Ramos blew it. <em>Providence Journal</em>, p. B9. </p>
  <p class="references">Peralta, E. (2015, August 26). Univision’s Jorge Ramos: Journalists must ‘denounce’ Trump’s ‘dangerous words.’ <em>The Two-Way</em>. Washington, D.C.: National Public Radio. Retrieved from <a href="http://www.npr.org" target="_blank">http://www.npr.org</a>. </p>
  <p class="references">Peyronnin, J. (2015, August 26). Trump v. Ramos. <em>The Huffington Post</em>. Retrieved from <a href="http://www.huffingtonpost.com" target="_blank">http://www.huffingtonpost.com</a>.</p>
  <p class="references">Phillips, C. (2015, September 1). The mainstream media should stop covering Donald Trump. <em>The Huffington Post</em>. Retrieved from  <a href="http://www.huffingtonpost.com" target="_blank">http://www.huffingtonpost.com</a>. </p>
  <p class="references">Przybyla, H. (2015, August 27). You shouldn’t lump Trump as a bully—technically speaking. <em>USA Today</em>, p. 1A. </p>
  <p class="references">Reyes, R. (2015, August 27). Trump’s endless summer of bigotry; candidate digs hole for GOP. <em>USA Today</em>, p. 7A. </p>
  <p class="references">Rieder, R. (2015, August 27). Univision’s Ramos not afraid to stand his ground. <em>USA Today</em>, p. 2B. </p>
  <p class="references">Rolly, P. (2015, August 28). Trump’s treatment of reporter reflects horrors of the past. <em>The Salt Lake Tribune</em>. Retrieved from <a href="http://www.sltrib.com" target="_blank">http://www.sltrib.com</a>.</p>
  <p class="references">Ross, J. (2015, August 25). Donald Trump kicked TV’s most influential Latino newsman out of a press conference. <em>The Washington Post</em>. Retrieved from <a href="http://www.washingtonpost.com/news/the-fix" target="_blank">http://www.washingtonpost.com/news/the-fix</a>.</p>
  <p class="references">Rucker, P. (2015, August 25). First, Trump booted Univision anchor Jorge Ramos out of his press conference. Then things got interesting. <em>The Washington Post</em>. Retrieved from <a href="http://www.washingtonpost.com" target="_blank">http://www.washingtonpost.com</a>. </p>
  <p class="references">Rucker, P., &amp; Costa, R. (2015, August 26). Trump kicks Latino reporter out of news conference. <em>The Washington Post</em>, p. A5. </p>
  <p class="references">Scherer, M. (2015, August 27). Univision’s Jorge Ramos: Reporters need to get tougher on Donald Trump. <em>Time</em>. Retrieved from <a href="http://www.time.com" target="_blank">http://www.time.com</a>. </p>
  <p class="references">Schleifer, M. (2015, August 25). Trump ejects Univision anchor from press conference. <em>CNN.com</em>. Retrieved from <a href="http://www.cnn.com" target="_blank">http://www.cnn.com</a>. </p>
  <p class="references">Schudson, M. (1978). <em>Discovering the news: A social history of American newspapers</em>. New York: Basic Books. </p>
  <p class="references">Schudson, M. (2003). <em>The sociology of news</em>. New York: W.W. Norton. </p>
  <p class="references">Schultz, M. (2015, August 26). Trump hit for latest Megyn diss. <em>New York Post</em>, p. 6. </p>
  <p class="references">Sherman, E. (2015, August 27). The Donald Trump-Jorge Ramos clash is a full-fledged media fight now. <em>Fortune</em>. Retrieved from <a href="http://www.fortune.com" target="_blank">http://www.fortune.com</a>. </p>
  <p class="references">Stelter, B. (2015, August 31). What really happened between Jorge Ramos and Donald Trump. <em>CNNMoney</em>. Retrieved from <a href="http://money.cnn.com" target="_blank">http://money.cnn.com</a>. </p>
  <p class="references">Stephanopoulos, G. (Host). (2015, August 26). Jorge Ramos addresses his confrontation with Donald Trump. <em>Good Morning America</em> [Television broadcast]. New York: American Broadcasting Company. </p>
  <p class="references">Sullivan, J. (2011, May/June). True enough. <em>Columbia Journalism Review</em>. Retrieved from <a href="http://www.cjr.org" target="_blank">http://www.cjr.org</a>.</p>
  <p class="references">Terkel, A. (2015, August 26). Donald Trump supporter tells U.S. citizen Jorge Ramos to ‘get out of my country.’ <em>The Huffington Post</em>. Retrieved from <a href="http://www.huffingtonpost.com" target="_blank">http://www.huffingtonpost.com</a>. </p>
  <p class="references">Tuchman, G. (1978). <em>Making news: A study in the construction of reality</em>. New York: Free Press. </p>
  <p class="references">Tuttle, I. (2015, August 26). Jorge Ramos is an immigration activist posing as a reporter. <em>National Review</em>. Retrieved from <a href="http://www.nationalreview.com" target="_blank">http://www.nationalreview.com</a>.  </p>
  <p class="references">Univision anchor kicked out of Donald Trump event. (2015, August 25). <em>The Hollywood Reporter</em>. Retrieved from <a href="http://www.hollywoodreporter.com" target="_blank">http://www.hollywoodreporter.com</a>.</p>
  <p class="references">Univision CEO blasts Donald Trump over Jorge Ramos flap: ‘Beneath contempt.’ (2015, August 26). <em>The Hollywood Reporter</em>. Retrieved from <a href="http://www.hollywoodreporter.com" target="_blank">http://www.hollywoodreporter.com</a>.</p>
  <p class="references">Wagner, M., &amp; Katz, C. (2015, August 27). He does a Kelly flop; now Trump likes Megyn. <em>New York Daily News</em>, p. 12.</p>
  <p class="references">Wemple, E. (2015, August 26). Fox News’ Jesse Watters says that Jorge Ramos ‘acted like an illegal alien and got treated like one.’ <em>The Washington Post</em>. Retrieved from <a href="http://www.washingtonpost.com" target="_blank">http://www.washingtonpost.com</a>. </p>
  <p class="references">Wood, L., &amp; Kroger, R. (2000). Doing discourse analysis: Methods for studying action in talk and text. Thousand Oaks, CA: Sage.</p>
  <p class="references">Wright, M. (2015, August 26). Jorge Ramos has a long history of activist ‘reporting.’ <em>National Review</em>. Retrieved from <a href="http://www.nationalreview.com" target="_blank">http://www.nationalreview.com</a>. </p>
  <p class="references">Zelizer, B. (1993). Journalists as interpretive communities. <em>Critical Studies in Mass Communication, 10</em>, 219-237.</p>
</section>
<hr />
