<h1>Dear Ladies of the Transition: Transsexuality in Spanish Films During and After Franco</h1>
<div>
  <p class="volume">
    Volume 8 | August 2015
  </p>
</div>
<section class="authors">
  <h4>Authors</h4>
  <p>
    <strong>Arnau Roig-Mora, Ph.D. Candidate</strong><br />
    Universitat Autònoma de Barcelona<br />
    University of Illinois Urbana-Champaign<br />
    Email: <a href="mailto:roig.arnau@gmail.com">roig.arnau@gmail.com</a>
  </p>
</section>
<hr />
<section>
  <h2>Abstract</h2>
  <p>This article compares two movies featuring transsexual protagonists made during the last years of Spain’s fascist dictatorship, <em>Mi Querida Señorita</em> and <em>Cambio de Sexo</em>. Both were presented to the censorship board, but while the former got released that same year (1972), the latter had to wait until after Franco’s death (1977). By comparing both movies and their treatment of transsexuality, this article locates the emerging new paradigm that was being defined at the time following Harry Benjamin’s work, while at the same time highlighting the limits of sex, gender, and sexuality transgressions under fascist censorship. The article explores the differences as well as the similarities between both texts in relation to their representation of people undergoing sex and gender transitions in order to understand the ideological transition that was taking place at the time in the public sphere of cinema in Spain.</p>
</section>
<hr />
<section>
  <h2>Introduction</h2>
  <p>The Spanish dictatorship of General Francisco Franco (1936-1975) saw the country change under a regime in which national cultural production was limited by institutionalized fascist ideology. Aware of the influence of media, Franco created a censorship institution (Junta Superior de Censura in 1937) and used state-controlled cinema newsreels called <em>Noticiarios y Documentales</em> or NO-DO (<em>News and Documentaries</em>) from 1943 until 1981 to “explain” the world to Spaniards from the regime’s point of view. Spain had only one state-owned TV channel, inspired by the Third Reich, from 1956 until 1966, when a second channel was launched (Palacio Arranz, 2002). Franco used his media and information control to weed out revolutionary ideas and foment a project of exaltation of Spanish folklore, an ideological return to a pre-war country and a nationalism exemplified by the motto “<em>España, una, grande y libre</em>” (“Spain, one, great and free”).</p>
  <p>Under such control, not only were all mentions of communism and socialism obliterated (or in some cases presented as the evil conspiracy endangering the country), but also all sorts of topics, such as divorce, gender discrimination, or resistance to authority were banned from the screen. Foreign films had to undergo a severe process of censorship until they were found suitable for Spanish audiences––even when it meant changing the script, the ending of the movie, or cutting entire scenes. Spaniards never saw Janet Leigh in the shower scene in <em>Psycho; Some Like It Hot</em> never made it to the screens for introducing homosexuality; and even <em>Breakfast at Tiffany’s</em> was considered “pornographic” (Gil, 2009). All in all, Spanish audiences were thus protected from pernicious ideas that could go against the regime, which was firmly based on Catholicism and labeled “dangerous” any expression of non-heterosexual, reproductive love or sex.</p>
  <p>Along with forbidden topics such as divorce, sex out of wedlock, and homosexuality, the dissonance between sex and gender was also off limits, something that radically changed after the dictator’s death and the inception of <em>La Movida Madrileña</em>, a countercultural movement that featured all these sexual dissidences in a prominent role. This change toward openness in the presence of sex and sexuality in culture has captured the interest of academia as a site for exploring the country’s change of mentality, but while Spanish cinema dealing with the LGBT community has been largely explored in specialized literature, such as Alberto Mira’s comprehensive volume <em>Miradas Insumisas</em> (2008), especially concerning the representation of gay and lesbian characters, transsexuality remains much less explored.</p>
  <p>There has been a lot of attention devoted to the work of internationally famous filmographer Pedro Almodóvar and his queer characters (Epps &amp; Kakoudaki, 2009; Edwards, 2001; Smith, 1994) but only one recent book focuses explicitly on transsexuality in Almodóvar’s films (Poyato Sánchez, 2014). Transsexual characters in Spanish cinema have gotten much less attention and their presence in academic research is mostly reduced to specific examples in broad sections dealing with other LGBT issues (Richmond Ellis, 1997; Perriam, 2013) as well as analyses of gender performance (Marsh &amp; Nair, 2004; Pastor, 2006), with only a few exceptions (Garlinger 2003). However, there is no archival work done in compiling the legacy of transsexuality in cinema, and much less an entire book dedicated to the topic. Indeed, most of the work on transsexuality has been done in the field of sociology (Nieto, 1998, 2003, 2008; Mejía, 2006; Soley-Beltrán, 2009), psychology (Becerra-Fernández , 2003), law (López-Galiacho Perona, 1998; Bustos Moreno, 2008), journalism (Hernaiz, 2007) and a more theoretical/philosophical approach in the work of Preciado (2002, 2008) and other queer theorists (Córdoba et al., 2005).</p>
  <p>This article is a first step toward addressing this academic gap, adding a new incursion into the topic of transsexuality in Spanish cinema, which can not only tell us more about acceptance of non-normative sexualities, but also about the ideological regulation of sex and gender through the culture. This article compares two productions, released before and after Franco’s death, in order to highlight the changes that took place in the representation of the topic. The movies under analysis are <em>Mi Querida Señorita</em> (henceforth <em>MQS</em>) (dir. Jaime De Armiñán, 1972) and <em>Cambio de Sexo</em> (henceforth CdS) (dir. Vicente Aranda, 1977). Both have been chosen for being fiction movies featuring a protagonist who transitions from one sex to another and for being produced during the 1970s. Both are mainstream movies as well, having been produced and released through mainstream channels for mass audiences. <em>MQS</em> remains the sole film dealing with gender transitioning released while Franco was still alive. Other films of the decade, like <em>Un Hombre Llamado Flor de Otoño</em> (dir. Pedro Olea, 1978) or <em>Ocaña, Un Retrato Intermitente</em> (dir. Ventura Pons, 1978) have been excluded for their focus on cross-dressing rather than transitioning, and <em>El Transexual</em> (dir. José Jara, 1977) for being an exceptionally rare and experimental movie that never reached wide enough distribution. Ignacio Iquino’s sexploitation movies (<em>La Tía de Carlos en Mini-falda</em> 1967 and <em>La Basura Está en el Ático</em>1979) have also been excluded for not belonging to mainstream cinema.</p>
  <p>What makes these movies representative of the late years of the regime, and perfect candidates for comparing them, is that both were originally going to be released around the same time (1972), but while <em>MQS’s</em> release was allowed by the censors, <em>CdS</em> had to wait five more years, until after the death of General Franco. What are the differences that permitted the former to be shown to the masses? How did each project deal with the issues of gender and sex, and where is the line that censors felt was crossed? By looking at both movies closely, we will see the shift in ideology before and after Franco’s death, as well as the different paradigm of representation that each movie uses when talking about transsexuality.</p>
  <p>Furthermore, transsexuality has long been the site for looking at the limits of sex and gender at a given moment, since it represents the ultimate transgression of the gender and sex binaries. By looking at the representation of this phenomenon, we question the understanding of these limits in a given society and can learn more about the predominant ideologies that were at work. Moreover, since it was after the decade of the 1970s that legislation on the issue, as well as medical regulations, started to change for transsexual people in Spain, together with an implosion of LGBT characters on screen, the 1970s themselves are a critical cultural time that must be analyzed to understand the subsequent years, up to our present moment, and these two movies capture the crossroads of this concrete topic (transsexuality) during and after the dictatorship and, as we will see, pave the way for the hegemonic understanding of transsexuality in the years to come––one crafted around the medical and pathological definition of transsexuality.</p>
  <p>For both films, I explore two main themes: the way the movie presents the characters and their own concerns with identity, transsexuality and sex/gender/sexuality; and the relationship of the characters with other people, the character’s socialization, and the role of institutions in that socialization, such as medical institutions, state, family, school, police, etc. Through those two axes, the article explores how sex, gender and sexuality are represented and intertwined in the two movies, revealing underlying ideologies that change from an avoidance of the topic in the earlier film to the</p>
  <p>medicalized process present in the latter.</p>
</section>
<hr />
<section>
  <h2>Context and Theoretical Framework</h2>
  <p>After the Spanish Civil War (1936-1939) General Francisco Franco established a fascist dictatorship in Spain that would last until his death in 1975. Already during the war, the fascist bloc had started to take control of radio and press, but cinema was disregarded for its frivolity (Cabrerizo Pérez, 2007). However, in the last years of the war, the Department of Propaganda created the National Department of Cinematography (1938), dedicated to the production of audiovisual propaganda, control of foreign production on the war, and control of national distribution of movies. Indeed, Franco understood the power of media in influencing ideology and, drawing on Mussolini and Hitler’s approach, created the longest-lasting censorship institution in Western Europe (Higginbotham, 1988). Censorship lasted until the last days of fascism, and the regime treated cinema and other media as influential state apparatuses.</p>
  <p>Media are part of what Althusser (1971) defined as “state apparatuses” in his re-reading of Marx. For Althusser, the way the state exerts its power is through Repressive State Apparatuses (RSA) and Ideological State Apparatuses (ISA). The former use violence to enforce society rules under its regime––the clearest example being the police and the military––while the latter work as enforcers of ideology. The concept of the ISA seems an essential frame from where to look at filmic texts, conceptualizing them as part of those apparatuses. Media become powerful tools for regulation and conforming of the self and function like subtle tools to enforce “normality” and separate “abnormal” minorities. While this “normality” became the hegemonic view (and was celebrated by the regime), Spanish censorship worked hard to remove all mention of abnormal minorities. Minorities are “defined by their deviation from a norm that is white, male, Christian and heterosexual [...] [they] share a common fate of relative invisibility and demeaning stereotypes” (Gross, 2001). Constructing minorities as “abnormal”––by not including them in the “normal” public space of media representation––media participate in a process of othering and denial of such minorities. Minoritized communities find no voice to their identities and lives in public culture in general, and mainstream media in particular. Franco’s regime wanted to make sure that such communities disappeared from popular culture so they could not permeate and establish themselves in society.</p>
  <p>Nevertheless, the ideological work of media goes far beyond a visible/invisible dichotomy (where visible equals good and invisible bad): The fact that a transsexual person is put onscreen does not mean such depiction is empowering, and casting him or her as deviant, criminal, or ill can do more harm than invisibility itself, for some of those concepts might remain ideologically attached to transsexuality. In 1974, Stuart Hall analyzed the construction of deviance and the role of media in perpetuating and enforcing such concept. Hall addressed the emergence of new political movements and their classification between “[being] legitimized publicly within the ‘political’ category, or de-legitimized by being assigned to the ‘deviant’ category” (1993, p. 66). Notwithstanding, Hall also noted that “[u]nder certain circumstances, legitimate political minorities are subjected to severe ‘status degradation’ ceremonies, and are lumped with the more marginal groups. They are then subject to quite different forms of public opprobrium, stigmatization, and exclusion. They have been symbolically de-legitimized” (1993, p. 66).</p>
  <p>While the number of movies dealing with any type of sex transition during Franco is reduced to <em>MQS</em>––whose status as an anomaly makes it an excellent text to analyze––Spain witnessed a proliferation of such films in the late 1970s and 1980s, a frequency of films with a transsexual protagonist that has never been reached afterward. However, the emergence of transgender issues in the cinema is not solely due to Franco’s death and the end of censorship. Other contextual developments were taking place roughly during the last years of the dictatorship that also fostered the social debate on the issue later on, such as the legal recognition of sex confirmation surgery in the Penal Code (1983) and the appearance of a diagnostic that validated transsexuality as a legal and medical matter in the American Psychiatric Association’s manual, DSM, which was and is the diagnostic reference for psychiatrists in Spain.</p>
  <p>The issue of transsexuality (and the possibility of gender confirmation surgery) started having a huge media presence through the case of Christine Jorgensen, the first American transsexual woman who had gender confirmation surgery in Denmark in the 1950s. Despite Jorgensen’s mediatization, and the efforts to legitimize transsexuality and transsexual people by endocrinologist Harry Benjamin, who published <em>The Transsexual Phenomenon</em> in 1966, Spain under Franco remained fairly impervious to such influences. News media was controlled by the regime (and did not mention such advances), and even if some Spanish doctors had access to international specialized literature and were able to read Benjamin’s recommendations, sex reassignment surgery remained illegal until 1983.</p>
  <p>The close relationship of transsexuality with its representation in visual media––stated explicitly in Benjamin’s work––is also pivotal in a national article explaining the first legal recognition of a gender transition in Spain in 1977 (Gradillas, 2003). In both cases, the medical practitioners and authors state that the presence on screen of such cases, as well as their visibility in the public sphere, are necessary for their acceptance and understanding. Also preoccupied with this link between science, power, and discursive formations of identity, Michael Franklin in his dissertation, <em>Spectacles in Transit: Reading Cinematic Productions of Biopower and Transgender Embodiment</em> (2011), exposes, precisely, these same interactions of visibility and the creation of medical/scientific categories. Franklin suggests that there is an active relationship with the media in that transgender people are “a minority group whose constitution via medicine and mass culture has animated their negotiation of social belonging” (Franklin, 2011, p. 6). He adds that since there’s a social fixation on the stripped-down body, and especially genitalia, as naturally evident truths about that person, and as validation for scientific observation, a visual representation of transgender people as well as the medical definition of a transgender person are pivotal for constituting transgender identity (p. 20).</p>
  <p>Looking at how Franco’s censorship accepted a certain way of transgressing the gender binary while rejecting another is important for understanding what ideological regulations the regime was trying to convey to its citizens. According to Michel Foucault (1971, 1973), it is the scientific gaze, and the visual representation of science, that creates scientific “knowledge.” This knowledge is then used in the management of life in society––Foucault’s “biopower” (1986, 1991)––and is the basis for societal control and rendering the bodies docile to the state. A Foucauldian approach to the two case studies––focused on the medical discourses being created around transsexuality––will unpack the interactions of science/medicine, cinema/visibility, and the regulation of sex and gender in Spain.</p>
</section>
<hr />
<section>
  <h2>Analysis</h2>
  <p><em>Mi Querida Señorita</em> was released in 1972, around the same time <em>Cambio de Sexo</em> was turned down by the censors. <em>MQS</em> features the famous actor José Luis López Vázquez in the role of Adela, the “dear lady” of the title, who lives in a small town and starts to feel jealous of her maid’s flirtations with guys and in discomfort about her abundant facial hair, which she needs to shave. After Isabelita (the maid) leaves her due to her jealousy and mood swings, Adela decides to go to the doctor and ask about her problems: “I’m a brave and strong woman, doctor; tell me what I have.” “You are brave and strong, indeed, but not a woman.” From that scene, we cut to Juan––Adela’s name after transitioning to a man––arriving in Madrid and trying to look for a job. In Madrid, he meets Isabelita again, but she does not seem to recognize him. They start a romance while Juan faces the hardships of finding a job without any training––just like Adela, he only knows how to sew. When he gets thrown out of the <em>pensión</em> where he’s staying, he returns to the village as Adela, but starts coming out to some people as a man. He finally returns to Madrid, and he and Isabelita end up together in a happy ending that had one last sentence censored: the one where Isabelita implies that she had known the whole time that Juan was also her “dear lady.”</p>
  <p><em>Cambio de Sexo</em> was first named <em>Una Historia Clínica<sup>1</sup></em> with the intention of avoiding censorship (Roca Sastre, 1977) and presenting the movie as a real and educational story about transsexuality. It did not convince Franco’s censors and had to wait until after Franco’s death to be released in 1977. It narrates the story of José María, an androgynous boy who is bullied by friends and family alike for his mannerisms and effeminacy. His father takes him to Barcelona in a trip to fix his masculinity, and although José María never consummates the sex his father wants him to have with a prostitute, that trip is crucial for his personal journey of discovery. That night he sees, for the first time, Bibi Andersen, a transsexual woman who captivates audiences in a cabaret bar with her feminine performance and male genitalia. José María, much as Juan in <em>MQS</em>, will escape to the big city and start living gradually as María José. Under Bibi’s mentorship, she will piece together who she wants to be and, after a few heartbreaks and disappointments––which means coming back to her parents and trying to live as José María for a while––she will find love and get surgery to become the woman she “feels to be.”</p>
  <p>Both movies have some parallelisms in form: They set up the characters and then make the spectator start a journey of self-discovery, accompanying the protagonists to the big city (Madrid and Barcelona, the biggest two in Spain) where they can live and be their “new” selves; both will have to return to their hometowns and mend the wounds of their lives in the city, but will soon realize that there is no going back; finally, both decide to try again and finally succeed in their personal and sentimental goals. However they also have asymmetries, especially regarding their status as transgender people: whereas José María will slowly and gradually “become” María José, the change from Adela to Juan is immediate and happens in an ellipsis between two shots; the difficulties in the city on their first arrivals are more related to performing masculinity successfully for Juan as much as it is a biological and corporal issue for María José, since her body does not “match her mind”; their return home is almost liberating for Juan, who has the opportunity to come out to some of his former neighbors, while María José goes back as José María to be under the father’s wing––and violence; <em>MQS</em> has an easy, happy ending, as Juan’s love story with Isabelita is the central plot in the movie. On the other hand, María José will have to give up her friendship with Bibi to achieve her happy ending, as well as go through cosmetic and surgical procedures that are the focus of the final segment of the movie.</p>
</section>
<hr />
<section>
  <h2>Characters and Transsexuality</h2>
  <p>In the credits sequence of <em>MQS</em>, we can see actor José Luis López Vázquez’s face in the vintage pictures, as a baby, a girl, and a woman. The credits establish the femininity of the main character, which is necessary given that López Vázquez, as a successful actor, was already a well-known face for Spanish audiences. The movie did actually improve the actor’s reputation for his versatile acting and elegant way of treating the “issue” and got him recognition in Chicago (Comas, 1996; Galán, 2003). He embodies the character of Adela/Juan. Adela is a middle-aged, conservative rural lady who is integrated and respected in her small-town community. We see her interacting with different people in town, even kicking off the local football game. Her main problems are, on the one hand, her growing “lesbian” attraction to her maid, which leads to jealousy, and on the other hand the growing hair she has in her face and body–– she shaves in one of the first scenes, hidden in the toilet but as a habitual thing. She does not look concerned about her gender identity, but the feelings for Isabelita trouble her to the point of seeking first spiritual guide––confessing to the priest––and then medical advice following the priest’s guidance. It was precisely Adela’s homosexual desire that bothered censors at the time<sup>2</sup>, not the fact that she becomes a man in the movie. In fact, turning Adela into Juan was the way that homosexuality was kept out of the plot. Censors only asked for the removal of the last sentence in the movie––“You don’t have to tell me, <em>señorita</em>”––which implies that Isabelita knew who Juan was, thus validating the earlier lesbian attraction.</p>
  <p>After her transition, Adela becomes Juan, a middle-age man finding it difficult to fit in society due to his lack of manly expertise and talents. He has the experience of a middle-aged bourgeois rural woman, so he needs to find a job that suits his abilities, leading him to lie about a sick sister at home in order to get some sewing work. He never really identifies with the other gender––not once do we see Juan missing being a woman, nor Adela longing to become a man. There seems to be no big issue in transitioning––apart from some hardship in finding a job––and Juan has no problem in “passing” as a man. It is also worth noticing that this is the only story focused on a female-to-male transition in Spanish cinema, which speaks to the invisibility of trans men (Kellaway, 2014). However, we cannot be certain that this is a case of transsexuality, since the details of the medical intervention and Juan’s biological body are not revealed to us. This has led some authors to group <em>MQS</em> among movies about intersex people (Estrada López, 2012), which would explain the facial hair, the socialization as a woman and a new gender diagnosis as an adult. Nevertheless, the fact that there is indeed a medical “change of sex” that is not entirely explained, nor shown, allows us to reflect on the importance of the body and biology to validate a medical diagnosis, which we as the audience cannot fully make. This article, then, considers Adela/Juan within the “transgender” category, as in the presentation of the main character, <em>MQS</em> speaks more to the fragile binary separation of the sexes and the performativity of gender than it does to the fact of <em>being</em> a transsexual.</p>
  <p><em>CdS</em>, on the other hand, is completely focused on explaining to the audience what a diagnosis for transsexualism looks like. It should be noted that the movie itself is formally framed and introduced by two lines in the credits: first, it adds “the presentation of Bibi Andersen, a star of <em>Cadena Ferrer<sup>3</sup></em>,” which introduces the fact that there is a transsexual actress in the film playing herself as a cabaret artist; second, there is a warning that “the authors have based this film on a real story.” Scriptwriters Joaquim Jordà and Vicente Aranda (who also directed the film) said in an interview that they researched and talked with transsexual people before making the movie (Ripoll Freixes, 1977; Roca Sastre, 1977). It is not surprising, then, that having consulted the available literature on the topic, they reproduce Benjamin’s “true transsexual” (1966) almost point by point in the movie<sup>4</sup>. In doing so, they add in the interview, they wanted to present the topic in a serious and even educational manner, which is precisely what the critics of the time said about the movie (Hernández, 1976; O.M., 1977). This is made clear on screen through, for example, a sequence made up of graphics that depict the process of gender confirmation surgery, or the diverse symptoms and situations that translate from the APA diagnosis of transsexuality onto the screen.</p>
  <p>This “real story” is centered around José María, a young androgynous boy played by a young and unknown Victoria Abril, who is presented to us as male through his father calling him “son.” This certainty about the main character’s gender will not last long, because in that same scene, a client will call him “<em>nena<sup>5</sup></em>.” From the beginning, the spectator is made witness to the problems of José María as a boy: through the interactions with his father and classmates, we will learn that José María does not feel, indeed, like José María but rather like María José<sup>6</sup>. Unlike Adela/Juan, this time the character is presented as Harry Benjamin’s “true transsexual,” fitting perfectly the clinical definition of transsexuality (which is consistent with the original title of the movie, <em>A Clinical Record</em>). The three characteristics posited by Benjamin are present in the movie, and medically construct the character of María José. However, this understanding of transsexualism excluded (and continues to do so) gender variant or gender-queer people, since there needs to be an investment in the gender binary and heterosexuality in order to get the recognition.</p>
  <p>María José is born an effeminate boy who soon feels trapped in her male body, starts dressing privately as a woman with stolen clothes (the fascination with feminine underwear and clothes is present in three different sequences) and finally gets gender confirmation surgery. Her story of transitioning to a woman is paralleled in the movie by the other main transsexual character, Bibi Andersen. In Bibi’s presentation scene, she is prefaced by the introduction of her show: “A mystery of nature, the biological enigma of our century, suspense in the flesh.” This mysterious character will become a sort of godmother to María José after meeting her in a hair salon (still as José María), and will help her to understand transsexuality. Bibi also helps the audience read both her and María José as transsexuals, highlighting the pre- and post-surgery moments for both her––showing her penis at the beginning, telling María José how she went to Casablanca and had the surgery––and María José (who has an entire long scene dedicated to her transition). In opposition to the subtlety that dodged censorship in <em>MQS</em>, <em>CdS</em> and Bibi are explicit and visual about the transsexual body, biology, and participation of an essentialization of transsexuality. For example, in Bibi’s introduction (“biological enigma”), or after the show, when José María’s father comments on Bibi’s penis, asking, “Is that glued?” to which his stripper friend responds, “The tits are glued, those are <em>his</em> and <em>his parents</em>’” evoking again the role of biology.</p>
  <p>After watching Bibi’s show, which José María’s father intended to be educational for his performance of masculinity, José María steals his first feminine clothes and decides to go to Barcelona and present himself as María José for the first time, although only in the street and in an anonymous way––he will still be José María for his patrons, his landlady, and even Bibi. María José’s transition is shown through two main scenes: one that is more psychological and another one devoted to physical changes. The first one happens in the motel, when the landlady leaves and José María takes some women’s clothes, dresses herself, listens to a radio program aimed at housewives and starts watching a romantic movie––she will later repeat some of the lines to her first lover. It shows how María José is learning to act like a woman, performing femininity through feminine role models and indications. She is practicing what she tried for the first time in the street, and as we see in subsequent scenes, she quickly learns how to “pass” as a woman.</p>
  <p>The second transformation scene is radically different, in that it presents feminization as a physical process. It happens later in the movie when Durán (Lou Castel) takes care of María José and decides to “make her” a woman. Both he and Bibi speak to a still frame of her face, voices overlapping, telling her what to do, while the montage shows different jars with hormones, waxing, depilation, hydrotherapy, exfoliation of the skin, ear piercing, lipstick, facial masks, electrode treatments, etc. All is shown very hygienically and almost surgically. This time, the body needs changing after she has tried living, working, and socializing as a woman. This parallels the process established by psychiatry for transsexuals in Spain (and most of the Western world), in which the person wanting to have a change of sex acknowledged by the law needs to first get a diagnosis and go through “the real life test.” This test implies living as the desired gender for a period of time in order to make sure of the person’s will to live as such before the operation. This test has also been reported to be a very vulnerable stage for transsexual people, leading to transphobic discrimination and aggressions, since in most cases the body has not been modified, and “passing” as the other gender is very difficult (Markman, 2011). We see this happen with María José’s first boyfriend, who beats her when he discovers she still has male genitalia.</p>
  <p>Finally, it’s worth commenting on Bibi’s slightly different take on surgery from María José’s. Despite being the first of the two to undergo the procedure, Bibi is much more critical of surgery, and she declares at first that she doesn’t want to do it. Bibi Andersen, the actress, not the character, also declared in interviews of the period that she was waiting to be really sure about that step (Torres, 1977), arguing that it’s irreversible and lethally dangerous. For both the actress and the character, surgery is a very important decision that might lead to regret or death, and she comments as well on her lack of work after surgery, because she’s no longer “special.” In fact, the relationship between work and surgery has been noted in other Spanish movies featuring a transgender protagonist, like Antonia San Juan in Almodóvar’s <em>All About my Mother</em> (1999) or Rossy De Palma in 20 <em>Centimeters</em> (dir. Ramón Salazar, 2005). Especially in the field of porn and sex work, being a transgender person pre-surgery has recently gained its own space (the so-called “shemale”) and taken it away from post-surgery transgender people (Escoffier, 2011), making more difficult the decision of undergoing surgery, which is also very expensive.</p>
  <p>Overall, both characters are presented under a very different light and have a different relationship with their own sex and gender identities. Whereas Juan/Adela reflect more metaphorically on gender differences and the correlation (or lack thereof) between sex, gender <em>and</em> sexuality, María José is constructed following the medical discourse of the time, and used as a poster-child for Benjamin’s “<em>true transsexual</em>.” This signals the fact that Franco’s censorship allowed a non-explicit transgression of gender (which, as I explain, helps avoid homosexuality in the film), whereas the new discourse after the dictatorship would bestow the power to decide who was deemed appropriate for transition to the medical institution. With this in mind, we can see how the freedom to talk openly about transsexuality on screen did not <em>per se</em> bring a subversive and radical way of empowering transsexual people for what they are, but rather pathologized transsexual people as a means to “explain” the unbeknownst phenomenon to the public.</p>
</section>
<hr />
<section>
  <h2>Socialization and Institutions</h2>
  <p>Since Adela has no adaptation problems in her community, her transition is not an escape or the result of internal discomfort with her sex/gender correspondence, but rather in accordance with her homosexual desire. The first part of the movie shows Adela as an important member of the town where she lives (as opposed to the trope of the marginalized transsexual that so often populated films in the following years).</p>
  <p>There are two main characters with whom she maintains a relationship in the movie: She is courted by wealthy Santiago (Antonio Ferrandis), the town’s bank manager, a representative of the rural bourgeoisie that surrounds Adela. However, the true love story in the film is that between Adela and her maid, Isabelita (Julieta Serrano). Isabelita is seeing the young town florist, and he brings Isabelita and Adela carnations, and compares the two ladies to the flowers, which both of them like. Later on, we see Adela being less and less comfortable with having him around, throwing the carnation away when she sees Isabelita flirting with him. After the boy leaves, Isabelita notices Adela’s irritation, apologizes, and promises she “will never marry.” The audience can already see here that there is something going on between the two––which is precisely what bothered the censors about the film. After a big argument, Isabelita tells Adela she’s leaving the house. While Isabelita packs, we can see Adela’s lusty gaze observing Isabelita while she gets dressed to go, which will prompt the “dear lady” to go see her priest.</p>
  <p>Adela keeps pushing Santiago away, using her problems with facial hair as a justification for her fear, while she also complains about “never having been loved”–– to which Isabelita answers, “Men are idiots.” Although Santiago, a widower, doesn’t seem to care––and tells her that he has “always been attracted to her” and that “beauty is not everything” in response to her excuses––it is precisely Adela’s rejection of “heterosexual” love in the first part of the movie what protected the whole project from being censored. Indeed, her lesbian desire, turned into heterosexual love after the transition, was tolerated. But what if Adela, whom we later discover is a man, falls in love with another man? Could Juan be at risk of falling in love again with another man? Most probably––and considering that just a sentence from Isabelita acknowledging Juan’s past as a woman was enough to set off the alarms for the censors––the idea of having actor José Luis López Vázquez play the part of a protagonist having had homosexual desires would have been too much.</p>
  <p>In the second half of the movie, we encounter Juan’s difficulties in socializing with others: He has problems at the unemployment office for not being able to show his ID card; he needs to lie about a handicapped sister at home so he can get some sewing work; he needs to hide his past to the landladies at the <em>pensión</em>, who eventually discover Adela’s clothes in his suitcase and end up kicking him out. Problems in the job market and in housing do resonate heavily with the lives of many transgender people, and Juan’s socialization is cleverly used as well as a critique of gender discrimination and the difficulties women face in the job market. Precisely because of the lack of interest in the process of transition, <em>MQS</em>’s cultural work is done at the level of sex and gender, denouncing unfair inequalities with which many minorities can identify. However, <em>MQS</em> still has some conservative views about compulsory heterosexuality (Wittig, 1978) that aligns sex and gender with sexuality and pleased the censors.</p>
  <p><em>CdS</em> is again fairly different in the treatment of the protagonist’s human interactions. School is not a safe space for José María, who is bullied by his classmates and called “faggot” by the entire class in one of the opening sequences. Not only this, but he finally gets expelled by the principal, who wants to “prevent putting his classmates at risk of perversion.” When the principal implies to José María’s mother that the boy might be queer (by comparing him to the rest of the classmates, who are “normal”), she corrects him and defends her son: “How dare you call him abnormal?!... He’s docile and delicate.” The principal agrees. The problem, then, is not José María’s sexuality (which has not been shown or explained to the spectator) but that he is too “tame and delicate”... for a boy. When José María tells his sister, the only member of the family who looks actually concerned <em>for</em> him (not because of him), she tells him not to worry, because “it’s not his fault.” He responds, “Don’t you want to understand? Even if it’s not my fault, I’m their amusement. If I try to talk like them, it’s worse, because they think I’m imitating them. I want to die.” This is the first time––but not the last––that he expresses his desire to die. However, what’s revealing here is how the story puts the blame of José María’s suffering on what others do to him, not on him. This highlights transphobia, not transsexuality, as the cause for suffering, something that is taken into account in the last revision of the DSM (American Psychiatric Association, 2013b).</p>
  <p>The sister will also be the first to see José María as María José, who decides to present herself as a woman and have a sisterly night out. The sister likes her much more as a woman, and thinks she’s more confident like that. However, sexuality is also one of the difficult parts of the process for María José’s sister to understand:</p>
  <ul>
    <li>What do you feel when you dance with a man?</li>
    <li>Same as you do.</li>
    <li>But that can’t be! I am a woman!</li>
    <li>I, too, feel like a woman.</li>
    <li>But you are not.</li>
    <li>Then what am I? (Sister starts sobbing).</li>
  </ul>
  <p>Still in the process of finding her own identity, María José lacks an answer to her sister’s question. She fulfills Benjamin’s three axes: hatred for her genitalia is repeatedly shown and mentioned every time showing genitalia on stage is part of a conversation, and she will try to cut her penis off herself half way through the movie; she also expresses in many occasions that she “feels like a woman,” and shows no desire for other women. Presented as an embodiment of a true transsexual, José María has many socialization problems as a boy, whereas María José passes perfectly as a woman and feels even more confident. The narrative of <em>CdS</em>, in contrast to <em>MQS</em>, is that of self-discovery in order to improve the initial situation, and in the words of the protagonist, become “normal” again. Bullied at school, battered by her father for not being manly enough, and expelled from school by a moralist principal, María José faces as many problems and direct consequences of discrimination as José María, but only one instance of violence as Maria José––when the first boyfriend beats her upon finding out she’s not a “real woman.” Being a woman, rather than preventing her from achieving goals, is the goal itself, and comes with the advantage that she feels more at home in femininity.</p>
  <p>As noted before, her relationship with Bibi is central to the story, and Bibi will become her transsexual mentor, one step ahead of her during the entire process. She is the one who visits at the hospital when José María tries to cut his penis off, the one that will get María José a job, and the one who will introduce her to her future husband. However, there is a mounting competition between the two (other workers in the cabaret compare them constantly), increased by Bibi’s lack of work after surgery, which will end their friendship when Bibi finds out that María José and their boss are romantically involved. Although the movie does not give importance to Bibi after they fall out, removing the character from the plot, she remains a central character for María José’s transition. There is another ally in the movie for María José, the landlady played by Rafaela Aparicio. If we compare the relationship they have with that of Juan and the owners of the <em>pensión</em> where he stays, the benign relationship that is established between the the landlady and María José, similar to that of a godmother and godchild of sorts, is reinforced by the fact that she is one of the first to know that José María is now living as María José, and seems completely supportive of the situation.</p>
  <p>We have briefly mentioned María José’s relationship with her first boyfriend, who beats her for having male genitalia. The other love interest, her boss Durán, will see her as an employee first, then start flirting, at some point abandoning her and calling her “nothing more than a transvestite,” and finally taking care of her and paying for the surgery in order for the two to get married. As we can see, María José’s relationship with men is problematic: On the one hand, she is punished by men for not having “completed” the transition, while on the other hand, it is a man who will secure a job for her, as well as sustainment and the money to surgically change her body. This dependence on surgery to be accepted, and dependence on men to physically become who she is, also references the difficulties of being independent as a woman and adds the cost of surgery as another burden for transsexuals. If we add to this hardship the difficulty of finding a job that is not highly feminized as José María (who starts working as a hairdresser) or linked to show business (making profit out of their weirdness rather than their talent), we can read in the movie a desolating landscape for the realities of transgender people.</p>
  <p>Hardships at work seem to be a commonality between the two movies, but the relationship of each protagonist with the institutions of our society is fairly different. In <em>MQS</em>, Adela is connected with the most important institutions in Franco’s Spain. She is an active member of the local church (the bells toll for a funeral in the opening scene; she confesses to the priest, looking to stop her lesbian desires) and the economic establishment (the bank manager is courting her). She even participates in the public leisure sphere, and she is invited to start the local soccer game as an integrated and respected member of the community (we cannot forget how powerful soccer is as an institution in Spain, as well as the importance it had for the regime)<sup>7</sup>. However, medicine has a shockingly minor role. The presence of medicine is anecdotic and appears only as working in consonance with the church to regulate citizens’ sex and gender. It is the doctor who tells Adela that she is actually Juan, and it is through the doctor that the movie establishes a bifurcated division of body and mind that together conform identity, much as Harry Benjamin did in his book. As the doctor says: “One cannot have a sick mind without the body being sick, too. It is not a dependence or interrelation, is about a total and complete identity.”</p>
  <p>Far from the mostly positive rapport between Adela/Juan and the institutions, <em>CdS</em> highlights instead the problems with all the institutions that the transsexual character encounters. School and education seem to be part of the problem rather than the solution. Family is a source of support (sister), a source of violence (father), and resignation to suffering (mother). After José María’s expulsion from school, his father goes as far as to say that he is dishonoring the family: “I will fix you, or nobody will. And if I don’t fix you, I will kill you.” He will try to mend his “broken son” by making him work hard with his body (cutting wood, in construction, etc.). He will, as well, show him how to socialize properly as a man, taking him to see a prostitute, talking about manly things like getting girls pregnant, and giving him money so he can tip people and feel in charge, all components of a very traditional view of masculinity.</p>
  <p>By far the institution most present in <em>CdS</em> is medicine. From the its original title to the sequence––done in the style of a public service announcement––about gender confirmation surgery, the film is educational in its treatment of transsexuality, but always within the medical paradigm. The questions the doctor asks before surgery are well researched and similar to the ones asked in real-life situations. The transformation of José María into María José is not possible without the intervention of science, and the doctor is represented as an absolute gatekeeper of the process. Overall, we can see two very different socializations: one in which the problems and frictions come from living in a “new” gender in which we are not trained to perform, and another one in which the problem is the correlation between sex and gender.</p>
  <p>Another looming institution in both movies, one that problematizes the ways in which transsexuality is presented, is that of marriage and heterosexual love. In both movies, transsexuality is presented almost as a solution for homosexuality, not unlike the case of Iran<sup>8</sup>, where prohibition of homosexuality is avoided by the state through the financing of half of the cost of sex reassignment surgeries for those who want it (and always from man to woman). In <em>MQS</em>, the change of sex and gender of the protagonist satisfied the censors as a solution to the lesbianism present at the beginning of the movie, and the sole mention of gender ambiguity in Isabelita’s final sentence was removed. <em>CdS</em> is no different in that regard, as marriage is the “happy ending” that the protagonist receives for becoming a woman through surgery. By portraying marriage and heterosexual love as the centerpiece of both endings, the movies reinforce the idea that surgery (and sex transition) is a means of reinserting the person into society, normalizing their bodies. Through the medical institution, the possible transgression of sex and gender becomes re-absorbed by the gender binary, which remains intact and even reinforced by the power of medicine and science.</p>
</section>
<hr />
<section>
  <h2>Conclusions</h2>
  <p>After analyzing both movies, we can see how the possibility of explicitly addressing transsexuality on screen brings forth a medical paradigm to understand the phenomenon that is based on Harry Benjamin’s work, substituting a more metaphorical approach to the topic–– one forced by the censorship. This new pathological framework becomes a  new way of explaining transsexuality in Spanish cinema that will coexist with other criminalizing discourse during decades, and is still reproduced in more mainstream movies like 20 <em>Centimeters</em> (dir. Ramón Salazar, 2005), and especially in documentary films like <em>El Sexo Sentido</em> (dir. Manuel Armán, 2014).</p>
  <p>The analysis shows a palpable difference between the way the two movies present the issue of transsexuality, both at the level of the character and of their socialization with others and with institutions. Whereas <em>MQS</em> is very ambiguous in the depiction of Adela/Juan and does not specify that the character is transsexual, <em>CdS</em> reproduces very thoroughly the features of Harry Benjamin’s “true transsexual.” However, both movies offer an account of gender transitioning through their main characters and highlight the instability and mutability of the supposedly fixed and monolithic gender binary, while at the same time reinforcing such categories. Not unlike Foucault’s claim that homosexuals became a “species” (1986) when medicine created the term to define same-sex desire, what we witness in <em>CdS</em> is the apparition through explicitness of the transsexual as a medical subjectivity.</p>
  <p><em>MQS</em> uses a more metaphorical approach to gender difference, underscoring the differences of living as a man or a woman and the difficulties and inequalities that it entails. On <em>CdS</em>, however, we see a more explicit representation of a medical discourse that is focused in the difficulties of living as a woman for a biological male or, in short, the transsexual experience, but it fails to subvert the binary that medicine inhabits, reinforcing through diagnosis the gender binary and its stereotypes. Furthermore, it seems that <em>MQS</em>’s plot is constructed around Juan and Isabelita’s love story––which also transitions from a forbidden lesbian love to an accepted heterosexual couple. Instead of focusing on transsexuality (which got <em>CdS</em> banned by the censors), <em>MQS</em> solves the great problem for Franco’s censorship––lesbianism––through Juan’s transition.</p>
  <p>The intent of each movie is also debatably different, opposing the critique to gender inequalities of <em>MQS</em> and the pedagogical intention of <em>CdS</em>, highlighted by both the scriptwriters and the critics. While the former presents the different institutions (church, bourgeoisie, sports, etc.) as supporting and encouraging Adela in the beginning, and accepting Juan in the end, <em>CdS</em> is more interested in making the difficulties of transsexual people known. José María/María José has problems with her family, school, love interests and the workplace, and it is not until she completes her transition that she is able to leave all that behind. María José will find peace in the world of entertainment and, avoiding established institutions and meeting other transsexuals, she will finally assert her feminine identity and will become “normal” again, deserving of love and a wedding in white.</p>
  <p>The role of medicine is important for both, but while in <em>MQS</em> the presence of medicine is almost anecdotal––and humoristic––<em>CdS</em> is deeply invested in portraying medicine (psychology and surgery above all) as the enabler for a legitimation of María José’s identity and transsexuality. Even so, both movies are doing cultural work in their approach to the topic, which is in itself unprecedented in Spanish cinema. Both question the logic behind an impossible-to-trespass border between the two sides of the gender binary (although they don’t question the binary itself), and both give voice to a very small minority that was, at the time, forming its own identity through diverse discourses. For their rare treatment of the topic, as well as for their elegant depiction (one that does not fall onto blaming/criminalizing the characters, or making fun of them for their situation) these movies are a perfect site of interrogation of the limits of sex, gender, and sexuality, and the ways of understanding any deviance, or lack thereof, from their heteronormative alignment (male/masculine/heterosexual and female/feminine/heterosexual).</p>
  <p>I want to dedicate also some words to more recent critiques to the medical paradigm on transsexuality (American Psychiatric Association, 2013a)<sup>9</sup> and the implications that being a transsexual––wishing for gender confirmation and experience transsexuality in Benjamin’s terms––has regarding gender normativity. First, it needs to be acknowledged that the medical classification of transsexuality opened the door for science and the law to recognize and set the parameters to legitimize gender non-conforming people. These parameters are not immutable, and there exists an international movement against trans pathologization––asking to remove transsexuality from the DSM––that has pushed for change in many countries and is trying to redefine what being transgender means. There have also been revisions of the the legal system in many countries that have gone from not including the surgery as a requirement (as in the United Kingdom in 2005 or Spain in 2007), and even ignoring the psychiatric diagnosis requirement (Argentina in 2012, Denmark and Malta in 2014, and Ireland in 2015). Despite these changes, the medical discursive formation of transsexuality has been instrumental in granting health coverage to transsexual people, protecting them legally, recognizing their transitions and even allowing them to coalesce around the transsexual identity for improving the rights of the community.</p>
  <p>Finally, I want to address the critiques that attack transsexuals for their reinforcement of gender stereotypes, because of their simplification of the complicated structures at play. If the one discourse on transsexuality (“man/woman trapped in the wrong body”) is so pervasive, the legal and medical frameworks that force and privilege this unique narrative are, at least partly, to blame. Recent research on the topic shows how some trans people have used the narrative as “strategic essentialism” to be able to access the necessary treatment to live up to their gender identity (Missé &amp; Coll-Planas, 2010). In the same book, the authors overview as well the different strategies used by activists in Spain to resist the normative understanding of transsexuality and the struggle for transgender de-pathologization. Ignoring those acts of resistance, which also come from within the transgender community, and the social pressure to conform to the “true transsexual” narrative is, indeed, reductive of the myriad different ways of living a transgender identity. With all the different ways of <em>being</em> transgender (one of which is medical transsexuality) and of transitioning between genders, one can only hope that Spanish cinema will continue fulfilling its task as facilitator in these social negotiations of what is acceptable or not. Hopefully in the future we will be able to see other new (and coexisting) discourses on the issue emerge in the public arena of the media, so the social understanding of deviation from the sexual norm becomes more inclusive, tolerant and open to changes––which history tells us, is unavoidable.</p>
</section>
<hr />
<section>
  <h2>References</h2>
  <p class="references">Althusser, L. (1971). Ideology and Ideological State Apparatuses. <em>Lenin and Philosophy, and Other Essays</em> (pp. 127-88). Trans. Ben Brewster.  London: New Left Books.</p>
  <p class="references">American Psychiatric Association. (2013a). <em>Gender Dysphoria</em>. Retrieved June 8th 2016 from <a href="http://www.dsm5.org/documents/gender%20dysphoria%20fact%20sheet.pdf">http://www.dsm5.org/documents/gender%20dysphoria%20fact%20sheet.pdf</a>]</p>
  <p class="references">American Psychiatric Association. (2013b). <em>Diagnostic and statistical manual of mental disorders</em> (5th ed.). Arlington, VA: American Psychiatric Publishing.</p>
  <p class="references">Becerra-Fernández, A. (2003). <em>Transexualidad. La búsqueda de una identidad</em>. Madrid: Díaz de Santos.</p>
  <p class="references">Benjamin, H. (1966). <em>The Transsexual Phenomenon</em>. New York: Julian Press.</p>
  <p class="references">Bradford, V. (2008). Iran’s “diagnosed transsexuals.” Retrieved March 2016 from <a href="http://news.bbc.co.uk/2/hi/7259057.stm">http://news.bbc.co.uk/2/hi/7259057.stm</a></p>
  <p class="references">Bustos Moreno, Y.B. (2008). <em>La Transexualidad (de acuerdo a la Ley 3/2007, de 15 de marzo)</em>. Madrid: Dykinson.</p>
  <p class="references">Cabrerizo Pérez, F. (2007). <em>La Atenas militarizada: La industria cinematográfica en Gipuzkoa durante la Guerra Civil (1936-1939)</em>. San Sebastián: Diputación Foral de Gipuzkoa.</p>
  <p class="references">Comas, A. (1996, May 27). Mi Querida Señorita. <em>La Vanguardia</em>.</p>
  <p class="references">Córdoba, D., Sáez, J. &amp; Vidarte, P. (Eds.). (2005). <em>Teoría queer. Políticas bolleras, maricas, trans, mestizas</em>. Barcelona: Egales.</p>
  <p class="references">Edwards, G. (2001). <em>Almodóvar: Labyrinths of Passion</em>. London: Chester Springs.</p>
  <p class="references">Epps, B., &amp; Kakoudaki, D. (Eds.). (2009). <em>All about Almodóvar: A passion for cinema</em>. Minneapolis: University of Minnesota Press.</p>
  <p class="references">Escoffier, J. (2011). Imagining the she/male: Pornography and the transsexualization of the heterosexual male. <em>Studies in Gender and Sexuality</em>, 12(4), 268-281.</p>
  <p class="references">Estrada López, L. (2012). <em>Indeterminacy and gender-sexual dichotomy in Hispanic cultural productions from the early twentieth century to the present</em>. (Doctoral dissertation). University of Connecticut. Retrieved June 8, 2016, from <a href="http://pqdtopen.proquest.com/#viewpdf?dispub=3520440">http://pqdtopen.proquest.com/#viewpdf?dispub=3520440</a></p>
  <p class="references">Foucault, M. (1965). <em>Madness and Civilization: A history of insanity in the age of reason</em> (R. Howard, Trans.). New York: Pantheon. (Originally published in 1961 as <em>Folie et déraison. Histoire de la folie à l’age classique</em>.)</p>
  <p class="references">Foucault, M. (1971). <em>L’Ordre du Discours</em>. Paris: Gallimard.</p>
  <p class="references">Foucault, M. (1973). <em>The Birth of the Clinic: An archaeology of medical perception</em> (A.M. Sheridan Smith, Trans.). New York: Vintage. (Originally published in 1963 as <em>Naissance de la clinique. Une archéologie du regard médicinal</em>, 1963).</p>
  <p class="references">Foucault, M. (1986). <em>The History of Sexuality. Vol.1. An introduction</em> (R. Hurley, Trans.). New York: Pantheon. (Originally published in 1976 as <em>Histoire de la sexualité. La volonté de savoir</em>).</p>
  <p class="references">Foucault, M. (1991). <em>Discipline and Punish: The birth of the prison</em> (A.Sheridan, Trans.). London: Penguin. (Originally published in 1975 as <em>Surveillir et Punir: naissance de la prison</em>).</p>
  <p class="references">Franklin, M. (2011). <em>Spectacles in Transit: Reading cinematic productions of biopower and transgender embodiment</em>. (Doctoral dissertation). Retrieved on June 8, 2016from The Data Repository for University of Minnesota [online] <a href="https://conservancy.umn.edu/handle/11299/101833">https://conservancy.umn.edu/handle/11299/101833</a></p>
  <p class="references">Galán, D. (2003, April 4). Solterona en aquella España. <em>El País</em>.</p>
  <p class="references">Garlinger, P. P. (2003). Transgender nation: Bibi Andersen, postmodernity, and the Spanish transition to democracy. <em>Revista de Estudios Hispánicos</em>. 37(1), 3-30.</p>
  <p class="references">Gil, A. (2009). <em>La Censura cinematográfica en España</em>. Barcelona: Ediciones B.</p>
  <p class="references">Gradillas, V. (2003). Based on the first legal sex change in Spain. <em>Actas Españolas de Psiquiatría</em>, 2003; 31(2), 95-99.</p>
  <p class="references">Gross, L. (2001). <em>Up from Invisibility: Lesbians, gay men, and the media in America</em>. New York: Columbia University Press.</p>
  <p class="references">Hall, S. (1993). Deviance, politics and the media. In H. Abelove, M. A. Barale &amp; D. M. Halperin (Eds.), <em>The Lesbian and Gay Studies Reader</em> (pp. 62-90). New York: Routledge.</p>
  <p class="references">Hernaiz, G. (2007). <em>El tercer sexo</em>. Barcelona: Ediciones B.</p>
  <p class="references">Hernández, I. (1976, July 7). Vicente Aranda Rueda “Cambio de Sexo.” <em>Dossier Filmoteca de Catalunya</em>.</p>
  <p class="references">Higginbotham, V. (1988). <em>Spanish Film under Franco</em>. Austin: University of Texas Press.</p>
  <p class="references">Hirschfeld, M. (1910). <em>The Transvestites: The erotic drive to cross-dress</em> (Trans. 1991). New York: Prometheus Books.</p>
  <p class="references">Kellaway, M. (2014). Op-Ed: When trans men’s visibility comes at the cost of self-esteem. <em>Advocate</em>. (online) Retrieved from: <a href="http://www.advocate.com/commentary/2014/12/02/op-ed-when-trans-mens-visibility-comes-cost-self-esteem">http://www.advocate.com/commentary/2014/12/02/op-ed-when-trans-mens-visibility-comes-cost-self-esteem</a></p>
  <p class="references">López-Galiacho Perona, J. (1998). <em>La Problemática jurídica de la transexualidad</em>. Madrid: McGraw Hill.</p>
  <p class="references">Markman, E. R. (2011). Gender identity disorder, the gender binary, and transgender oppression: Implications for ethical social work. <em>Smith College Studies in Social Work</em>,  81(4), 314-317.</p>
  <p class="references">Marsh, S., &amp; Nair, P. (Eds.). (2004). <em>Gender and Spanish cinema</em>. Oxford: Berg.</p>
  <p class="references">Mehrotra, A. (2014). Fascism &amp; football: The political history of Spanish football. Retrieved March, 2016, from: <a href="http://outsideoftheboot.com/2014/05/22/fascism-football-the-political-history-of-spanish-football/">http://outsideoftheboot.com/2014/05/22/fascism-football-the-political-history-of-spanish-football/</a></p>
  <p class="references">Mejía, N. (2006). <em>Transgenerismos. Una experiencia transexual desde la perspectiva antropológica</em>. Barcelona: Bellaterra.</p>
  <p class="references">Mira, A. (2008). <em>Miradas insumisas</em>. Madrid: Egales.</p>
  <p class="references">Missé, M. &amp; Coll-Planas, G. (2010). <em>El Género desordenado: Críticas en torno a la patologización de la transexualidad</em>. Barcelona: Egales.</p>
  <p class="references">Nieto, J.A. (1998)<em>Transexualidad transgenerismo y cultura</em>. Madrid: Talasa.</p>
  <p class="references">Nieto, J.A. (Ed.). (2003). <em>Antropología de la sexualidad y diversidad cultural</em>. Madrid: Talasa.</p>
  <p class="references">Nieto, J.A. (2008). <em>Transexualidad, intersexualidad y dualidad de género</em>. Barcelona: Edicions Bellaterra.</p>
  <p class="references">O.M. (1977, June 23). Cambio de Sexo. <em>TeleXpres</em>.</p>
  <p class="references">Palacio Arranz, M. (2002). Francisco Franco y la televisión. <em>Archivos de la Filmoteca: Revista de estudios históricos sobre la imagen</em>, 42-43(2), 72-95.</p>
  <p class="references">Pastor, B. M. (2006). Screening sexual and gendered otherness in Almodóvar’s <em>Law of Desire</em> (1987):  The real “sexual revolution.” <em>Studies in European Cinema</em>, 3(1), 7-23.</p>
  <p class="references">Perriam, C. (2013). <em>Spanish queer cinema</em>. Edinburgh: Edinburgh University Press.</p>
  <p class="references">Poyato Sánchez, P. (2014). <em>El cine de Almodóvar. Una poética de lo “trans.”</em> Sevilla: Zemos98.</p>
  <p class="references">Preciado, B. (2002). <em>Manifiesto contrasexual</em>. Barcelona: Anagrama.</p>
  <p class="references">Preciado, B. (2008). <em>Testo Yonqui</em>. Madrid: Espasa.</p>
  <p class="references">Richmond Ellis, R. (1997). <em>The Hispanic Homograph: Gay self-representation in contemporary Spanish autobiography</em>. Urbana: University of Illinois Press.</p>
  <p class="references">Ripoll Freixes, E. (1977, August 7). Un tema que deixa d’ésser tabú. <em>Avui</em>.</p>
  <p class="references">Roca Sastre, E. (1977, June 24). Cambio de Sexo. <em>Mundo Diario</em>.</p>
  <p class="references">Smith, P. J. (1994). <em>Desire Unlimited: The cinema of Pedro Almodóvar</em>. London: Verso.</p>
  <p class="references">Soley-Beltran, P. (2009). <em>Transexualidad y la matriz heterosexual</em>. Barcelona: Bellaterra.</p>
  <p class="references">Torres, M. (1977, February 2). El Transexual de la Reforma. <em>TeleXpres</em>.</p>
  <p class="references">Wittig, M. (1978). <em>The Straight Mind and Other Essays</em>. London: Harvester.</p>
</section>
<hr />
<section>
  <h2>Notes</h2>
    <p><sup>1</sup> The title means “a medical record” but it plays on the word “historia,” which can be used as “record” or ‘story’ in this context.</p>
    <p><sup>2</sup> In the censorship document of MQS, preserved in the National Archives in Alcalá de Henares, “lesbianism” is the main concern for all the agents involved in the “censorship dossier” of the movie. Once the last sentence (in which Isabelita acknowledges that she knew Juan was Adela) was removed, censors granted the permission for the movie to be released.</p>
    <p><sup>3</sup> Cadena Ferrer was an enterprise of cabaret and night entertainment famous at the time for bringing long-forbidden erotic shows to Spanish stages.</p>
    <p><sup>4</sup> In his book The Transsexual Phenomenon (1966), Benjamin separates the definitions of the terms “transvestite” and “transsexual,” so as to be able to address each differently. In the case of Benjamin’s “true transsexual” (which only contemplates female transsexuals), the gender feeling is that of being trapped in the wrong body (total psycho-sexual inversion); they may live as the gender they identify with, but dressing is not enough, they desire intensely relationships with “normal males”; and the medical indications for them is hormone treatment and surgery, all of which are present in the movie.</p>
    <p><sup>5</sup> The equivalent of baby, but in an unequivocal feminine gender.</p>
    <p><sup>6</sup> Note: The inversion of two of the most popular names in Spain denotes the difference in gender of the person named.</p>
    <p><sup>7</sup> “Franco had seen the positive effects of football through the exploitation of the sport by Mussolini and Hitler, and saw it as a perfect way for Spain to regain some positive global attention and also help him consolidate his rule at home. He also wanted to use it as something which could divert people’s attention from his regime” (Mehrotra, 2014).</p>
    <p><sup>8</sup> See “Iran’s ‘diagnosed transsexuals’” (Bradford, 2008).</p>
    <p><sup>9</sup> In the last revision of the DSM, the previous diagnosis on “gender identity disorder” has been changed to “gender dysforia,” which “is the presence of clinically significant distress associated with the condition.” This was done to reduce the stigma attached to mental “disorders” while shifting the focus of the diagnosis from the features of the patient to the suffering this condition causes, if any. De-pathologization movements have criticized this step as insufficient. The debate is ongoing due to the limits to the access to healthcare and surgery if there is no medical condition to back the patient up.</p>
</section>
