<p class="volume">
  Volume 8 | September 2015
</p>
<h6><a href="http://www.internationalhispanicmedia.org/wp-content/uploads/2016/11/IJHM_Vol9-Transsexuality.pdf">[ Download PDF ]</a></h6>
<section class="authors">
  <h4>Authors</h4>
  <p>
    <strong>Bruno Takahashi, Ph.D.</strong><br />
    Michigan State University, USA<br />
    Email: <a href="mailto:btakahas@msu.edu">btakahas@msu.edu</a>
  </p>
  <p>
    <strong>Juliet Pinto, Ph.D.</strong><br />
    Florida International University, USA<br />
    Email: <a href="mailto:gillj@fiu.edu">gillj@fiu.edu</a>
  </p>
  <p>
    <strong>Mercedes Vigón, Ph.D.</strong><br />
    Florida International University, USA<br />
    Email: <a href="mailto:vigonm@fiu.edu">vigonm@fiu.edu</a>
  </p>
  <p>
    <strong>Manuel Chavez, Ph.D.</strong><br />
    Michigan State University, USA<br />
    Email: <a href="mailto:chavezm1@msu.edu">chavezm1@msu.edu</a>
  </p>
</section>
<hr />
<section>
  <h2>Abstract</h2>
  <p>Scholars of science and environmental communication have frequently studied the content of environmental affairs coverage in the mass media. However, little still is known about the approaches used by newsrooms in Spanish-language media in the United States. This study shows the nature and content of environmental news and the models used by decision makers in Spanish-language newsrooms regarding content and editorial decisions. This study is based on a content analysis of environmental news in Spanish-language media, and on data collected through interviews with senior newsroom staff and reporters who have experience in covering environmental affairs at major U.S. Spanish-language television stations. The findings demonstrate the impact of revenue-streams needs, the perception that environmental news is not important, and the perception that environmental coverage lacks immediacy and impact. These findings reflect other research examining the output of U.S. English-language journalism and of other ethnic media, and provide impetus for future research.</p>
  <p>
    <strong>Keywords:</strong> Environmental communication, Spanish-language television, ethnic media, news coverage, editorial decision making
  </p>
</section>
<hr />
<section>
  <h2>Introduction</h2>
  <p id="note-line-2">Scholars of science and environmental communication have frequently studied the content of the coverage of environmental issues (with a recent focus on climate change) in global mass media. However, less is known of how and why decisions are made in newsrooms regarding coverage of those issues (Smith, 2005). Much less still is known about the editorial approaches and decision-making processes used by newsrooms in Spanish-language media in the United States, something with important implications for public understanding of relevant issues for major sectors of the U.S. population. The U.S. Census Bureau estimates that the Latino/Hispanic1 population in the United States accounts for more than 50 million people, which represents 16% of the total population and a growth of 43% from the 2000 Census (Ennis et al., 2011). In a study commissioned by the Sierra Club and the National Council of La Raza in 2012, Hispanic voters were also observed to strongly support clean energy and conservation measures, and to believe that climate change is already happening.<sup><a href="#note-2">[2]</a></sup> However, little research has examined U.S. Spanish-language news coverage of environmental issues, with one finding scant attention to the topic of climate change in the U.S. Hispanic press (Villar &amp; Pinto, 2013), something that has import for public awareness and policy direction.</p>
  <p>Therefore, this study seeks a deeper understanding of how and why environmental issues such as climate change are perceived within U.S. Spanish-language newsrooms, and how those perceptions affect coverage for Spanish-speaking populations. We investigate the editorial models applied, given contextual nuances such as the global recession and internal dynamics of newsrooms, along with the fast-growing Spanish-language media in the U.S., and how forces associated with restructuring, innovation, and cultural and value systems affect coverage, or the lack of it. We ask how the leaders in Spanish-language news see their roles in communicating environmental issues to their publics, therefore illuminating variables that help our understanding of the interfaces with science and environmental issues, public opinion, news values, and cultural contexts.</p>
  <p>This study is based on data collected in 2013 through semi-structured, in-depth interviews with senior personnel (news directors, executive producers, and editors), and reporters who have considerable experience at major Spanish-language news media at regional and national levels in the United States, including South Florida, a major hub for Spanish-language media. We also conducted a content analysis of environmental news in major Spanish-language news outlets. Findings are discussed in terms of implications for policy, public and news agendas, and will constitute a base for future scholarly and industry research on this issue. We contextualize our research questions and analysis by borrowing from the perspectives of the <em>hierarchy of influences</em> model (Reese, 2001; Shoemaker &amp; Reese, 1996), as well as the <em>acculturation</em> functions of Spanish-language mass media (Subervi-Vélez, 2008).</p>
</section>
<section>
  <h2>Literature Review</h2>
  <h3>U.S. Spanish-Language News Coverage</h3>
  <p>Research focusing on the coverage of environmental issues in ethnic media in the U.S. is scarce. With such paucity of research examining environmental coverage in Spanish-language media, we turn to examinations of other issues of import for U.S. Spanish-speaking populations. This research can provide preliminary explanations to the limited coverage of issues that are not considered as priorities for news decision makers or the audiences, something we discuss in more detail in the next sections.</p>
  <p>Research in this area has examined the content, with many studies focusing on issues of import to Hispanic audiences, such as labor, voting, political empowerment, health care or immigration (Abrajano &amp; Singh, 2009; Lozano, 1989; Subervi-Vélez, 2008; Thorson, 2006; Vargas, 2000; Vargas and De Pyssler, 1999; Veciana-Suárez, 1990; Vigón, 2010; Villar &amp; Bueno, 2013). The content reported in these studies can be explained from the perspective of a functionalist role of the media. Subervi-Vélez (1986) first proposed to analyze empirically the double functions of assimilation and pluralism served by the Latino media. These refer to the media as a means to assimilate into the dominant culture, and to provide the amplitude of perspectives that serve the heterogeneous cultural group. Subervi-Vélez (2008) has referred to the concept of acculturation, where specific traits of the dominant culture are learned and adapted to the individual’s or group’s culture, as a better concept to explain the roles of the media within Latino audiences. Others have found nuanced differences among ethnic- and general-market media, as well as within their audiences (e.g. Guzmán, 2006; Kerevel, 2011; Subervi-Vélez, 1986, 1999; Soruco, 1996; Ríos &amp; Gaines, 1998). In a recent study, Kerevel (2011, p. 509) argued: “The effect of using Spanish-language media serves to promote a sense of group consciousness among Latinos by reinforcing roots in Latin America and the commonalities among Latinos of varying national origin.”</p>
  <p>Some other studies in the area have also compared the reporting of Spanish-language media and English-language media to determine similarities and differences. For example, Hale, Olsen, and Fowler (2009) reported that Spanish-language media devoted less time to coverage of the 2004 presidential election than English-language media, and that the former focused more on horse-race than on issues. Similarly, Branton and Dunaway (2008) compared the coverage of immigration reform between English- and Spanish-language newspapers from an economic theory perspective. They argued that consumer preferences influence the volume and type of coverage. Spanish-language newspapers provide more volume, while English-language newspapers use a negative framing more frequently. Finally, a comparative study between ethnic media (<em>El Nuevo Herald</em>) and mainstream media (<em>The Miami Herald</em>) about coverage of immigration showed that <em>El Nuevo Herald</em> attempted to include diverse voices and took a more dialogue-based approach, while <em>The Miami Herald</em> was more conservative and critical (Guzmán, 2006). Fowler, Hale, and Olsen (2009, p. 248) summarized this trend:</p>
  <blockquote>
    <p>To a certain extent, our findings are encouraging in that local news stations do alter their content according to changing demographic trends (whatever the causal mechanism may be, a number of which are outlined above). Stations in competitive, diverse markets are open to airing content that reflects the market’s demographics.</p>
  </blockquote>
  <p>However, there is also evidence that Latino media are starting to resemble more and more the corporate model of mainstream English-language media. For example, Moran (2006) found this to be the case in a comparison of a Univision affiliate and an ABC affiliate in San Diego County, California. The content analysis revealed some differences in regards to frequency of coverage across topics, and also in the focus on Latino issues. However, the author argued that the similarities in terms of news values are due to journalistic training and a market-driven approach. Similarly, a recent study comparing the coverage of Latino collective action between Latino newspapers and elite U.S. newspapers found no significant differences (Okamoto, Ebert, &amp; Violet, 2011). The researchers suggested that U.S. media are broadening their scope in part due to demographic changes in the country. The study reported that Latino media tend to focus on issues about immigration, politics, and health, and that they tend to portray Latinos in a good way and to cater favorably to local news.  Those results are consistent with those reported by Vargas and De Pyssler (1999), who reported that health stories dominated the coverage in 17 Latino newspapers (both weeklies and dailies) during a six-month period, followed by crime, immigration, and education stories. Conversely, the coverage in TV is dominated by crime-related stories, while health stories were not as prominent.” (Subervi-Vélez, 1999). In contrast, Piñón and Rojas (2011) discussed the creation of new cultural hybrids of <em>Latinidad</em> that include the creation of a pan-Latino identity to be exported from Miami to Latin America and other world markets by U.S. mainstream English-language media.</p>
  <p>Finally, while much research has examined environmental news in U.S. and U.K. English-language media (Anderson, 2009) and despite the increase in efforts to study the coverage of various issues in U.S. Spanish-language media, there are no studies attempting to explain the way the issues are covered. Given that language is the defining variable for Spanish-language news in the U.S., we use a cultural and ideological lens from within the newsroom to understand the process of reporting environmental news.</p>

  <h3>Cultural Processes, Environmental Ideologies, and News</h3>
  <p>Cultural variables, ideological foundations, and news values impact how environmental or scientific issues are reported by the media and understood by audiences. Certainly, relevance, impact, novelty, and controversy are important determinants for what makes the news, and this applies to environmental issues as much as to any other thematic area (Friedman, Dunwoody, &amp; Rogers, 1986; Hansen, 1994; Lester, 2010). As Guzmán (2006, p. 282) noted:</p>
  <blockquote>
    <p>The circulation of cultural meaning through the news media contributes to the social construction of knowledge and performs a central ideological function in the reproduction of social and political inequality . . . . Consequently, news stories . . . are what Stuart Allan defines as an “ideological <em>construction</em> of reality.”</p>
  </blockquote>
  <p>Scholars have increasingly noted how media, science, and ideological discourse interface in interesting ways. As Carvalho (2007, p. 225), has discussed, ideologies are value-laden, normative, and political, and therefore media discourse and ideology are “mutually constitutive.” Media can validate scientific claims, make truth claims, or use values to evaluate science and scientists (ibid.). How receptive audiences are to environmental information also has an ideological dimension. Corbett (2006) wrote, “All environmental messages have ideological roots that are deep and influenced by individual experience, geography, history, and culture.” Corbett (2006, p. 26) summarizes environmental ideologies as “fully formed belief systems concerning the natural world,” and denotes the nuances along a scale from anthropocentric to ecocentric. She argues that most U.S. communication is anthropocentric, with a limited and one-sided ideological expression regarding the natural world.</p>
  <p>Other research has examined the role of culture in explaining environmental concern. This is important to the study of the news because it provides some basic notions about the different ways in which Hispanic audiences understand and perceive environmental issues. For example, the dynamics of public opinion in immigrant communities over time are not static. Schultz, Unipan, and Gamba (2000) discussed that foreign-born Latinos in the U.S. show higher levels of environmentalism than U.S. citizens (both Anglo and Latino). They suggested that this is explained partially by cultural differences, where Latinos live in more close-knit societies while the dominant U.S. culture is a more individualistic society. However, their study suggested that level of acculturation is negatively related to environmentalism. In other words, the longer a foreign-born Latino lives in the U.S., the more he/she becomes acculturated and therefore the levels of environmental concern become similar to those of the dominant U.S. culture. More recent work with Latino populations using community-based participatory research also suggests that Latino environmental discourses differ significantly from traditional Anglo-Western dualistic perspectives that place human and nature apart (Subervi-Vélez, 1999).  Lynch (1993, p. 118) suggested, “What differentiates U.S. Latino environmental perspectives from those of the Anglo-American mainstream is an un-willingness to sever people from the landscape, the technological from the political, or the environment from cultural identity.”</p>
  <p>However, the higher levels of concern about environmental issues of Hispanics as compared to non-Hispanic whites appears to be more prevalent on issues of proximate concern to these populations and not on more abstract environmental issues (Whittaker, Segura, &amp; Bowler, 2005). Studies examining the <em>white male effect</em> suggest important significant differences in risk perceptions between whites and other racial groups, where whites tend to see the world as less risky than any other group (Finucane et al., 2000; Flynn, Slovic, &amp; Mertz, 1994). Some minorities, including Hispanics, may dismiss certain health or environmental risks because they are already living with many highly visible risks (Mays &amp; Cochran, 1988). Other studies suggest that Hispanics perceive higher risk to them than to whites, as found in a study of the risk heat waves pose to the public (Palmer, 2003). These studies highlight differences but do not examine the ways in which Hispanics process information about environmental and health risks, which could explain such differences. Moreover, there is limited evidence about the sources of information used by Hispanics that may explain the formation of these risk perceptions. If the process of acculturation described above is indeed in place, what is the role of the media in promoting or preventing it? Moreover, in what ways are these dynamics reflected in media coverage of environmental issues?</p>
  <p>Also, the process of acculturation can be modifying the environmental perceptions brought from the immigrants’ countries of origin so that they now resemble the environmental discourses of the dominant culture.  However, environmental information from a Hispanic perspective is critical as the U.S. Hispanic population continues to increase; so, the contributions of Hispanic ecological discourses to the broader discourse on sustainable development may very well become more influential. Specifically, Peña (2003, p. 72) suggested: “Emergent Latino/a political ecologies must make reference to and explore strategies and projects of resistance generated by the submerged networks of displaced and re-localized cultures in an increasingly transnational civil society.”</p>

  <h3>Newsroom Decision Making and Diversity Models</h3>
  <p>Given the complexity of making and receiving environmental messages in the news, we choose to focus on how decisions are made about environmental news within the newsroom, an underexplored area of research, particularly in Spanish-language news. In order to explain news decision making about environmental issues, we turn to Shoemaker and Reese (1996), who developed a hierarchy-of-influences model to explain influences on media practice. In this model, they suggest that journalism content may be influenced by factors at various levels: the individual level (journalistic practices), the organizational level, factors external to the news organization (“extra media” factors, such as sources, economy, technology, money, or others), and the ideological level. This model has since been the subject of much research (e.g. Hanitzsch, 2006; Hanitzsch, 2007; Hanitzsch et al., 2010; Kim, 2010; Reese, 2001; Shoemaker and Vos, 2009; Voakes, 1997; Weaver et al., 2007), including international cross-comparison, that found that organizational, professional, and procedural factors influenced coverage more than structural ones (Hanitzsch et al., 2010); and also that routine forces (e.g. journalistic norms) have a stronger influence in determining what becomes news than individual forces (e.g. journalists’ beliefs) (Shoemaker, Eichholz, Kim, &amp; Wrigley, 2001). </p>
  <p>Indeed, journalistic role conceptions (Weaver, Beam, Brownlee, Voakes, &amp; Wilhoit, 2007) and norms may also influence output and perspectives. In terms of covering the environment, although some environmental journalists do practice forms of “advocacy journalism on behalf of the environment,” (see e.g. Frome, 1998), adherence to U.S. journalism values and norms such as objectivity and neutrality are standard tenets that journalists in U.S. newsrooms value (Hansen, 1994; Palen, 1999; Sachsman, Simon, &amp; Valenti, 2006). However, as environmental issues such as climate change became highly politicized in recent decades, accusations of bias or advocacy on behalf of political leanings or ideological slant have ramped up (Sachsman, Simon, &amp; Valenti, 2010), as have issues relating to tenets of balance and others in terms of voices and perspectives given weight as “expert” (Boykoff &amp; Boykoff, 2004). Prioritization of news values emphasizing conflict, drama, and institutional actors has also affected coverage, as observed in another study examining U.S. coverage of climate change: When personalization, dramatization (through sharp political contention), and authority-order bias norms (primarily consulting authority sources) took effect, the newspaper and television media had news (Boykoff &amp; Boykoff, 2007).</p>
  <p>In this paper we argue that these same influences are present in ethnic media, although the level of influence of the factors will show unique characteristics based on the media functions (i.e. acculturation) described in the previous sections.</p>

  <h3>Research Questions</h3>
  <p>As mentioned above, despite the increase in scholarly activity on scientific and environmental affairs, most have focused on U.S. English-language media or its Western counterparts (i.e. European countries), particularly in the realm of climate change (e.g., Boykoff &amp; Boykoff, 2007; McComas &amp; Shanahan, 1999; Nissani, 1999; Wilkins, 1993; Zehr, 2000). Only one research project examined media coverage of climate change in U.S. Spanish-language press (Villar &amp; Pinto, 2013), finding little attention paid to the topic nationally for Hispanic audiences.  No studies have discussed environmental coverage from a perspective within the newsroom.</p>
  <p>To bridge these gaps, this study is guided by the following research questions: To what degree are environmental issues covered in U.S. Spanish-language print and television news? What factors influence the coverage of environmental issues in Spanish-language television in the U.S.?</p>
  <p>More specifically, we can guide the study with the following specific research questions based on hierarchy of influences and role conception literature:</p>
  <p class="rq-list"><strong>RQ1.</strong> What are the professional journalistic factors influencing the coverage of environmental issues in the Spanish-language news media in the U.S.?</p>
  <p class="rq-list"><strong>RQ2.</strong> In what ways have media organizational structures and editorial decision-making processes influenced the coverage of environmental issues in the Spanish-language news media in the U.S.?</p>
  <p class="rq-list"><strong>RQ3.</strong> In what ways do individual journalists’ perspectives influence the coverage of environmental issues in the Spanish-language news media in the U.S.?</p>
  <p class="rq-list"><strong>RQ4.</strong> In what ways do journalists believe their audiences’ preferences influence the extent and type of coverage of environmental affairs in the Spanish-language news media in the U.S.? </p>
</section>
<section>
  <h2>Methodology</h2>
  <p id="note-line-3">In order to answer these questions, we first conducted an exploratory content analysis of major Spanish-language news outlets about major environmental issues. We selected 80 RSS (Real Simple Syndication) feeds from different U.S. Spanish-language news media, based on the Pew Research Center’s 2011 “State of the News Media” report of Hispanic media.<sup><a href="#note-3">[3]</a></sup> These feeds represented the following television news outlets: Univision, Telemundo, CNN en Español national and also in the markets of New York, Los Angeles, Miami, Dallas, Houston, and Chicago. In terms of the print media, we obtained feeds from <em>El Sentinel</em>, <em>La Opinión</em>, <em>El Diario</em>, <em>Rumbo</em>, <em>El Mensajero</em>, <em>Hoy Los Ángeles</em>, <em>La Raza</em>, <em>Vívelo Hoy</em>, <em>Diario las Américas</em>, <em>Al Día</em> (Texas), <em>Diario de México USA</em>, and <em>El Nuevo Herald</em>.</p>
  <p>We collected all articles and transcripts published in RSS feeds every 24 hours between October 5th and November 8th 2012, the month before the presidential election. RSS feeds, sent daily to the subscribers, consist of a selection of the most important stories according to the editorial team of each media). Although this is a relatively short period of analysis, the presidential election context heightens the coverage of policy discussions, and therefore we would argue this is one of the contexts where environmental coverage could receive considerable attention. In addition, the goal of the content analysis is not to examine trends in the coverage of environmental issues across time, but to illustrate the typical coverage at any given point in time. </p>
  <p>HDD (<em>Herramienta de documentalista</em>) software was used to gather the articles and conduct the analysis. This allowed us to gather large numbers of online articles (13,276) and then to sort, filter, and analyze them (Diago, 2011, 2013). We predefined “<em>materias</em>” (topics) of major environmental and natural-disaster issues that could result in national or regional coverage: “<em>calentamiento global</em>, <em>huracán</em>, <em>inundación</em>, <em>medio ambiente</em>, Sandy, <em>sequía</em>,” (global warming, hurricane, floods, environment, Sandy, drought) or their synonyms, keywords that were used to search for the stories. We recognize the challenge of collecting all environmental stories, and that the keywords only capture a subset of them. With this in mind, in this study we only report the frequencies of issues to provide an overview of the overall environmental coverage in the aforementioned time period.</p>
  <p>Then, in order to understand the trends found in the content analysis, we conducted in-depth interviews with 12 news professionals at various Spanish-language news organizations (see Appendix 1 for the list of interviewees). We used a convenience sampling approach and employed several criteria to select the individuals: their leadership position among some of the largest Spanish-language media outlets in the country, their accessibility based on personal connections; and the individuals’ availability and willingness to participate. Semi-structured, in-depth interviews were conducted in person and via Skype, and the interview responses were analyzed qualitatively for emerging themes and compared against the existing literature discussed above. The thematic analysis allowed us to identify common themes within and across the interviews and confirm saturation, which means no new themes emerged with every additional interview conducted. All of the interviewees agree that global warming and environmental issues were important to them and key for the future of our planet.  Still, none of them considered the issues a coverage priority.  They were also in agreement on the justification for this apparent contradiction, as interviewees explained they had to balance more immediate priorities in regard to coverage (journalistic practices at an individual level), and a lack of resources (external factors at an organizational level). </p>
  <p>We gave the respondents the option of remaining anonymous, with nine opting to be quoted with name and title. Nevertheless, we used only their initials to report the results to maintain consistency with those who wanted to remain anonymous. The interviews focused on the professional, structural, and personal factors that can influence the decision to cover environmental affairs, or not.</p>
</section>
<section>
  <h2>Results</h2>
  <p>Environmental themes, according to the respondents and the content analysis, are not being covered in Spanish-language media in a comprehensive or adequate manner. Although the total number of stories collected in the RSS feeds was 13,276, very few of these dealt with environmental issues (see Table 1).</p>
  <h3><strong>Table 1.</strong> Environmental Stories from RSS Feeds of Spanish-Language Media</h3>
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Percent of the coverage</th>
        <th>Number of Stories</th>
        <th>Duplicates</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <td colspan="4">
          <em>Note: * HDD software calculation (a classic of indexation and automatic classification) allowed us to differentiate between hurricane and flooding when assigning a “materia” (or topic) to a document, based on the number of words that appeared and were repeated during the text.</em>
        </td>
      </tr>
    </tfoot>
    <tbody>
      <tr>
        <td>Sandy</td>
        <td>7.07%</td>
        <td>500</td>
        <td>176</td>
      </tr>
      <tr>
        <td>Hurricane*</td>
        <td>5.08%</td>
        <td>343</td>
        <td>111</td>
      </tr>
      <tr>
        <td>Drought</td>
        <td>0.20%</td>
        <td>14</td>
        <td>10</td>
      </tr>
      <tr>
        <td>Flood</td>
        <td>0.20%</td>
        <td>14</td>
        <td>8</td>
      </tr>
      <tr>
        <td>Environment</td>
        <td>0.16%</td>
        <td>11</td>
        <td>11</td>
      </tr>
      <tr>
        <td>Global warming</td>
        <td>0.04%</td>
        <td>3</td>
        <td>0</td>
      </tr>
    </tbody>
  </table>
  <p id="note-line-4">Hurricane Sandy, as an event, garnered somewhat more coverage, but other topics, such as climate change, barely registered at all, which is surprising considering the episodic but significant coverage the issue receives in the mainstream media.<sup><a href="#note-4">[4]</a></sup> These findings are in line with other studies of Hispanic and Latin American media (Villar &amp; Pinto, 2013; Zamith, Pinto, &amp; Villar, 2013).</p>
  <p>When asked why, broad themes emerged that encompassed structural, organizational and professional dimensions that resounded with previous studies of environmental information in U.S. mainstream English-language news (Archibald, 1999; Smith, 2005), and added new dimensions to the discussion. All respondents mentioned a lack of resources affecting journalistic output and focus, particularly in terms of possibilities for investigation and enterprise or proactive journalism, with one calling such reporting a “luxury” that the organization could not afford. The effects of ratings wars and a shrinking news hole on environmental news have been well represented in other studies of environmental journalism and its paucity in mainstream news (Friedman, 2004; Hansen, 2011; Sachsman, Simon, &amp; Valenti, 2006), as well as in Spanish-language press (Villar &amp; Pinto, 2013). </p>
  <p><em>‘Important to Me, but Not to My Organization or My Audience’</em></p>
  <blockquote>
    <p>Hispanic media have to begin to create awareness about environmental issues, to create a little pressure. It’s a challenge… but it’s important that the people read it and understand it, and that they create a little bit of pressure... Maybe [environmental news] doesn’t directly make day-to-day life better, but it’s going to make life better in the future. (VC)</p>
  </blockquote>
  <p>All respondents noted that they, personally, were interested in environmental issues and thought they were important topics to cover. As one respondent said in discussing his coverage of the Chevron contamination case in Ecuador:</p>
  <blockquote>
    <p>I get a close look, I have touched, I have been present at this type of debate, I have developed a degree of commitment and of conscience regarding environmental themes. (DR)</p>
  </blockquote>
  <p>However, when asked to rank topics such as the economy, politics, immigration, health, sports, education, violence, or corruption in terms of importance, almost all respondents consistently listed environmental themes last, or toward the bottom (see Figure 1).</p>
  <figure>
    <h4><strong>Figure 1.</strong> Average Rankings of Topics by Respondents in Terms of Importance to Audience (n=10)</h4>
    [FIGURE 1 GOES HERE]
  </figure>
  <p>When asked why, organizational challenges were enumerated. They included lack of resources to take on investigative enterprise topics as well as lack of interest on the part of news managers seeking ratings and circulation numbers: “When you are in a big company, well, the themes have to pass more filters.” (ES) Another respondent who worked in Spanish-language television noted the fierce pressure of ratings on newscasts:</p>
  <blockquote>
    <p>[In television journalism, we have a newscast each night]. But your news director never asks you, how was the newscast? He asks you, how was the show? It’s a show on television, one that has to have attractive things and bring ratings. (VC)</p>
  </blockquote>
  <p>The responses also revealed journalistic principles favoring news values. Most responded that environmental issues get covered when the news pegs of immediacy and impact are met, what Revkin (2006, p. 224) has called “the tyranny of the news peg.”</p>
  <blockquote>
    <p>Spanish language media is one that reacts to what is happening; it is not proactive. [The environment] gets covered when there’s a natural disaster, and we cover how to find services and public assistance afterward, but not why these disasters are bigger and more frequent each year. (MS)</p>
  </blockquote>
  <p>One respondent (DC) noted that, in his view, environmental issues impacted his audiences “in a thousand distinct ways”:</p>
  <blockquote>
    <p>They affect them by the negative labor conditions… contamination in poor urban zones that are in general where Hispanics may live, by contaminated food, or oil stories…. It’s necessary that we have coverage of these aspects…. But obviously, the focus is on what is affecting you; that is news. </p>
  </blockquote>
  <p>As others noted, even journalistic enterprise, experience, and interest in covering environmental themes may not be enough to overcome the obstacles and gatekeepers from within news organizations:</p>
  <blockquote>
    <p>When I covered environmental themes at the global level or the U.N., I saw it as a form of assigning myself.… But I saw that these themes were not being welcomed.… It wasn’t a priority for the media. (DR)</p>
  </blockquote>
  <p>Various respondents attributed these contradictions to a lack of “awareness,” both within the media as well as among their audiences. The functions of a journalist, beyond informing and explaining, is also to create awareness of the important issues of the day, they often said:</p>
  <blockquote>
    <p>Personally, I believe that what’s missing is that journalists also create more awareness… just like we do when covering health… but I think that journalists personally do not understand that [these] stories are important, and so we don’t pressure the managers so that they take them as serious themes…. I believe journalists and reporters need to become more aware themselves that it is important to cover these themes and put it out into the Hispanic community in terms of how it affects or doesn’t affect them. (MA) </p>
    <p>As long as this awareness doesn’t exist, the media won’t take on their responsibility and journalists won’t look for training. There won’t be change; there will always be superficial coverage, or an irrelevant theme, or not in-depth reporting. (DR)</p>
  </blockquote>
  <p>In addition, part of this lack of interest and awareness from news decision makers appears to be a function of the perception of the attributes of the issues. Environmental issues were described as “complicated,” and neither “sexy” nor “audience drivers,” and therefore remained off the editorial agendas.  As one participant said:</p>
  <blockquote>
    <p>Hispanic media is more concerned with segmenting… or monetizing… than [with] offering public service to the community. There is a clash of principles. (MS) </p>
  </blockquote>
  <p>Another respondent said:</p>
  <blockquote>
    <p>I think the other problem in environmental coverage is that it isn’t as sexy as covering the deaths on the border, or the immigration policies, and since one can’t sell it equally, we leave it. (MA)</p>
  </blockquote>
  <p><em>Audience Functionality</em></p>
  <p>Related to this, most respondents also shared a perception that the audience was not interested in environmental information. The majority saw their audiences as immigrants seeking information about employment, housing, and how to better understand U.S. culture. They saw their roles as journalists to inform and explain, but also they understood that their audiences used their content to educate and acculturate themselves––immigrants living day to day, working to find employment and housing, to get ahead in their daily lives, finding, as one put it, the “Hispanic angle.” (MS)</p>
  <blockquote>
    <p>[We cover] themes important to the audience. It depends on the market. Our market . . . many of them are immigrants. So everything has to do with how they can improve their lives: job searches, education, security. (Anon.)</p>
    <p>In the United States, Hispanic journalism has a very clear theme, which is coverage of immigration, for example, themes that concern the search for well-being of the Hispanic community of immigrants: health, education, labor themes. (DR)</p>
    <p>Hispanic media create a sense of belonging, that they are educational media. The Hispanic still watches Spanish-language television as a window toward the U.S., its culture. They want to know what’s happening, but they also want to know how to live in this country… Hispanic media  still are the media used by people to acculturate themselves. (VC)</p>
  </blockquote>
  <p>Another respondent differentiated among the Hispanic population to discuss nuances in terms of generation and education. The significant differences between Latino generations based on their levels of assimilation and acculturation (Smith, 2003) are important when considering their information needs. One respondent said:</p>
  <blockquote>
    <p>I believe there is more awareness of environmental themes in the segment of the Hispanic population that only speaks English or the segment that is bilingual but searches for content in English because Spanish-language content doesn’t satisfy them. (ES)</p>
  </blockquote>
  <p><em>Comparisons with Other Media</em></p>
  <p>When asked to contrast environmental coverage by Spanish-language media to that of other (U.S. English-language, or country-of-origin media), responses differed slightly. Several said they believed U.S. English-language media fared better, with more comprehensive coverage, but for different reasons: more resources than Spanish-language media, translation services, better access to information than in Latin America. One cited acculturation functions of media that bring audience numbers:</p>
  <blockquote>
    <p>The American media cover it better than Hispanic media. They pay more attention…. American media do not have to worry about [creating a sense] of belonging. (VC)</p>
  </blockquote>
  <p>Other responses included that Spanish media covered it better (MS), that Latin American media did not cover it as well (MS and RV), and also that media in Puerto Rico covered it more often that U.S. media did (PR).</p>
  <p>In one interview, the question of comparison with English-language media took on new dimensions when discussing differences between <em>El Nuevo Herald</em>, one of Miami’s Spanish-language newspapers, and <em>The Miami Herald</em>, the English-language daily. While most of the other respondents characterized their audiences as immigrants seeking information for day-to-day life, using public transportation, working in agrarian sectors, <em>El Nuevo</em>’s then-executive editor (MG), saw his newspaper’s public differently, “We have readers from the worker to the multi-millionaire living on Key Biscayne.” <em>El Nuevo</em> also had additional opportunities to publish environmental news, MG said, noting that they are able to translate stories from <em>The Miami Herald</em>’s environmental reporter, Curtis Morgan. He noted several stories that have been important to their audiences, such as those on anticipated huge upgrades to Miami-Dade County’s water and sewer system, and on tropical storms, among others. A story regarding oil exploration off the coast of Cuba published the year prior was one of the most read stories, according to MG. However, he did note differences among English- and Spanish-language audiences:</p>
  <blockquote>
    <p>Environmental themes are key for English language audiences.… It’s not true that they are not also key for us, but here there are priorities. In <em>The Miami Herald</em>, it’s very important what is happening in the Everglades and if they are going to move the Urban Development Boundary…. But it’s not a black-and-white thing. It’s not as if we don’t also think this is important…. We do think it’s important. But Cuba, Venezuela, and other themes are a little higher. But this  depends story to story.</p>
  </blockquote>
  <p><em>Challenging Content to Cover Adequately?</em></p>
  <p>The interviews also focused on the perceptions of environmental issues’ attributes, and the presumed difficulty of covering science-based issues. Only two interviewees responded that environmental news was challenging because of its complexity and scientific dimensions, with the others responding that it was not. Some noted that environmental or scientific topics were necessarily difficult for the journalist to translate and explain; the difficulty was in convincing executives and news directors that such topics were important for the communities. One called it a “myth” that environmental themes were difficult for journalists to cover:</p>
  <blockquote>
    <p>I don’t believe [environmental] coverage is difficult or complex…. Like any other theme, you have to educate yourself, you have to understand it so you can explain it. (MA)</p>
    <p>I have a team of reporters with a lot of experience. They educate themselves and don’t publish anything if they don’t understand the topic. They speak with a lot of experts…. It can be a complex topic, but we speak with experts who guide us. (MG)</p>
  </blockquote>
  <p>When asked to explain their perceptions of the content of environmental stories, respondents described distinct interpretations of what “environmental” themes encompassed, with examples that ranged from recycling batteries to climate change, the Everglades, the Galapagos, hurricanes, the BP oil spill, mining, the weather, or pesticides. Respondents gave wide-ranging examples when discussing environmental news coverage: developments and actions that impacted health or the economy, such as the BP oil spill or pesticides on food production, events such as Earth Day, and also the growing visibility of extreme weather events in the news. </p>
  <p>The theme of weather and weather events, discussed peripherally by three and in depth by one respondent, presents an interesting avenue to explore how climate change and other environmental issues may become inserted more frequently into newscasts, as they change from being abstractions to issues with impact that act as audience drivers. As one participant noted, Hurricane Sandy evolved into a political story as the 2012 presidential election was affected by changes in candidate support from governors of key states, and that such effects on traditional news beats could be expected with continuing climate change:</p>
  <blockquote>
    <p>Everybody is realizing that the environment is something that each day, plays a more central role. It’s going to force us to cover the environment more…. Our challenge is to find a way to present environmental issues in a more entertaining, informative… way, because it’s an important topic. (VC)</p>
  </blockquote>
  <p>This process, as the weather or weather events become “<em>pura actualidad</em>” (relevant) when they turn into natural disasters, could have transnational dimensions, as ES noted. His organizations covered “all types of disasters” in Latin America as well as the United States, as environmental themes became news in this way.  </p>
  <p>Another interviewee explained that weather as environment is an important day-to-day news peg for their audience––who needed to be outside, heading to work, living their lives.  They compared it to covering local transportation in terms of the day-to-day necessity, as well as how an environmental item could become a top news priority:</p>
  <blockquote>
    <p>[B]ecause weather is environment. The fact of changing weather… a few weeks ago, there was flooding here. We went out into the streets, and we put a 12-minute first segment that no one else had.… For three days, we reported mainly on weather. Environment can become the most important theme. (Anon.)</p>
  </blockquote>
  <p>Recent research focusing on the role of meteorologists in communicating climate change through their weather forecasts validates the increasing importance of making this issue relevant to individuals in their daily life (Wilson, 2008, 2009).</p>
</section>
<section>
  <h2>Discussion and Conclusion</h2>
  <p>This study offers relevant insights into how Spanish-language media in the U.S. make news decisions concerning environmental issues. In this section we discuss such findings, and provide recommendations for future areas and directions of research that could help us better understand news decision making in ethnic media.</p>
  <p>First, in regards to RQs 1, 2, and 3, the results show that within the hierarchy of influences model (Shoemaker and Reese, 1996), organizational, extramedia, and professional influences appear to have strong impact on the ability to report on environmental news. More specifically, revenue streams (extramedia), the perception of editors/executives that environmental news is not important (organizational), and the perception that environmental stories lack immediacy/impact (professional) are the main reasons cited by the respondents. Such findings reflect other research examining news production of environmental affairs in English-language mainstream media (e.g. Friedman, 2004; Lester, 2010; Shanahan &amp; McComas, 1997).</p>
  <p>Indeed, responses indicated there is confusion, or perhaps simply broad interpretation, in terms of what environmental news actually is, something that has implications for understanding news gatekeeping.  From this initial study, it would seem that there are differences within Spanish-language newsrooms, so that audiences’ environmental value systems and beliefs are viewed in drastically different ways. For the most part, these organizational, professional, and extramedia influences were at odds with the respondents’ perceptions that environmental issues were important and should be on the media agenda. Further, respondents argued that environmental stories are not challenging to cover (so do not present a professional obstacle). This contradicts previous research on environmental journalism and the difficulties journalists face in translating environmental and scientific information (Archibald, 1999; Yang, 2004). This self-assurance is surprising. Previous research on environmental journalists in the U.S. reports conflicting results in regards to the role of scientific knowledge (Yang, 2004) and science training (Archibald, 1999) on environmental reporting. Nuances in levels of perceived knowledge (Sundblad, Biel, &amp; Garling, 2009) can affect the way accuracy with which journalists report on these issues (Wilson, 2000). More research will be needed to confirm whether this is a widespread perception of news decision makers in Hispanic and other ethnic media, and whether it has an effect on the way the issues are covered.</p>
  <p>Second, from a role-conception perspective (RQ 3), the results did not reveal the tension between objectivity and advocacy sometimes discussed in the literature on environmental journalism (Palen, 1999). Several of the respondents mentioned that their role was to raise awareness for some of these environmental issues (something consistent with the advocacy role; see Tandoc and Takahashi, 2014), something similar to what they have done with health issues. In addition, the respondents discussed lack of specialization, which includes the non-existence of an environmental beat, a feature more commonly found in English-language media. This limitation can help explain why this tension is not as prevalent Spanish-language media as it has been reported elsewhere. However, respondents expressed a desire that agencies, nonprofits, organizations with prestige, or professional organizations such as the Society of Professional Journalists (SPJ) or the National Association of Hispanic Journalists (NAHJ) would “pressure” or remind journalists and their editors about the importance of more coverage.  All respondents noted they, as individuals, found environmental news important to cover. Again, this suggested multi-directional processes at work in terms of public and media agendas, as well as within the hierarchical structure. </p>
  <p>Third, as regards RQ 4 and related to the point above, respondents overwhelmingly suggested that the lack of coverage of environmental news is a response to audiences’ needs. Cultural processes played an important role, from the perspectives articulated here. One consistent emergent theme from our study indicated that most of the content producers for Spanish-language media we interviewed perceived their audiences’ use of media as predominantly oriented toward acculturating into U.S. culture, viewing it as a largely “utilitarian” usage (Ríos &amp; Gaines, 1998, p. 755).  There is a sense that audiences aren’t interested in environmental news to the degree that they are in “day-to-day” affairs, and that most people use Hispanic media to aid them in the acculturation process, to solve day-to-day problems and get ahead with their lives.  Cultural processes associated with media uses have provided many avenues of research on Spanish-language media and their audiences (e.g. Guzmán, 2006; Subervi-Vélez, 1986, 1999; Ríos &amp; Gaines, 1998). Others have noted the prioritization of needs such as health, immigration, justice, place, and culture (Santiago-Irizarry, 2003), and the lack of other important information, such as environmental topics or policy issues. This cultural function is also consistent with the arguments articulated by Carvalho (2007) and Corbett (2006) in the context of dominant anthropocentric ideologies in the communication of environmental issues. The individual experiences of newsmakers and audiences, geographical characteristics, history, and overall culture (Corbett, 2006), played a role in the ways that environmental issues were, or were not, reported by Spanish-language media.    </p>
  <p>However, nuances were also articulated. For example, as RP noted, “South Florida is a world apart.” As a diverse region, with a majority (69% as of the 2010 Census) immigrant population in Miami-Dade County, the unique relationship between the two main newspapers allows for more efficient use of resources. Although MD clarified that <em>El Nuevo Herald</em> and <em>The Miami Herald</em> have two distinct editorial lines, they may decide to “interchange” stories, depending on audience interest. And rather than a focus on immigration, which he ranked lower than did other respondents, MD’s perceptions of audience interests involved home countries, particularly Cuba and Venezuela. Interestingly, he noted that one of the most read stories of the previous year involved potential oil exploration off the coast of Cuba by Venezuelan companies, which had implications for Florida coastlines. This nexus of conflict, countries of origin, politics, and environment evolved into an important story. Several respondents mentioned region-specific nuances in terms of how broadly defined “environmental news” had more immediacy for news audiences. These include, for example, health issues related to pollution in Los Angeles, and weather events in Chicago.</p>
  <p>Another respondent (ES) also noted the importance of generational shifts and organizational orientations. His outlet, VOXXI, catered to English-speaking or bilingual Hispanics, therefore, second- and third-generation residents, who in his view, care more about environmental issues than most first-generation or recently arrived immigrants do. In addition, in a smaller organization such as his, there was more room for enterprise journalism, since content wasn’t already necessarily earmarked for specific sections, such as politics, the economy, or immigration.</p>
  <p>The results of this study provide a first look into why environmental issues in Spanish-language media have been largely ignored by researchers. This exploratory study has several limitations, so we consider the results preliminary, a first step in an area of study that has received very little attention. The limitations include the sample size of the content analysis and interviews, which as we discussed in the methods sections, we expect to expand. </p>
  <p>Therefore, more work is needed to understand the dynamic nature of audience interests, and how these interests are reflected in, and influence (or don’t) media agendas. Our results show that Spanish-language media do not create a sense of consciousness about the environment among Hispanics, something that Kerevel (2011) aregues is a main functions of these media. Future studies should explore how coverage of environmental issues, both in English- and Spanish-language media, influence the process of acculturation, and how ideology manifests itself in the processes of news media production. In other words, are Hispanics in the U.S. conforming to dominant environmental discourses and behaviors, or do they retain and reinforce their own cultural perceptions about nature and environmental issues? Also, how are those processes being understood by news content producers? As Guzmán (2006, p. 293) wrote:</p>
  <blockquote>
    <p>[I]mmigrants continue to serve a symbolic and political utility for the ideological tensions between immigrant host and home country… [T]he ideological relationship between ethnic and general-market press will play an increasingly vital function in defining the public discourse of citizenship, community, and culture.</p>
  </blockquote>
  <p>As the Hispanic population continues to grow in size and power in the U.S., the ways in which the public agenda and media agenda interface regarding coverage of environmental issues such as climate change will remain important avenues of research for scholars in various disciplines. For example, the research examining a shared culture between scientists and journalists, as well as the need for scientifically based training of environmental journalists, suggest that journalists, in Spanish-language media as well as in other ethnic media, will face considerable challenges in their reporting. This will be especially important when coverage moves beyond the day-to-day needs of audiences, and requires more in-depth examination of the science and the policy implications behind environmental issues.</p>
</section>
<hr />
<section>
  <h2>References</h2>
  <p class="references">Abrajano, M., &amp; Singh, S. (2009). Examining the link between issue attitudes and news source: The case of Latinos and immigration reform. <em>Political Behavior, 31</em>(1), 1-30.</p>
  <p class="references">Anderson, A. (2009). Media, politics and climate change: Towards a new research agenda. <em>Sociology Compass, 3</em>(2), 166-182. </p>
  <p class="references">Archibald, E. (1999). Problems with environmental reporting: Perspectives of daily newspaper reporters. <em>Journal of Environmental Education, 30</em>(4), 27-32. </p>
  <p class="references">Boykoff, M., &amp; Boykoff, J. (2004). Balance as bias: Global warming and the U.S. prestige press. <em>Global Environmental Change, 15</em>(2), 125–136.  </p>
  <p class="references">Boykoff, M., &amp; Boykoff, J. (2007). Climate change and journalistic norms: A case study of U.S. mass-media coverage. <em>Geoforum, 38</em>(6), 1190-1204.</p>
  <p class="references">Branton, R., &amp; Dunaway, J. (2008). English- and Spanish-language media coverage of immigration: A comparative analysis. <em>Social Science Quarterly, 89</em>(4), 1006-1022. </p>
  <p class="references">Carvalho, A. (2007). Ideological cultures and media discourses on scientific knowledge: Re-reading news on climate change. <em>Public Understanding of Science, 16</em>, 223-243.</p>
  <p class="references">Corbett, J. (2006). <em>Communicating nature: How we create and understand environmental messages</em>. Washington, D.C.: Island Press.</p>
  <p class="references">Diago, F. J. (2011). Procedimiento de cálculo de la materia probable de un documento de texto y su uso en el programa informático “Herramienta de Documentalista.” Retrieved from <a href="http://eprints.rclis.org/15375/1 como%20se%20calcula%20la%20materia%20probable2.pdf" target="_blank">http://eprints.rclis.org/15375/1 como%20se%20calcula%20la%20materia%20probable2.pdf</a></p>
  <p class="references">Diago, F. J. (2013). APIs to improve the information aggregation system: The uses of HDD software and other applications. <em>Boletín ANABAD, 63</em>(3), 523-537.</p>
  <p class="references">Ennis, S., Ríos-Vargas, M., &amp; Albert, N. (May, 2011). <em>The Hispanic population: 2010</em>. 2010 Census Briefs. United States Census Bureau. C2010BR-04.</p>
  <p class="references">Finucane, M. L., Slovic, P., Mertz, C. K., Flynn, J., &amp; Satterfield, T. A. (2000). Gender, race, and perceived risk: The ‘white male’ effect. <em>Health, Risk &amp; Society, 2</em>(2), 159-172. </p>
  <p class="references">Flynn, J., Slovic, P., &amp; Mertz, C. K. (1994). Gender, race, and perception of environmental health risks. <em>Risk Analysis, 14</em>(6), 1101-1108.</p>
  <p class="references">Fowler, E., Hale, M., &amp; Olsen, T. (2009). Spanish- and English-language local television coverage of politics and the tendency to cater to Latino audiences. <em>International Journal of Press/Politics, 14</em>(2), 232-256. </p>
  <p class="references">Friedman, M., Dunwoody, S., &amp; Rogers, C. L. (1986). <em>Scientists and journalists: Reporting science as news</em>. New York: Free Press.</p>
  <p class="references">Friedman, S. ( 2004). And the beat goes on: The third decade of environmental journalism. In S. Senecah, S. Depoe, M. Neuzil, &amp; G. Walker (Eds.) <em>Environmental communication yearbook</em>, Vol. 1 (pp. 175-187). London: Lawrence Erlbaum. </p>
  <p class="references">Frome, M. (1998). <em>Green ink: An introduction to environmental journalism</em>. Salt Lake City: University of Utah Press.</p>
  <p class="references">Guzmán, I. (2006). Competing discourses of community: Ideological tensions between local general-market and Latino news media. <em>Journalism, 7</em>(3), 281-298. </p>
  <p class="references">Hale, M., Olsen, T., &amp; Fowler, E. (2009). A matter of language or culture: Coverage of the 2004 U.S. elections on Spanish- and English-language television. <em>Mass Communication and Society, 12</em>(1), 26-51. </p>
  <p class="references">Hanitzsch, T. (2006). Mapping journalism culture: A theoretical taxonomy and case studies from Indonesia. <em>Asian Journal of Communication, 16</em>(2), 169-86.</p>
  <p class="references">Hanitzsch, T. (2007). Deconstructing journalism culture: Toward a universal theory. <em>Communication Theory, 17</em>(40), 367-385. </p>
  <p class="references">Hanitzsch, T., Anikina, M., Berganza, R., Cangoz, I., Coman, M., Hamada, B., . . . Yuen, K. W. (2010). Modeling perceived influences on journalism: Evidence from a cross-national survey of journalists. <em>Journalism &amp; Mass Communication Quarterly, 87</em>(1), 5-22.</p>
  <p class="references">Hansen, A. (1994). Journalistic practices and science reporting in the British press. <em>Public Understanding of Science, 3</em>(2), 111-134. </p>
  <p class="references">Hansen, A. (2011). Communication, media and environment: Towards reconnecting research on the production, content and social implications of environmental communication. <em>International Communication Gazette, 73</em>(1-2), 7-25.</p>
  <p class="references">Kerevel, Y. (2011). The influence of Spanish-language media on Latino public opinion and group consciousness. <em>Social Science Quarterly, 92</em>(2), 509-534. </p>
  <p class="references">Kim, H. (2010). Forces of gatekeeping and journalists’ perceptions of physical danger in post-Saddam Hussein’s Iraq. <em>Journalism and Mass Communication Quarterly, 87</em>(4), 484-500.</p>
  <p class="references">Lester, L. (2010). <em>Media and environment: Conflict, politics and the news</em>. Malden, MA: Polity Press.</p>
  <p class="references">Lozano, J. C. (1989). Issues and sources in Spanish-language TV: A comparison of Noticiero Univision and NBC Evening News. <em>Frontera Norte, 1</em>(1), 151-173.</p>
  <p class="references">Lynch, B. (1993). The garden and the sea: U.S. Latino environmental discourses and mainstream environmentalism. <em>Social Problems, 40</em>(1), 108-124. </p>
  <p class="references">Mays, V. M., &amp; Cochran, S. D. (1988). Issues in the perception of AIDS risk and risk reduction activities by Black and Hispanic/Latina women. <em>American Psychologist, 43</em>(11), 949-957.</p>
  <p class="references">McComas, K., &amp; Shanahan, J. (1999). Telling stories about global climate change: Measuring the impact of narratives on issue cycles. <em>Communication Research, 26</em>(1), 30-57.</p>
  <p class="references">Moran, K. C. (2006). Is changing the language enough? The Spanish-language ‘alternative’ in the USA. <em>Journalism, 7</em>(3), 389-405. </p>
  <p class="references">Nissani, M. (1999). Media coverage of the greenhouse effect. <em>Population &amp; Environment, 21</em>(1), 27-43.</p>
  <p class="references">NOAA. (2012). United States flood loss report: Water year 2012. Retrieved from <a href="http://www.nws.noaa.gov/hic/summaries/WY2012.pdf" target="_blank">http://www.nws.noaa.gov/hic/summaries/WY2012.pdf</a>.</p>
  <p class="references">Okamoto, D., Ebert, K., &amp; Violet, C. (2011). ¿El campeón de los hispanos? Comparing the coverage of Latino/a collective action in Spanish- and English-language newspapers. <em>Latino Studies, 9</em>(2), 219-241. </p>
  <p class="references">Palen, John. (1999). Objectivity as independence. <em>Science Communication, 21</em>(2), 156-171.</p>
  <p class="references">Palmer, C. (2003). Risk perception: Another look at the ‘white male’ effect. <em>Health, Risk &amp; Society, 5</em>(1), 71-83. </p>
  <p class="references">Peña, D. G. (2003). The scope of Latino/a environmental studies. <em>Latino Studies, 1</em>(1), 47-78. </p>
  <p class="references">Piñón, J., &amp; Rojas, V. (2011). Language and cultural identity in the new configuration of the U.S. Latino TV industry. <em>Global Media and Communication, 7</em>(2), 129-147. </p>
  <p class="references">Reese, S. (2001). Understanding the global journalist: A hierarchy of influences approach. <em>Journalism Studies, 2</em>(2), 173-187. </p>
  <p class="references">Revkin, A. C., (2006). The daily planet: Why the media stumble over the environment. In D. Blum, M. Knudson, &amp; R. M. Henig (Eds.), <em>A field guide for science writers</em>. (pp. 222-228). New York: Oxford University Press. </p>
  <p class="references">Ríos, D. I., &amp; Gaines, S. O. (1998). Latino media use for cultural maintenance. <em>Journalism and Mass Communication Quarterly, 75</em>(4), 746-761.</p>
  <p class="references">Sachsman, D. B., Simon, J., &amp; Valenti, J. M. (2006). Regional issues, national norms: A four-region analysis of U.S. environment reporters. <em>Science Communication, 28</em>(1), 93-121.</p>
  <p class="references">Sachsman, D., Simon, J., &amp; Valenti, J. M. (2010). <em>Environment reporters in the 21st century</em>. New Brunswick, NJ: Transaction Publishers.</p>
  <p class="references">Santiago-Irizarry, V. (2003). Environmentalism, identity politics and the nature of ‘nature.’ <em>Latino Studies, 1</em>(1), 79-89. </p>
  <p class="references">Schultz, W., Unipan, J., &amp; Gamba, R. (2000). Acculturation and ecological worldview among Latino Americans. <em>Journal of Environmental Education, 31</em>(2), 22-27. </p>
  <p class="references">Shanahan, J., &amp; McComas, K. (1997). Television’s portrayal of the environment: 1991-1995. <em>Journalism &amp; Mass Communication Quarterly, 74</em>(1), 147-159. </p>
  <p class="references">Shoemaker, P., Eichholz, M., Kim, E., &amp; Wrigley, B. (2001). Individual and routine forces in gatekeeping. <em>Journalism &amp; Mass Communication Quarterly, 78</em>(2), 233-246. </p>
  <p class="references">Shoemaker, P., &amp; Reese, S. (1996). <em>Mediating the message</em>. White Plains, NY: Longman.</p>
  <p class="references">Shoemaker, P., &amp; Vos, T. (2009). <em>Gatekeeping theory</em>. New York: Routledge. </p>
  <p class="references">Smith, J. (2003). Assimilation across the Latino generations. <em>American Economic Review, 93</em>(2), 315-319. </p>
  <p class="references">Smith, J. (2005). Dangerous news: Media decision making about climate change risk. <em>Risk Analysis, 25</em>(6), 1471-1482. </p>
  <p class="references">Soruco, G. (1996). <em>Cubans and the mass media in South Florida</em>. Gainesville: University Press of Florida.</p>
  <p class="references">Subervi-Vélez, F. (1986). The mass media and ethnic assimilation and pluralism: A review and research proposal with special focus on Hispanics. <em>Communication Research, 13</em>(1), 71-96. </p>
  <p class="references">Subervi-Vélez, F. (1999). Spanish-language television coverage of health news. <em>Howard Journal of Communications, 10</em>(3), 207-228. </p>
  <p class="references">Subervi-Vélez, F. (2008). Latinos’ use of media and the media’s influence on political knowledge and participation: Findings from the 1989 Latino political survey. In F. A. Subervi-Vélez (Ed.), <em>The mass media and Latino politics</em> (pp. 323-349). New York: Routledge.</p>
  <p class="references">Sundblad, E., Biel, A., &amp; Garling, T. (2009). Knowledge and confidence in knowledge about climate change among experts, journalists, politicians, and laypersons. <em>Environment and Behavior, 41</em>(2), 281-302. </p>
  <p class="references">Tandoc, E., &amp; Takahashi, B. (2014). Playing a crusader role or just playing by the rules? Role conceptions and role inconsistencies among environmental journalists. <em>Journalism: Theory, Practice, and Criticism, 15</em>(7), 889-907.</p>
  <p class="references">Thorson, E. (2006). Print news and health psychology: Some observations. <em>Journal of Health Psychology, 11</em>(2), 175-182.</p>
  <p class="references">Vargas, L. (2000). Genderizing Latino news: An analysis of a local newspaper’s coverage of Latino current affairs. <em>Critical Studies in Media Communication, 17</em>(3), 261-293. </p>
  <p class="references">Vargas, L., &amp; De Pyssler, B. J. (1999). U.S. Latino newspapers as health communication resources: A content analysis. <em>Howard Journal of Communication, 10</em>(3), 189-205.</p>
  <p class="references">Veciana-Suárez, A. (1990). <em>Hispanic media. Impact and influence</em>. Washington, D.C.: The Media Institute.</p>
  <p class="references">Vigón, M. (2010). Covering the news for Spanish-speaking USA. <em>Journal of Spanish Language Media, 3</em>, 24-40.</p>
  <p class="references">Villar, M. E., &amp; Bueno, Y. (2013). Disparate health news frames in English- and Spanish-language newspapers in two U.S. Cities. <em>Howard Journal of Communications, 24</em>(1), 57-70.</p>
  <p class="references">Villar, M. E. &amp; Pinto, J. (2013). Coverage of climate change in leading U.S. Spanish-language newspapers. <em>Journal of Spanish Language Media, 6</em>, 42-60.</p>
  <p class="references">Voakes, P. (1997). Social influences on journalists’ decision making in ethical situations. <em>Journal of Mass Media Ethics, 12</em>(1), 18-35.</p>
  <p class="references">Weaver, D., Beam, R., Brownlee, B., Voakes, P., &amp; Wilhoit, C. (2007). <em>The American journalist in the 21st Century: U.S. news people at the dawn of a new millennium</em>. Mahwah, NJ: Lawrence Erlbaum Associates.</p>
  <p class="references">Whittaker, M., Segura, G., &amp; Bowler, S. (2005). Racial/ethnic group attitudes toward environmental protection in California: Is “environmentalism” still a white phenomenon? <em>Political Research Quarterly, 58</em>(3), 435-447. </p>
  <p class="references">Wilkins, L. (1993). Between facts and values: Print media coverage of the greenhouse effect, 1987-1990. <em>Public Understanding of Science, 2</em>(1), 71-84.</p>
  <p class="references">Wilson, K. (2000). Drought, debate, and uncertainty: Measuring reporters’ knowledge and ignorance about climate change. <em>Public Understanding of Science, 9</em>(1), 1-13. </p>
  <p class="references">Wilson, K. (2008). Television weathercasters as potentially prominent science communicators. <em>Public Understanding of Science, 17</em>(1), 73-87. </p>
  <p class="references">Wilson, K. (2009). Opportunities and obstacles for television weathercasters to report on climate change. <em>Bulletin of the American Meteorological Society, 90</em>(10), 1457-1465. </p>
  <p class="references">Yang, J. (2004). Constraints on environmental news production in the U.S.: Interviews with American journalists. <em>Journal of International and Area Studies, 11</em>(2), 89-105. </p>
  <p class="references"> Zamith, R., Pinto, J., &amp; Villar, M. E. (2013). Constructing climate change in the Americas: An analysis of news coverage in U.S. and South American newspapers. <em>Science Communication, 35</em>(3), 334–357.</p>
  <p class="references">Zehr, S. (2000). Public representations of scientific uncertainty about global climate change. <em>Public Understanding of Science, 9</em>(2), 85-103.</p>
</section>
<hr />
<section>
  <h2 id="note-line-5">Appendix 1. Interviewees<sup><a href="#note-5">[5]</a></sup></h2>
  <ol>
    <li>MA, a former reporter for the <em>Arizona Daily Star</em>, the <em>Orlando Sentinel</em> and online business editor at a Grupo Reforma newspaper in Guadalajara, Mexico. </li>
    <li>DC, vice president of news for Univision in the United States; former editor in chief of the Colombian national newscasts Noticias Uno, NTC Noticias, and Noticias RCN.</li>
    <li>MG, former executive editor and general manager, <em>El Nuevo Herald</em> in Miami, Florida.</li>
    <li>RP, editorial director of the weekly <em>Qué Pasa-Mi Gente</em> in Charlotte, N.C., with 30 years’ experience working for various outlets, including the Spanish news service EFE, Univision, CBS Telenoticias, ECO-Televisa, Telemundo, Canal de Noticias NBC, and <em>La Opinión</em>.</li>
    <li>DR, writer/columnist at HuffPost Voces, and former executive news editor at <em>El Diario/La Prensa</em>.</li>
    <li>PR, retired executive editor of <em>La Opinión</em> in Los Angeles; former executive editor at <em>El Diario/La Prensa</em>.</li>
    <li>ES, president and editor-in-chief of VOXXI and former U.S. Hispanic editor for EFE News Agency.</li>
    <li>MS, former managing editor of <em>El Diario/La Prensa</em> in New York, and former AP Spanish online supervisor.</li>
    <li>RV, former news director of WSCV-TV (Channel 51, owned and operated by Telemundo) in Miami and assistant news director of WLII-TV (owned and operated by Univision) in Puerto Rico.</li>
    <li>Anonymous respondent</li>
    <li>Anonymous respondent</li>
    <li>LG, Executive News Management &amp; Coaching</li>
  </ol>
</section>
<hr />
<section>
  <h2>Notes</h2>
  <p id="note-1"><sup>1</sup> For the purposes of this study, we use the terms “Latino” and “Hispanic” interchangeably.</p>
  <p id="note-2"><sup>2</sup> See <a href="http://vault.sierraclub.org/ecocentro/survey/2012%20Latinos%20and%20the%20Environment%20Survey_Exec%20Summary_English.pdf" target="_blank">http://vault.sierraclub.org/ecocentro/survey/2012%20Latinos%20and%20the%20Environment%20Survey_Exec%20Summary_English.pdf</a> <a href="#note-line-2">[top]</a></p>
  <p id="note-3"><sup>3</sup> Available <a href="http://stateofthemedia.org/2011/hispanic-media-fairing-better-than-the-mainstream-media/" target="_blank">http://stateofthemedia.org/2011/hispanic-media-fairing-better-than-the-mainstream-media/</a> (last accessed, May 28, 2013). <a href="#note-line-3">[top]</a></p>
  <p id="note-4"><sup>4</sup> See <a href="http://sciencepolicy.colorado.edu/media_coverage/" target="_blank">http://sciencepolicy.colorado.edu/media_coverage/</a> <a href="#note-line-4">[top]</a></p>
  <p id="note-5"><sup>5</sup>  Note that the jobs listed in the appendix were those held at the time of the interview. Some interviewees have moved to different positions since then. <a href="#note-line-5">[top]</a></p>
</section>
