<h1>Social Networks in Spain: Twitter and Facebook During ‘La Crisis’</h1>
<div>
  <p class="volume">
    Volume 8 | August 2015
  </p>
</div>
<section class="authors">
  <h4>Authors</h4>
  <p>
    <strong>María del Carmen García Galera, Ph.D.</strong><br />
    University Rey Juan Carlos, Madrid<br />
    Email: <a href="mailto:carmen.garcia@urjc.es">carmen.garcia@urjc.es</a>
  </p>
  <p>
    <strong>Mercedes del Hoyo Hurtado, Ph.D.</strong><br />
    University Rey Juan Carlos, Madrid<br />
    Email: <a href="mailto:mercedes.hoyo@urjc.es">mercedes.hoyo@urjc.es</a>
  </p>
  <p>
    <strong>Jesús del Olmo Barbero, Ph.D.</strong><br />
    University Rey Juan Carlos, Madrid<br />
    Email: <a href="mailto:jesus.delolmo@urjc.es">jesus.delolmo@urjc.es</a>
  </p>
</section>
<hr />
<section>
  <h2>Abstract</h2>
  <p>This article explores the use of social networks for political participation in contemporary Spanish society. Online social networking and the mobilization of thousands of people require leadership with the ability to respond quickly and make the multiple connections necessary for a purposeful organization to function.  This hypothesis leads us to establish a classification of three key elements to consider when talking about participation through social networks: first, who calls for participation and who participates; second, what purpose is pursued with such participation; and third, how does participation take place. This article focuses on the context of Spain and the role played by Facebook and Twitter, two of the most relevant social networks. It analyzes data gathered in the 2011-2014 period, when economic and social crisis in Spain fostered several civic movements, two of which, M-15 and the Anti-Evictions Platform, will be analyzed in this article. These brief case studies illustrate contemporary political activism and outcomes connected to social networks in Spain.</p>
</section>
<hr />
<section>
  <h2>Introduction and Literature Review</h2>

  <h3>Who Is on Social Networks?</h3>
  <p>The rapid development of mobile phones, tablets and other technological advances have blurred the temporal and spatial barriers that limited individuals, allowing them to access, from anywhere and at any time, information flowing through the net<sup>1</sup>. Research suggests that one out of every two times we access the internet we log on to a social network (Carcar, 2015; García, del Hoyo &amp; Fernández, 2014; Chen, 2011; García &amp; Gértrudix, 2009).  Spanish data documents this trend.  The Observatorio Nacional de las Telecomunicaciones y de la Sociedad de la Información (The National Observatory for Telecommunication and Information Society) reported that 70% of Spanish households had internet access in the first half of 2014 (2014). According to Eurostat (2015), between 2007 and 2013, 66% (six percentage points below the European average) of individuals regularly use the Internet in Spain. </p>
  <p>For its part, the 6th Wave of Observatorio de Redes Sociales 2014 (Observatory for Social Networks 2014), (The Cocktail Analysis, 2014), placed the use of social networks among Spanish internet users at 90%, and the 5th Annual Survey of Social Networks (IAB, 2014) notes that usage increased from 51% in 2009 to 79% in 2013.  While these figures do not completely coincide with each other, they all point to widespread and growing use of internet and social media in Spain.</p>
  <p>Online social networks allow users to create a personal profile, connect with other users, and browse profiles or contacts (Boyd &amp; Ellison, 2007). These profiles allow individuals to have detailed information about other individuals on the network, including interests, musical tastes, life preferences, and an endless amount of past, present, and even future personal information. Users can also communicate with each other through a wide range of tools that include sending private messages, chatting, leaving public comments on users’ walls, and sharing photos, videos, or other content.</p>
  <p>There are differences between the social networks that have emerged in recent years, mainly based on the specificity of their content. Although some figures suggest a slowdown in the growth of the major social networks, penetration numbers are still quite significant: Facebook, present in the vast majority of countries, with daily active users exceeding 600 million, is a network that facilitates the exchange of information on social relationships in real or virtual life across the world (Manzoor, 2016)</p>
  <p>Twitter has 284 million users worldwide, and about 500 million tweets written per day (Manzoor, 2016). Despite being the social network (of the two analyzed) with the most posts, it is not at the forefront in terms of the number of users. One explanation for this could be that the peculiarity of Twitter seems to demand a higher rate of posts than other platforms, and it promotes freshness over preparation.  In Spain, the two main football teams––Real Madrid and Barcelona FC––have the greatest number of followers on Twitter exceeding 13 million in both cases. Pope Francis tops the list of public figures with nearly 8 million followers; Spanish Prime Minister Mariano Rajoy is at a considerable distance, with over 600,000 followers. Between these major figures we find a large number of artists and singers (whose presence represents the leisure aspect of this network).</p>
  <p>Non-governmental organizations also inhabit the virtual environment to launch messages encouraging civic participation. Leading in Spain are Greenpeace, followed by Doctors Without Borders and UNICEF (the latter jumps to first place in terms of the number of followers at a global level, with more than 3.5 million). All of them seek the means that will enable them to take their message to more people, and find social networks to be a useful tool for social mobilization. </p>
  <p>During 2014, photography-based social networks absorbed most of the growth in the number of active users: Instagram, which reflects how a picture is worth a thousand words, grew 25%; Tumblr, 22%; and Pinterest, 7% (Fundación Telefónica, 2015).</p>
  <p>At present, specialists observe a shift from communication through social networks to instant messaging, making it possible for apps like WhatsApp to exceed 450 million users in 2014. In the first five months of 2014 alone, WhatsApp grew by 100 million. India, Russia, Brazil, and Mexico are the places where it has grown the most. In Brazil, it exceeds 45 million users. Spain, one of the places where it is used more actively, already has 25 million users. 700 million photos and over 100 million videos are shared worldwide on a daily basis through WhatsApp (El País, April 22, 2014). </p>
  <p>This quantitative data helps us to map the major social networks and their capacity and ability to attract hundreds of millions of users from around the world in a very short time. No previous means of communication has been able to concentrate so many people in such a “limited” space––a small screen. Therefore, readers should take into account that they are dealing with a situation that is changing precipitously and whose future is, for this very reason, difficult to predict, even for experts.</p>

  <h3>Why Should We Be on Networks?</h3>
  <p>Even if the Uses and Gratifications theory (Katz, Blumler, &amp; Gurevitch, 1974) served as a reference for many years to understand and contextualize how traditional media was used and which gratifications the audience got from it, it seems that the appearance of a medium like the internet––and social networks with it––make it necessary to develop enhanced approaches to understand the uses of these media and the needs they satisfy. LaRose and Eastin (2004) propose that instead of talking about gratifications, the starting point should be the consequences of internet usage expected by users, as these become the factor that will help predict the kind of online activities in which people are likely to participate. That is, if what is expected is meeting new people, this will lead to greater activity to help achieve that goal.</p>
  <p>Research on the role of social networks to date focuses especially on social relationships as a form of participation. Ellison et al (2014) posit, for example, that social networks are a formula to increase the social capital of individuals. The technical process of adding new friends on social networks requires very little effort from users, and once a user has been added, there is no need to take any action in order to keep that contact “alive.”  Nyland, Marvez, and Beck (2007) found that the ability to make new friends, be entertained, maintain social relationships, and organize social events were the main reasons for being in the networks. Similarly, Joinson (2008) identified a number of factors for using Facebook: social connections, sharing identities, photographs, content gratification, social research, and “surfing” networks.  Raacke and Bonds-Raacke (2008) explored Facebook and Myspace and specified that the most common reasons for users to use them were to keep in touch with current and “historical” friends, share photos, make new friends, and find old ones. Urista, Dong, and Day (2009) concluded, based on research conducted among young people through focus group discussions, that the main reasons for being in both communities were curiosity to learn more about others, popularity, and forming new relationships.  Kahne, Lee and Timpany (2011), though they include friendship or social relationships as one of the three predominant forms of online participation, establish another two as more important, political or civic and cultural or leisure.</p>
  <p>At first, online social networks served the purpose of strengthening already formed networks among highly selective student populations in U.S. Ivy League universities, and as such, had a significant impact on their users’ social relationships. Some used the networks to find new friends with similar hobbies or as a means to extend face to face contact with members of their peer group through the virtual world (Park, Kee, &amp;Valenzuela, 2009). However, the effect of the role of social networks in everyday life does not stop there, as its value goes beyond the number of users or beyond the number of interactions per user that take place in a virtual environment. Besides becoming vehicles that facilitate social relationships, networks are becoming necessary contributors for collective social action.</p>
  <p>Based on a review of the literature, conceiving the use of online social networks as a medium focused on social relationships is a rather reductionist way to approach this phenomenon. There are already different scientific approaches on ways to participate in online social networks that go beyond being in contact with a peer group. Information or citizen mobilization are other possibilities of social networks. Ito et al. (2009) have also shown that young people not only use social media as a tool for socialization, but also as a formula to learn and explore the world around them.</p>
  <p>Motivations that lead to the use of online social networks include sociability, entertainment, status-seeking, and information (Park, Kee, &amp; Valenzuela, 2009). Cheung and Lee (2009) refer to a number of informational purposes that lead youth to join virtual communities: to gain self-knowledge through the social interactions promoted by networks; to gain social benefit from contact with others, such as friendship; and finally, to achieve the possibility of social improvement, which refers to the value that social network participants obtain by gaining acceptance and approval of other members, as well as improving their social position within the community because of the contribution of young people to it.  Furthermore, Yang and Brown (2013) discuss the role that social networks play in helping young people adjust to new contexts or personal situations. Teenagers, as a group of the population, participate in Twitter to share information on their practices and work; to share information about their classmates and other students; to ask for help or suggestions on any particular issue or to offer such help or suggestions to anyone; and to participate with comments, among other reasons (Veletsianos, 2012).</p>
</section>
<hr />
<section>
  <h2>Discussion</h2>

  <h3>Participation in Collective Social Actions</h3>
  <p>We now ask what has happened with the political or civic participation outlined by Kahne, Lee, and Timpany (2011). In recent years, in a rapidly changing world, we have witnessed numerous social movements in which citizens have expressed, in more or less numerous ways, their reactions to certain measures. At the end of the first decade of the 21st century, Spain began to experience a recession, a devastating housing bubble, and an economic downturn<sup>2</sup> that led to what many experts define as a “social crisis” (Costas, 2014), all of which has caused an exponential increase in political and social movements.</p>
  <p>Following the recession and economic crisis, a greater number of groups have felt the need to go out and demonstrate for different reasons, and the reactivation of citizens’ critical awareness has progressed in parallel to the increase in the number of social network users. Young people, besides being the most present social group in networks, have been and still are one of the main collective voices involved in mobilizations (as Salvador Allende said in 1972 at the University of Guadalajara, “being young and not being a revolutionary may even be a biological contradiction.”)</p>
  <p>There are also other reasons why young people are often present in, and even lead, many of the social movements of our times. Martínez, Silva and Hernández (2010) see that youth participation lies in solidarity and empathy of the youngest with those who suffer from injustice, lack of human rights, and lack of real power.  City of Madrid figures document 10,831 demonstrations held in between January 2012 and August 2014. This is just a sample of the number of events, meetings, demonstrations, actions of solidarity, protests, and other forms of mobilization that have taken place (Ministerio de Hacienda, 2015).</p>
  <p>M-15 is one of the most recognized Spanish social movements of recent years. Originating in Puerta del Sol in Madrid and elsewhere in Spain the week of May 15, 2011, a large majority of the protesters were young people, who form one of the groups most affected by the economic crisis and the lack of opportunities for gainful employment. Protesters participated not only due to political reasons but also because of the social crisis and the consequences of policies on budget cuts and on social rights. For example, between 2007 and 2010, the unemployment rate rose from 8.3% to 20.3%, and continued to grow until 2013, when it peaked. This situation resulted in an increase in inequality and poverty, especially among the most vulnerable sectors of society.</p>
  <figure>
    <h4>M-15 Movement</h4>
    <p>The M-15 movement originated the night of May 15, 2011, at the Puerta del Sol square in Madrid. After a mass demonstration called by a group called Democracia Real Ya (Real Democracy Now) to protest against the distressing economic situation in Spain and the discredit of institutions, some young people decided to extend their protest by installing tents and camping out in that symbolic location of the capital. Despite several attempted ejections, the camping lasted until early August of that year. Demands included changes in the democratic system as well as in the electoral system, access to decent housing, attention to the most vulnerable sectors and sharing the burdens of the economic crisis. However, and despite the fact that their goals still monopolize slogans on demonstrations four years later, lack of internal organization and clear objectives meant that the demonstrations did not achieve immediate results. The movement spread to most Spanish cities and revolutionized the social landscape of the country. At that time, social networks experienced an unexpected boom inspired by the role they had played in the Arab Spring. Within hours of setting up camp, pages on Facebook and Twitter had already emerged to support the movement whose members called themselves the <em>indignados</em> (the indignant ones). As many authors have described, this is the first mobilization that occurred in Spain in which social networks and the internet played a key role. Although Facebook became the network of choice in the Egyptian Youth Revolution (January 2011), launched four months before the events at Puerta del Sol, members of M-15 chose Twitter as the platform to demand political change. The hashtags that had greater impact on Twitter are evidence of the role they played and of what they wanted to symbolize. Thereby, “Twitter appeared in the eyes of #democraciarealya (real democracy now), #juventudsinfuturo (youth without future), #nolesvotes (do not vote for them) and #spanishrevolution as a more efficient tool to achieve their goals” (Martínez, 2013). Although the use of other social media was discarded, Twitter served to denounce the economic situation, make calls for popular demonstrations, and extend the slogans and include proposals to improve the economic situation (Hernández, Roble, &amp; Martínez, 2013). Twitter became a vital tool to support the movement.</p>
  </figure>
  <p>Social justice movements––outside more traditional politics channeled by political players and union representatives––have grown among the youth, who have greater participation in social volunteering and specific local actions than in conventional politics (Martínez, Silva, &amp; Hernández, 2010).</p>
  <p>If the crisis has brought anything, it is the discrediting of political leaders, and with it, mistrust in political mediation (Reina, 2012). The crisis of faith observed in the main political parties and in politics in general has affected almost all Western countries. In Spain, as the book <em>La Urna Rota</em> (Galindo et al, 2014) explains, the arrival of the crisis, which also highlighted cases of corruption among high-ranking officials, encouraged citizens to blame politicians for the crisis. According to the authors, it seems clear that after the spring of the housing bubble comes the winter of discontent. All of these elements, or at least a substantial part, have caused a shift from national politics to local social action. These social movements prioritize targeted actions that seek solutions in a specific region. Activists find it easier and more practical to fight against local injustice than against world hunger. For example, the Anti-Eviction Platform has performed thousands of actions in Spain. It has organized specific local mobilizations over the past few years with the purpose of halting foreclosures of families affected by the mortgage crisis. Geographical proximity appears to be an incentive for youth to participate in collective social actions.</p>
  <figure>
    <h4>Anti-Eviction Platform (AEP)</h4>
    <p>After the collapse of the housing bubble in 2008 and the resulting economic crisis in Spain, many families have been unable to afford their mortgage payments. Consequently, foreclosures and evictions have been increasing exponentially. In 2013 there were more than 67,000 evictions (El País, March 28, 2014). Evictions have become a social problem that has awakened citizen solidarity. In this context, the Anti-Eviction Platform (AEP) was born in Barcelona in 2009, led by Ada Colau, who has since stopped hundreds of evictions and has given advice to those threatened by foreclosure. Over these years, the AEP has gradually opened offices in the main Spanish cities. Its internal organization is carried out through assemblies, and it has an apolitical ideology. AEP’s success in leading social mobilization against evictions under the slogans “Stop desahucios” (“Stop evictions”) and “Sí se puede” (“Yes we can”)<sup>3</sup>, lies in using social networks to extend their actions. AEP members, convened mainly through Facebook and email, protest in front of bank branches in order to ask for the handover of assets in lieu of payment (the handing over of a house to the bank in order to pay for the total debt)<sup>4</sup>, in front of homes to avoid evictions, or in front of politicians’ homes and party headquarters to promote changes in mortgage laws. AEP has prevented at least 1,135 evictions and managed to raise awareness among politicians about the extent of the problem. It uses Twitter to organize so-called virtual <em>escraches</em> (their name for their public demonstrations), which are online protest actions to express rejection of some of the statements made by politicians. Colau, the former spokesperson and founder of the platform, has hundreds of thousands of followers on Twitter, “126,000 piojosos<sup>5</sup>” as the controversial journalist and talk show guest Alfonso Rojo called them on the TV channel Sexta in April 2014.</p>
  </figure>
  <p>Besides the two factors mentioned above–crisis of faith in political actions and geographical proximity to social needs––pragmatism and proxemics as two prevailing attitudes in youth could also be added (González-Anleo, 2005). Youth pragmatism requires institutions to ensure practical results, and proxemics values proximity, closeness, simplicity, and openness of organizations and groups that take care of youth directly or indirectly.</p>
  <p>Nongovernmental organizations (NGOs) and other associations play a crucial role under these circumstances.  These organizations have attempted to attract young people to mobilize in collective social actions aimed towards solidarity and justice. So-called “cause marketing” has made NGOs achieve more active communication––without losing visibility in more traditional media––contributing to making youth participate in such organizations (López &amp; Roig, 2006).</p>
  <p>Proxemics could be one of the main factors leading young people to join collective social actions promoted by NGOs or other associations and organizations. In short, as already mentioned, local and regional actions are usually the most successful. Young people in situations that require their active social participation depend largely on proximity, both in what we understand as geographical proximity and the so-called social proximity (García, del Hoyo, &amp; Fernández, 2014). When it comes to showing an active attitude beyond social networks, young people tend to be more sympathetic to geographically close situations.</p>
  <figure>
    <h4>Let’s save Excalibur</h4>
    <p>The first case of the Ebola infection outside Africa occurred in October 2014 in Spain. A health care assistant, Teresa Romero––who had taken care of two Ebola-stricken missionaries repatriated by the Spanish government and who subsequently died––became infected, and health authorities activated the protocol against Ebola in Spain. The infected assistant and her partner had a dog named Excalibur. When it was made public that Excalibur was to be euthanized in order to avoid contagion, considerable controversy arose over the decision, made by the Comunidad de Madrid and backed by the Juzgado Contencioso-Administrativo No. 2 (administrative court). The decision was justified by the lack of medical knowledge regarding infection between animals and humans afflicted with Ebola. Despite the fact that the assistant’s partner posted a video urging authorities not to euthanize their pet, the court ordered it. Subsequently, a crowd of people gathered in Alcorcón (Madrid), in front of the couple’s house, to try to prevent Excalibur from being taken. Animal welfare groups and the Partido Animalista Contra el Maltrato Animal (Animal Rights Party Against Animal Abuse) mobilized, using social networks with the #SalvemosaExcalibur (Let’s save Excalibur) hashtag. Although the dog’s sacrifice could not be avoided, this initiative was supported by over 150,000 followers on Facebook and became the first trending topic on Twitter on the day of his death (August 10, 2014). Furthermore, many people initiated and supported several initiatives through the website <a href="http://www.change.org">www.change.org</a>. While thousands of people had been killed by the disease in Africa, and no Ebola-related social movement had taken place in Spain, this unusual mobilization occurred in order to save an animal, with hundreds of people taking to the streets in order to demonstrate in front of Teresa Romero’s home.</p>
  </figure>
  <p>Furthermore, the influence of peers on youth tends to be high (Moreira, Sánchez, &amp; Mirón, 2010). Their external image and their sense of belonging to a particular group can lead to participation in certain movements (Hornsey &amp; Jetten, 2004). The existence of opinion leaders who reinforce their status by participating in social networks are a mobilizing factor that should be taken into account as well (Morris &amp; Staggenborg, 2004). In particular, the influence of the mobilization for participation should be highlighted. Generally, organizers of collective social action employ every possible tool to mobilize the highest number of people. As has already been stated, social networks not only allow young people to be informed about these actions but also to actively participate. New information and communication technologies and social networks have made this task easier (García &amp; del Hoyo, 2013).</p>

  <h3>When Participation Remains in the Network</h3>
  <p>Many movements and social participation fronts have had their online version, although social networks have not always been their driving force. As seen in M-15, young people are often the main protagonists of some of these citizen movements, since they are also the main users of the internet and all of the information and communication technology (Jenkins, 2016).  Therefore, the question is: What are the motives that inspire them to participate in any type of mobilization?</p>
  <p>At first, a distinction can be made between two types of participation: the one that is only expressed in virtual networks and the one that is expressed in real life. While participation through social networks and new information technologies only involves, at first, armchair activism or clickactivism (García &amp; del Hoyo, 2013), active offline mobilization means a far greater commitment than the one practiced from the solitude of the computer or mobile device.  Answers to the mystery about factors that cause mobilization through social networks can be found in their immediacy and interactivity (García, del Hoyo, &amp; Fernández, 2014). These two factors help understand the attraction of social networks and how the possibilities that information and communication technologies offer have generated a change in communication paradigms. This so-called revolution has expanded opportunities to actively participate in social movements. Some studies suggest that youth believe that networks have almost unlimited capabilities (e.g., Bescansa &amp; Jerez, 2012) so that they feel that communication skills have been extended by new online tools. New forms of organization and decision-making have been developed as a result of the better and easier communications made possible by the internet (López &amp; Roig, 2006). These developments theoretically suggest that an increasing number of young people will mobilize to participate in events or demonstrations regulated by the “We-intention” concept (Cheung, Chiu, &amp; Lee, 2011) used by philosophers (Bratman, 1997; Tuomela, 1995) prior to the existence of digital media. The concept expresses that “we together can achieve X,” in which X represents a joint action. While the “I-intention” is explained on the basis of individual reasons to take a given action, the “We-intention” can be explained when individuals see themselves a part of a social representation when participating in group action (Bagozzi &amp; Lee, 2002). “We-intention” exists when individuals believe not only that they can be a part of a joint action, but also that they, along with other participants, can carry out this action and are likely to succeed.</p>
  <figure>
    <h4>Eviction of Juana Vacas Pancorbo</h4>
    <p>Juana Vacas Pancorbo, known as Juani, a 74-year-old widow, is the mother of a woman who was murdered by her former husband in 2011 in a case of domestic violence. A few months after the murder, when Juani accepted the inheritance from her daughter, she unknowingly took on numerous debts that the ex-husband and murderer had contracted in previous years. The bank notified Juani of the mortgage foreclosure of her daughter’s flat in order to pay off mortgage debts. After great public pressure through <a href="http://www.change.org">www.change.org</a>, which gathered 175,000 signatures, the court from Jaen annulled the acceptance of inheritance and recognized that Juani was not fully informed about its consequences. Eventually, the foreclosure was also annulled. The case of “The legacy of the murderer”––as the <em>Diario Vasco</em> titled it in November 2012––generated a support campaign across many types of media. On this occasion, social mobilization was organized through Facebook, with the profile “Todos con Juana” (Everyone with Juana) and through Twitter with the @todosconJuana profile and #todosconJuana hashtag.</p>
  </figure>
  <p>Social networks are a starting point for mobilization of campaigns such as Greenpeace’s “Save the Arctic.” More than 6 million people have signed online for this cause. Social networking has changed the traditional methods of getting support and multiplied their effects.  Social networks’ multiplicative effects probably contribute to the success of organizations like change.org in terms of the number of followers of their causes in Spain. As Greenpeace advertises on its website, it is the “world’s platform for change.” Greenpeace has become a reference platform for active social mobilization offline, getting thousands of signatures for their causes.</p>
  <p>Social networks are visible spaces to an undetermined amount of users in which many young people try to weave their social relationships. But there is the possibility that so-called online activism becomes a way to “save face” and does not involve a real commitment. Basic online participation is so simple that it is possible for a user to publish or share his or her compliance with collective social actions in response to social pressure or in order to achieve greater approbation from his or her peers. The possibility of anonymity that the internet and social networks offer could also encourage a greater involvement of users and encourage online participation (Colás, González, &amp; de Pablos, 2013). Anonymity allows individuals to support causes, especially when it comes to situations or reasons for mobilization that could “point out” the individual as a supporter of the cause. This could be a motivation for youth, as their social actions are severely influenced by their peer group.  Visual anonymity allows someone to deliberately play with a polysemic me, behaving like different characters and adjusting the level of commitment that the subject assumes in the encounter with the other (Cáceres, Ruiz, &amp; Brändle, 2009).  Research also shows that almost 70% of young respondents use other identities on the internet (Cáceres, Ruiz, &amp; Brändle, 2009).  Therefore, anonymity can be a determining factor for youth participation in social networks.</p>
  <figure>
    <h4>Tragedy in Madrid-Arena</h4>
    <p>On Halloween night 2012, five young women lost their lives at a party in the Madrid Arena. The crush of people––a much higher amount than the capacity for the venue––and the nefarious intervention and negligence of organizers, were two major factors responsible for the death of the young women, aged 17 to 20, in an avalanche that trapped dozens of young people. A few weeks later, one of the mothers of the deceased initiated a petition through the website change.org, asking for a change in the law regulating shows from the Comunidad de Madrid in order to guarantee greater safety and control over such massive celebrations. After getting over 128,000 signatures, the president of the Comunidad de Madrid, Ignacio González, promised to change the law. This online initiative has totaled more than 428,000 signatures from people endorsing this petition.</p>
  </figure>
</section>
<hr />
<section>
  <h2>Conclusion</h2>

  <p>This overview of recent activism generated by social networks in Spain provides a number of findings. First, the accessibility that the Internet offers to remote causes facilitates mobilization of people, but curiously, networks have not caused the abandonment of local and proximate causes.  In fact, online contributes to the vibrancy of local and regional activism.  Second, the crisis in Spain has brought political disenchantment and criticism of the ruling classes, but it has aroused at the same time a renewed interest in public and social commitment. Volunteering and other forms of citizen activism find in online social networks the most appropriate means for its extension and development. Third, simplicity and immediacy for participation provided by social networks facilitate online commitment, but these two features also facilitate the conversion of online commitment into offline engagement, so that users participate online and the “mobilizing” agent—such as an NGO––reaps the benefits (support, money, etc.) offline, to accomplish or help its social justice goals and potentially transform the reality that transcends the organization and in which it is immersed.  As such social networks take advantage of space-time compression facilitated by digital technology to bring people together, especially but not exclusively youth, toward social and political goals.  As with previous media, it is important to remember that people and leadership are the agents for technology-facilitated activism.</p>
</section>
<section>
  <h2>References</h2>
  <p class="references">Allende, Salvador.  (December 2, 1972). University of Guadalajara. Retrieved October 2014 from: <a href="http://www.abacq.net/imagineria/discur5.htm">http://www.abacq.net/imagineria/discur5.htm</a></p>
  <p class="references">Bagozzi, R. P., &amp; Lee, K. H. (2002). Multiple routes for social influence. The role of compliance, internalization and social identity. <em>Social Psychology Quarterly</em>, 65(3), 226–247.</p>
  <p class="references">Bescansa, C., &amp; Jerez, A. (2012). La red: ¿nueva herramienta o nuevo escenario para la participación política? <em>XV Encuentro de Latinoamericanistas: América Latina: La autonomía de una región</em>. Madrid: Universidad Complutense de Madrid.</p>
  <p class="references">Boyd, D. &amp; Ellison, N. (2007) Social Network Sites: Definition, History, and Scholarship. <em>Journal of Computer-Mediated Communication</em>, 13(1), 210–230.</p>
  <p class="references">Bratman, M. E. (1997). I intend that We J. In G. Holmstrom-Hintikka, &amp; R. Tuomela (Eds.), <em>Contemporary action theory</em>, 49-63. The Netherlands:  Kluwer, Dordrecht.</p>
  <p class="references">Cáceres, Mª D., Ruíz San Román, J. A., and Brändle, G. (2009) Comunicación interpersonal y vida cotidiana. La presentación de la identidad de los jóvenes en internet. <em>CIC (Cuadernos de Información y Comunicación)</em>, 14, 213-231.</p>
  <p class="references">Carcar, J.E. (2015). Las redes y los movimientos sociales ¿Una acción colectiva o marketing viral? <em>Icono14</em>, 13(1).</p>
  <p class="references">Chen, G.M. (2011) Tweet this: A uses and gratifications perspective on how active Twitter use gratifies a need to connect with others. <em>Computers in Human Behavior</em>, 27, 755-762.</p>
  <p class="references">Cheung, C. M. K., Chiu, P-Y &amp; Lee, M. (2011). Online social networks: Why do students use Facebook? <em>Computers in Human Behavior</em>, 27, 1337–1343.</p>
  <p class="references">Cheung, C. M. K., &amp; Lee, M. K. O. (2009). Understanding the sustainability of a virtual community: Model development and empirical test. <em>Journal of Information Science</em>, 35(3), 279–298</p>
  <p class="references">Colás, P., González, T., &amp; de Pablos, J. (2013). Juventud y redes sociales: Motivaciones y usos preferentes. <em>Comunicar</em>, 20(40).</p>
  <p class="references">Costas, A. (2014). El riesgo, ahora, es la crisis social. <em>El País</em>. Retrieved February 2, 2014, from <a href="http://economia.elpais.com/economia/2014/01/31/actualidad/1391167456_902934.html">http://economia.elpais.com/economia/2014/01/31/actualidad/1391167456_902934.html</a></p>
  <p class="references">Dahlgren, P. (2011) Jóvenes y participación política. Los medios en la red y la cultura cívica. <em>TELOS (Cuadernos de Comunicación e Innovación)</em>. 89, 1-11</p>
  <p class="references">El País (March 28, 2014). El Poder Judicial revela que en 2013 hubo una media de 184 desahucios al día. Retrieved from <a href="http://politica.elpais.com/politica/2014/03/28/actualidad/1395997876_165402.html">http://politica.elpais.com/politica/2014/03/28/actualidad/1395997876_165402.html</a></p>
  <p class="references">El País (April 22, 2014). WhatsApp supera 500 millones de usuarios.  Retrieved from  <a href="http://tecnologia.elpais.com/tecnologia/2014/04/22/actualidad/1398191305_540693.html">http://tecnologia.elpais.com/tecnologia/2014/04/22/actualidad/1398191305_540693.html</a>.</p>
  <p class="references">Ellison, N., Vitak, J., Gray, R., and Lampe, C. (2014). Cultivating Social Resources on Social Network Sites: Facebook Relationship Maintenance Behaviors and Their Role in Social Capital Processes. <em>Journal of Computer-Mediated Communication</em> 19(4), 855-870.</p>
  <p class="references">Eurostat (2015). Being young in Europe today - digital world. Retrieved from  <a href="http://ec.europa.eu/eurostat/statistics-explained/index.php/Being_young_in_Europe_today_-_digital_world">http://ec.europa.eu/eurostat/statistics-explained/index.php/Being_young_in_Europe_today_-_digital_world</a></p>
  <p class="references">Fundación Telefónica (2015). <em>La Sociedad de la Información en España 2014</em>. Barcelona: Ariel.</p>
  <p class="references">Galindo, J., Llaneras, K., Medina, O., San Miguel, J., Simón, P., and Senserrich, R. (2014) <em>La urna rota. La crisis política e institucional del empleo español</em>. Madrid: Editorial Debate.</p>
  <p class="references">García, F., and Gértrudix, M. (2009). El Mare Nostrum Digital: Mito, ideología y realidad de un imaginario sociotécnico. <em>Icono14</em>, 7(1).</p>
  <p class="references">García, M.C., and del Hoyo, M. (2013) Redes sociales, un medio para la movilización juvenil. ZER magazine, 18 (34). ISSN: 1137-1102. 111-125</p>
  <p class="references">García, M.C., del Hoyo, M., and Fernández, C. (2014). Jóvenes comprometidos en la Red: El papel de las redes sociales en la participación social activa. <em>Comunicar</em>, 22(43).</p>
  <p class="references">González-Anleo, J. (2005) Jóvenes y valores cívico-políticos. <em>Revista Educación y Futuro</em>, 13, 59-70.</p>
  <p class="references">Hernández, E., Robles, M.C., and Martínez, J. B. (2013). Jóvenes interactivos y culturas cívicas: Sentido educativo, mediático y político del 15M. <em>Comunicar</em>, 20(40),  59-67</p>
  <p class="references">Hornsey, M.J., and Jetten, J. (2004). The Individual Within the Group: Balancing the Need to Belong with the Need to Be Different. Personality and Social Psychology Review, 8(3), 248-264</p>
  <p class="references">IAB (2014). <em>Spain, V Estudio Anual de Redes Sociales</em>. Retrieved from <a href="http://www.iabspain.net/wp-content/uploads/downloads/2014/04/V-Estudio-Anual-de-Redes-Sociales-versi%C3%B3n-reducida.pdf">http://www.iabspain.net/wp-content/uploads/downloads/2014/04/V-Estudio-Anual-de-Redes-Sociales-versi%C3%B3n-reducida.pdf</a></p>
  <p class="references"> Ito, M., Horst, H. A., Bittanti, M., Boyd, D., Herr-Stephenson, B., Lange, P.G., Mahendran, D., Martínez, K., Pascoe, C., Perkel, D., Robinson, L., Sims, C., &amp; Tripp, L. (2009). <em>Living and learning, with new media: Summary of findings from the Digital Youth Project</em>. Cambridge, MA: MIT Press.</p>
  <p class="references">Jenkins, H. (2016). Youth voice, media and political engagement. In  H. Jenkins, S. Shresthova, L. Gamber-Thompson, N., Kligler-Vilenchik, &amp; A. Zimmerman, <em>By Any Media Necessary: The New Youth Activism</em>, pp. 1-60. New York, NY: New York University Press</p>
  <p class="references">Joinson, A. N. (2008). 'Looking at', 'looking up' or 'keeping up with' people? Motives and uses of Facebook. Paper presented at the CHI 2008 - Online Social Networks, Florence, Italy.</p>
  <p class="references">Kahne, J., Lee, N., &amp; Timpany, J. (2011). <em>The Civic and Political Significance of Online Participatory Cultures and Youth Transitioning to Adulthood</em>. San Francisco: DML Central Working Papers</p>
  <p class="references">Katz, E., Blumler, J. G., &amp; Gurevitch, M. (1974). Utilization of mass communication by the individual. In J. G. Blumler &amp; E. Katz (Eds.), <em>The uses of mass communications: Current perspectives on gratifications research</em>, 19-32. Beverly Hills, Calif.: Sage.</p>
  <p class="references">LaRose, R., &amp; Eastin, M. (2004). A social cognitive explanation of Internet uses and gratifications: Toward a new theory of media attendance. <em>Journal of Broadcasting and Electronic Media</em>, 48(3), 358–378</p>
  <p class="references">López, S. &amp; Roig, G. (2006). La globalización de los movimientos sociales: los medios alternativos telemáticos. Documentación Social: <em>Revista de Estudios Sociales y Sociología Aplicada</em>. 140, 129-150.</p>
  <p class="references">Manzoor, A. (2016). Social Media for Promoting Grassroots Political Movements and Social Change. In B. Guzzetti &amp; M. Lesley (Eds.), <em>Handbook of Research on the Societal Impact of Digital Media</em>,609-637. Hershey, Pensilv: Igi Global Series</p>
  <p class="references">Martínez, C. (2013) #15M. Una protesta coordinada a través de Twitter. Online, Suite101. Retrieved from <a href="http://suite101.net/article/15m-una-protesta-coordinada-a-traves-de-twitter-a59920#.VMPnv2Y5BaQ">http://suite101.net/article/15m-una-protesta-coordinada-a-traves-de-twitter-a59920#.VMPnv2Y5BaQ</a></p>
  <p class="references">Martínez, M. L., Silva, C. &amp; Hernández, A. (2010) ¿En qué ciudadanía creen los jóvenes? Creencias, aspiraciones de ciudadanía y motivaciones para la participación sociopolítica. <em>PSYKHE</em>, 19(2), 25-37.</p>
  <p class="references">Ministerio de Hacienda (2015). Cifuentes cumple tres años al frente de la Delegación del Gobierno con un descenso de la delincuencia del 4% en 2014. Retrieved on October 2014, from <a href="http://www.seap.minhap.gob.es/en/ministerio/delegaciones_gobierno/delegaciones/madrid/actualidad/notas_de_prensa/notas/2015/01/2015_01_16.html">http://www.seap.minhap.gob.es/en/ministerio/delegaciones_gobierno/delegaciones/madrid/actualidad/notas_de_prensa/notas/2015/01/2015_01_16.html</a>)</p>
  <p class="references">Moreira, V., Sánchez, A., &amp; Mirón, L. (2010). El grupo de amigos en la adolescencia. Relación entre afecto, conflicto y conducta desviada. <em>Boletín de Psicología</em>, 100, 7-21.</p>
  <p class="references">Morris, A.D., &amp; Staggenborg, S. (2004). Leadership in social movements. In <em>The Blackwell Companion to Social Movements</em>, D. A. Snow, S.A. Soule, &amp; H. Kriesi, (Eds.). Oxford, UK: Blackwell Publishing.</p>
  <p class="references">Nyland, R., Marvez, R., &amp; Beck, J. (2007).  Myspace: Social networking or social isolation. AEJMC Midwinter Conference.</p>
  <p class="references">Observatorio Nacional de las Telecomunicaciones y de la Sociedad de la Información en España. (2014).  XLIII Oleada del Panel Hogares. Las TIC en los hogares españoles. Retrieved on June 13, 2016, from <a href="http://www.ontsi.red.es/ontsi/es/estudios-informes/xliii-oleada-del-panel-hogares-%E2%80%9Clas-tic-en-los-hogares-espa%C3%B1oles%E2%80%9D-1t2014">http://www.ontsi.red.es/ontsi/es/estudios-informes/xliii-oleada-del-panel-hogares-%E2%80%9Clas-tic-en-los-hogares-espa%C3%B1oles%E2%80%9D-1t2014</a></p>
  <p class="references">Park, N., Kee, K., &amp; Valenzuela, S. (2009). Being Immersed in Social Networking Environment: Facebook Groups, Uses and Gratifications, and Social Outcomes. <em>Cyberpsychology &amp; Behavior</em>, 12(6).</p>
  <p class="references">Raacke, J., &amp; Bonds-Raacke, J. (2008). Myspace and Facebook: applying the uses and gratifications theory to exploring friend-networking sites. <em>Cyberpsychology Behavior</em>, 11(2), 169-177.</p>
  <p class="references">Reina, A. (2012). De la primavera árabe a los indignados. ¿Hacia dónde van las movilizaciones sociales? <em>Reconciliando Mundos</em>, October.</p>
  <p class="references">Romero, A. (2011). Las redes sociales y el 15-M en España. <em>Telos</em>, November-December, 1-6.</p>
  <p class="references">The Cocktail Analysis (2014). VI Ola del Observatorio de Redes Sociales. Retrieved October 2014 from <a href="http://tcanalysis.com/blog/posts/the-cocktail-analysis-y-arena-publican-la-vi-ola-del-observatorio-de-redes-sociales">http://tcanalysis.com/blog/posts/the-cocktail-analysis-y-arena-publican-la-vi-ola-del-observatorio-de-redes-sociales</a></p>
  <p class="references">Tuomela, R. (1995). <em>The importance of us: A philosophy study of basic social notions</em>. Stanford, Calif.: Stanford University Press.</p>
  <p class="references">Urista, M. A., Dong, Q., &amp; Day, K. D. (2009). Explaining why young adults use Myspace and Facebook through Uses and Gratifications theory. <em>Human Communication</em>, 12(2), 215-229.</p>
  <p class="references">Veletsianos, G. (2012). Higher education scholars’ participation and practices on Twitter. <em>Journal of Computer Assisted Learning</em>, 28(4), 336-349.</p>
  <p class="references">Yang, C. C. &amp; Brown, B. B. (2013). Motives for using Facebook, patterns of Facebook activities, and late adolescents’ social adjustment to college. <em>Journal of Youth and Adolescence</em>, 42(3), 403-416.</p>
</section>
<hr />
<section>
  <h2>Notes</h2>
  <p><sup>1</sup>This is the case in Spain, though we acknowledge that there are still pockets and even entire countries—such as Myanmar, North Korea, and Cuba—whose population do not have access to the internet.</p>
  <p><sup>2</sup>Unemployment reaches 26.9% in 2013, banks cut credit to businesses and individuals, and, as of 2012, government deficit exceeds 100 billion euros. The EU urged Spain to take action in order to avoid a bailout like Greece’s. </p>
  <p><sup>3</sup>This slogan is borrowed from the United States Farm Workers social movement for living wages and safe harvesting conditions.</p>
  <p><sup>4</sup>In case of defaulting on the mortgage, the current Spanish law allows banks to be able to own the property and also to force the owner to keep paying the mortgage (even when the property no longer belongs to the owner but to the bank and the owner doesn’t have access to it). The aim of the platform was to fight for a law that would force banks to eliminate the mortgage once banks own the property.</p>
  <p><sup>5</sup>Meaning literally, “lice-infested people” but often used in Spanish as “scum” is used in English.</p>
</section>
