<p class="volume">
  Volume 9 | October 2016
</p>
<h6><a href="http://www.internationalhispanicmedia.org/wp-content/uploads/2016/11/IJHM_Vol9-Portrayl.pdf">[ Download PDF ]</a></h6>
<section class="authors">
  <h4>Authors</h4>
  <p>
    <strong>Jessica Retis, Ph.D.</strong><br />
    California State University Northridge<br />
    <a href="mailto:jessica.retis@gmail.com">jessica.retis@gmail.com</a>
  </p>
</section>
<hr />
<section>
  <h2>Abstract</h2>
  <p>This article explores the way that Latin American immigration at the turn of the 21st century was framed in mainstream media in Spain. The study reviews hundreds of news stories printed in three national newspapers, El País, El Mundo, and ABC, during 2001. Analyzing how major media presented the “Latinoamericanization” of non-European immigration in Spain, this article examines the 2001 political debate on immigration in relation to Ecuadoreans and Colombians. Through a comparative analysis, this study shows how news media discourse tends to decontextualize the transnational context of capital and population flows between Spain and Latin America, and how it influences public opinion. Moreover, this study shows the prevalence of a set of metaphors related to the emotions of fear and compassion in the news coverage of Colombian and Ecuadorean immigrants.</p>
  <p>
    <strong>Keywords:</strong> Colombian, discourse, Ecuadorean, immigration, journalism, media, news, Spain
  </p>
</section>
<hr />
<section>
  <h2>Introduction and Literature Review</h2>
  <p>Immigration has become a highly politicized issue, often perceived in a negative way despite the clear need for the diversification of modern societies and economies: “In spite of the revolution in communications, there are many people who have inadequate information on the magnitude, the implications, and the socioeconomic context of migration” (IOM, International Organization for Migration, 2011, p. 8). In its sixth report, the International Organization for Migration argued that it is essential to have well-informed and clear debates in the public and political arenas. The risk of maintaining the status quo is threefold: 1) Continued politicized debate will only serve to foster sectarian agendas rather than promote broader national, regional, and international interests, 2) Negative attitudes and reactive approaches are likely to continue to dominate over positive attitudes and proactive approaches, 3) Both integration and reintegration efforts will inevitably be undermined unless migrants themselves become active participants, rather than the objects, in the migration debate. (IOM, 2011, pp. 8-9).</p>
  <p>Until the turn of the century, Spaniards tended to collectively imagine Moroccans and North Africans as the face of non-European immigrants (Martínez, 2003). Although statistics showed a growing presence of Latin Americans, this phenomenon did not surface in the political debate and media discourse until 2001. During those years, several researchers analyzed how immigration in Spain was a collectively conceived social phenomenon resulting from symbolic constructions, and how news stories about non-European immigrants tended to be presented out of context, with a rather local scope and without delving into the phenomenon’s complexity (Bañón, 2002; Granados, 2002; Santamaría, 2002). </p>
  <p>Trends in the news media portrayal of Latin American immigrants at the turn of the century developed in a pattern similar to those in other countries in the global North that are receiving immigrants from the global South. As critical studies have argued, there is an evident correspondence between media’s and audience’s agendas. Research has exposed that media tend to convey stereotypical portrayals of immigrants/minorities and to emphasize the problems and threats in news coverage (Cottle, 2000; Hegde, 2016; Van Dijk, 2000). Public opinion on Latin American immigration has been based mainly on information delivered through a media-distorted glass (Retis, 2006). </p>

  <h3>Public discourse on immigrants and immigration</h3>
  <p>When analyzing mainstream media in Spain, critical analysts have argued that media discourse is the socio-cognitive drive of social thought and verbal communication, and above all, that the mainstream press offers a formally structured internal coherence and vision of the world (Imbert, 1993). Comparative analysis of news reporting on ethnic minorities and immigration have demonstrated that mainstream media tend to collectively construct otherness as social problem. Rodrigo and Martínez (1997) examined the way the news related to ethnic minorities was treated in Spain (<em>ABC</em> and <em>El País</em>), France (<em>Le Figaro</em> and <em>Le Monde</em>), Italy (<em>Corriere della Sera</em> and <em>La Repubblica</em>), and UK (<em>The Times</em> and <em>The Guardian</em>). The content analysis found that the European elite press associates the information about ethnic minorities mainly with conflicts, whereas cultural attributes are forgotten. When comparing conservative versus progressive media, they found that there were more similarities than differences in the depiction of minorities in Europe. Benson and Saguy (2005) compared news media reporting in the US (<em>The New York Times</em>, <em>Los Angeles Times</em>, <em>ABC</em>, <em>NBC</em>, and <em>CBS</em>) and France (<em>Le Monde</em>, <em>Le Figaro</em>, <em>Libération</em>, France 2, and TF 1). They found that when French media raised concerns about immigrants, they discussed immigrants’ failure to do enough to “fit in” with the national community. Conversely, the dominance of market-based cultural repertoires in the United States led the US news media to emphasize the fiscal costs created by immigration for extra social services and education (Benson &amp; Saguy, 2005, p. 244). In their analysis, Benson and Saguy categorized frames and news event types in US and French immigration stories as social problems for immigrants, cultural problems for immigrants, racial/ethnic discrimination, cultural problems created by immigrants, fiscal problems created by immigrants, positive cultural diversity, routine identical (such as a newspaper-sponsored poll or investigative journalism, in which journalists are both the news “promoters” and news “assemblers”), routine habitual (stories, in which government, business or academic elites with “habitual” and easy access to journalists promote media coverage of an event), and scandals.</p>
  <p>Santa Ana (2002) analyzed the public discourse metaphors depicting Latinos in the United States. In his long-term and in-depth study, he found that the metaphors constituting everyday understandings of citizen, immigrant, language, racism, and English are linked together by way of the most prevalent metaphors of the concept “nation.” The main metaphors he analyzed were <em>Nation as a Body</em>, <em>Nation as a House</em>, and the extension of <em>Nation as a City</em>: “…these metaphors serve as overarching ‘umbrella’ metaphors, providing semantic source domains for a wide range of political metaphorization. By way of illustration, immigrant as invader and racism as a disease are both affiliated with these umbrella metaphors of the nation” (Santa Ana, 2002, p. 272). Santa Ana adds that through the metaphor of <em>Immigrant as Animal</em>, Latino immigrants continue to be dehumanized in contemporary discourse, which justifies inequity and discrimination against them (Santa Ana, 1999, 2002).</p>
  <p>Discourse analyses of how media depict young immigrants have demonstrated similar trends in news coverage. Jefferies (2009) explored the major media output on questions of access to higher education for undocumented immigrant and found the prevalence of a set of frames related to meritocratic ideologies. He argued that meritocracy as an ideology of inequality served economically established populations to justify the segregation of new waves of immigration (Jefferies, 2009). Retis and García (2010; García &amp; Retis, 2011) found that young immigrants tend not to appear in European mainstream media unless they are involved in an event related to social conflict. The comparative analysis showed how Spanish and French media framed these events by utilizing affective strategies of compassion and fear, fragmenting reality, and reconstructing collective emotions in media discourses. Young non-European immigrants suffered from double vulnerability since, on the one hand, they had little or no access to the public discourse, and on the other hand, when they finally appeared in news media coverage, they were depicted in terms of social conflict or moral panics, a classic finding of symbolic annihilation (García &amp; Retis, 2011; Retis &amp; García, 2010).</p>

  <h3>Media Construction of Emotions</h3>
  <p>In Spain, critical researchers examined how TV newscasts utilized affective mobilization strategies when covering stories related to non-European immigrants (Rizo, 2001), how Spanish TV news turned into an industry of induced emotions, and how news audiences participated in this activity, which is not only cognitive and rational but emotional (Rey Morato, 1998). Researchers have found that the study of emotional communication must analyze the media as constructors and transmitters of emotions (Rodrigo, 1992, 1997).  Although traditional perspectives tend to attribute to the print media the sole function of “making readers know” (<em>hacer saber</em>) the news, it is crucial to understand that, in reality, what is involved is an “impure genre” that, as well as informing, entertains, and what is doubly relevant, “makes readers feel” (<em>hacer sentir</em>) the news through linguistic construction of emotions (Harré 1986; Rizo, 2001; Rodrigo, 1992). In this context, the discourse on immigration tends to induce mainly two types of emotions: <em>fear</em>, depicting immigrants as a danger that triggers emotional reactions of fear; and <em>compassion</em>, as it also tends to focus on their “pitiful” situation––their poverty––all of which triggers emotional reactions of compassion (Rizo, 2001, 2011).</p>

  <h3>Immigrants as Victims or as a Threat</h3>
  <p>In his comparative analysis of US and French immigration news, Benson (2013) found three main frames. First, in the <em>Immigrants as Victims</em> scenario, the “global economy” frame emphasizes problems of global poverty, underdevelopment, and inequality, of which the immigration from global South to North is only one symptom. The “humanitarian” frame highlights the hardships of immigrants, while the “racism/xenophobia” frame emphasizes systematic discrimination. Second, the <em>Immigrants as Heroes</em> scenario includes “cultural diversity,” which brings attention to immigration’s positive effects on society; “integration,” which recognizes immigrants’ efforts in adaptation; and the “good worker,” which highlights how immigrants do the work that others won’t do. The third scenario, <em>Immigrants or Immigration as a Threat</em>, includes the “jobs” element, which accuses immigrants of taking jobs from natives or lowering wages; the “public order” aspect, which emphasizes any law-breaking event; the “fiscal” element, which portrays the concern on taxpayers and the cost of services; and “national cohesion,” which portrays cultural differences as a threat to national unity (Benson, 2013, pp. 6-7).  </p>
  <p>This article examines how Spanish news media incorporated these frames when depicting Latin American immigrants at the turn of the century, when immigration reforms where a focal point of the debate between the main political parties. It focuses on three national print news organizations because they were echoing the political debate, turning news media into a virtual scenario for these confrontations.</p>

  <h3>The “Latinoamericanization” of Non-European Immigration in Spain</h3>
  <p id="note-line-1">The evolution of Latin American immigration to Spain has been conditioned by structural and cyclical factors on both sides of the Atlantic (Colectivo Ioé, 2003a, 2003b; Pellegrino, 2004). Emigrations to countries outside the region increased in South America, particularly since the second half of the last century. Demographers identify these as the last links of previous population movements such as crossing national borders, and before that, displacements from rural to urban areas caused by the forces of early industrialization processes that led to the rapid growth of cities to the detriment of the agricultural sector (Pellegrino, 2003). In the context of international migration, although the United States has been the main destination, Spain became more important during the 1990s. During those years, Spain transitioned from sending immigrants to North Europe to receiving immigrants, and was categorized as a latecomer<sup><a href="#note-1">[1]</a></sup> and heir of the “European unease over immigration” (Arango, 2000, 2002). Some researchers identified Latin Americans as the “preferred of the 21st century” to explain that this migratory growth was due, among other factors, to the political will to favor them over other non-European groups, and to social preferences both in public opinion and in the business sector (Izquierdo, López, &amp; Martínez, 2002).<sup><a href="#note-2">[2]</a></sup> Other authors argued that this “preferential” situation was contingent on socioeconomic and administrative conditions when incorporated into the analysis, particularly in terms of labor insecurity and precariousness (Colectivo Ioé, 2003a, 2003b; Domingo, 2005).</p>
  <p>By incorporating a comprehensive understanding of the contexts of reception as well as the socio-cultural factors and the collective strategies that immigrants develop, we can better examine the immigration processes of Latin Americans in Spain (Herranz, 1998; Retis, 2006). Transnational perspectives give us the opportunity of exploring beyond push/pull factors of international migration (Levitt &amp; Glick Schiller, 2004; Smith &amp; Guarnizo, 1998). A review of the main processes on both sides of the Atlantic helps us understand how population flows occur along with capital flows, but in the opposite direction. </p>
  <p>In the mid-1970s the process of democratization in Spain and its integration into the transnational economy attracted foreign capital, generating economic development that allowed its exit from its semi-periphery condition in Europe. Simultaneously, Spain started attracting immigrant workers. The demand for a new organization of production involved the accelerated expansion of the service sector and the concentration of economic activity in “global cities” (Sassen, 2001) such as Madrid or Barcelona. The demand for new labor created two types of immigration: for highly skilled and technical jobs, and for low-skill jobs in areas such as maintenance, courier services, hospitality, and services in general. This “first reception context” of immigrants coincides with the first flow of Latin Americans, the ones who arrived in Spain for political reasons. Most came from the Southern Cone, mainly from Argentina and Chile, but also from Venezuela. They were basically of urban origin, with a balance in gender composition, education levels higher than the Spaniards’, and with a higher tendency to self-employment than other non-European immigrants. Over time, Spanish workers increased their professional preparation and entered into the professional labor market, leaving other jobs exclusively for immigrants (Colectivo Ioé, 2003a; Herranz, 1998).</p>
  <p>In the late 1980s, the deceleration of the economy in Spain resulted in an increase in unemployment. This is when researchers identify the “second reception context” of immigrants, in which foreign workers are mostly limited to low-skilled jobs, those that native populations reject (Herranz, 1998). Adding to the labor conditions, we must consider new patterns in the Spanish immigration policies. The incorporation of Spain to the European Union (UE) was preceded by the approval of the 7/1985 Law, which brought with it the European unease over immigration (Arango, 2002). The hardening of its application in 1991, with a quota policy and the tightening of border controls, created a much more difficult migratory environment. Until then, it was not essential for Latin Americans to have papers to work informally and accumulate some capital without fear of expulsion. The new visa requirements presented a new set of barriers (Herranz, 1998). The second flow of Latin Americans occurred during this “second reception context” of immigration and was driven by economic reasons.</p>
  <p>In Latin America, critical researchers consider the 1980s as “the lost decade” due to the effects of structural adjustment policies, which raised the numbers of South Americans emigrating out of the region, primarily to the United States. The 1990s began an increase in emigration to Spain. As Figure 2 shows, during the early 1990s, immigrants from the Caribbean and the Andean Region, particularly from the Dominican Republic and Peru, joined those from the Southern Cone. Studies demonstrated that during those years Latin Americans arrived with high levels of education (Aparicio &amp; Giménez, 2003). Their strong geographical concentration in urban areas and their incorporation in services sectors, especially domestic service and care of the elderly and children, led to an initial feminization in the early stages (Oso, 1998).</p>
  <p id="note-line-3">In 1996, the Partido Popular (PP) won the elections and established new immigration policies. It was the beginning of the “Latinoamericanization” of the non-European immigration in Spain. The events in El Ejido<sup><a href="#note-3">[3]</a></sup> influenced the negative perception of Moroccan immigrants, as was evident during the electoral vote for local administrative posts.<sup><a href="#note-4">[4]</a></sup> During those years the most relevant political decisions were the processes of “regularization” and “documentación por arraigo” (temporary residence authorization for social rootedness): Compared with other non-European immigrants, Latin Americans obtained higher rates of acceptance and increased their numbers as legal residents (Izquierdo, López, &amp; Martínez, 2002). Other indicators of the “preferential” position were the speedy process of obtaining Spanish citizenship (proceso de naturalización), a right for Latin Americans after two years of legal residence.<sup><a href="#note-5">[5]</a></sup> During those years, Spaniards favored Latin Americans over other non-European immigrants in public polls (Figure 1). Until the turn of the century, Latin Americans were perceived with more empathy than other non-European groups, a perception that began to decline after their more frequent appearance in news media.</p>
  <figure>
    <h3>Figure 1. Attitudes Toward Immigrants in Spain (1996-2003)</h3>
    [FIGURE 1 GOES HERE]
    <figcaption>Figure 1. Respondents were asked: “On a scale from 0 to 10, how much empathy do you feel for the following groups”? Source: Public Opinion Polls from Centro de Investigaciones Sociológicas, various years.</figcaption>
  </figure>
  <p>During the second half of the 1990s, two concomitant processes occurred. While Latin American countries suffered the effects of an economic and financial crisis, Spain began an economic recovery. Expulsionary migration flows from Latin America and pulling immigration flows in Europe, combined with immigration reforms in the United States–– the main recipient of Latin American flows––resulted in a reconfiguration of Latin American international immigration processes (Retis, 2006). The end of the “Ecuadorean miracle,” the Colombian agricultural and social crisis, and the Argentinean financial crisis known as the <em>corralito</em>, coincided geopolitically with the opening of a niche for non-European immigrant workers in Southern European countries such as Spain, Italy, and Portugal. Latin Americans moved with the flow of foreign international capital, but in the opposite direction: the “golden decade” of Spanish investments in Latin America (Casilda, 2002) was coupled with the international emigration projects of the Latin American middle classes hit by the economic crisis (Retis, 2006)</p>
  <p>At the turn of the century, Latin American immigrants found jobs in different productive sectors. In their settlement process, they began to concentrate in specific areas in Spain. Argentineans started working in service sectors in urban areas of Madrid, Catalonia, Galicia, and the Balearic and Canary Islands. Colombians started working in the areas of child and elderly care, hospitality, and various services in urban areas of Madrid and Catalonia. Ecuadoreans became the fastest growing group in this decade, and during those early years they settled in urban areas of Madrid and Catalonia, but also, to a large extent, in agricultural areas of Murcia (Retis, 2006).</p>
  <p>Between 1995 and 2000, Latin American immigrants in Spain doubled (from 92,000 to 184,000). Between 2000 and 2005, they grew by more than 500% (reaching 986,000) and surpassed immigration from Africa. The regularization process of 2004 showed the diversification of origins. Those years saw immigration flows from most South American countries, with Ecuadoreans, Colombians, Argentineans, Peruvians, Dominicans, Bolivians, Brazilians, Paraguayans, Cubans, Venezuelans, and Uruguayans among the most numerous. The numbers continued to rise until 2009, when there were almost 1.5 million registered immigrants. The 2008 economic crisis in Southern European countries generated a slight decline in the numbers of Latin American immigrants with residence and work permits. This recent decrease in the number of visas and work permits shows some return migration, but also naturalization processes, as well as new migratory flows toward other countries in northern Europe (Retis, 2011). At the end of 2015, fewer than 900,000 Latin Americans were residing in Spain (879,000).</p>
  <figure>
    <h3>Figure 2. Latin American Immigrants in Spain (1995-2015)</h3>
    [FIGURE 2 GOES HERE]
    <figcaption>Figure 2. Latin Americans with working or resident permits by year. Source: Observatorio Permanente de la Inmigración. Ministerio de Empleo y Seguridad Social. Yearbooks from 1995 to 2015.</figcaption>
  </figure>
  <p>Throughout these decades, mainstream media in Spain has played a key role in presenting and (re)presenting the arrival, settlement, and return process of Latin American immigrants. For the last 10 years, I have been analyzing the portrayal of Latinos in Spanish mainstream media from qualitative perspectives. My studies have compared the specificities of how Latina immigrants have been portrayed in news media and fiction series (Galán &amp; Retis, 2012; Retis, 2013). They have also compared how young immigrants are depicted in European media (García &amp; Retis, 2011; Retis &amp; García, 2010), examined how the need for self-representation has encouraged the creation of ethnic media in Madrid (Retis, 2008), and how cultural consumption of Latin American immigrants in Spain demands a transnational perspective (Retis, 2011). In this article, I specifically analyze what I consider the trigger moment when Latin American immigrants burst for the first time on the front pages of national print newspapers. A rapid review of current news coverage of Latin American immigrants could give us the perception that they have always been part of the discussion when, indeed, they haven’t been. Extensive coverage didn’t happen until two events related to social conflict occurred. These two events coincided with the growing political debate on immigration reforms in Spain, the increase of racism against non-European immigrants, particularly Moroccans, and the perception of immigration as a problem for Spain.</p>
  <p>What is presented here is part of a broader investigation that seeks to deconstruct the socially constructed public discourse and collective representations of Latin American immigrants that arrived mainly for economic reasons to Spain during the turn of the century (Retis, 2006). It seeks to examine transnational contexts of immigration flows and to contrast them with public discourses around this phenomenon. That larger study demonstrated how news media portrayal of immigrants has contributed to the construction of hegemonic discourses on segregation, even in the case of the ones considered “preferred,” such as Latin Americans. The media construction of emotions of compassion or fear towards non-European foreign workers has contributed to the public conception of immigration as a problem. These types of discourses served to justify the segregation of minorities. These trends are encountered when examining news media coverage of the arrival and settlement of Ecuadoreans and Colombians in Spain during 2001 (Retis, 2006).</p>
</section>
<hr />
<section>
  <h2>Methodology and Research Design</h2>
  <p>This study analyzes how the political debate on immigration reform turned immigration into a topic of public interest, as well as how and when it was treated as one of the main problems for the country. Researchers have demonstrated how news media play an important role in setting the public agenda (McCombs, 2004; Weaver, McCombs, &amp; Shaw, 2004). Mostly due to the choices they make on which events to highlight or ignore, media not only reflect social reality but actively shape it (Tuchman, 1978). In other words, media frames shape audience frames (Benson 2013; Iyengar, 1991).</p>
  <p>When monthly opinion polls and media coverage are compared, the statistics show an increase in the general public’s perception of immigration as a “problem” between January and March 2001. It was considered the third most important issue, only behind terrorism and unemployment. By March and April, it significantly dropped to fourth place and kept falling until the end of the year, when it was considered the sixth main problem (Figure 3). The statistics showed, however, that immigration in Spain not only did not decline but continued to increase. </p>
  <p>Why and when, then, did the perception of immigration as one of the country’s problems increase or diminish? A review of secondary sources that analyzes on a daily basis the news coverage of immigration in Spain showed that the peak in the curve coincided with the moment when the public debate on immigration received greater media exposure (Centro de Investigaciones Sociológicas, 2000, 2001; Fundación Iberoamérica Europa, 2000, 2001, 2002; SOS Racismo, 2000-2002). Newspapers covered the political debate on the immigration reform with a greater focus on political parties to the detriment of alternative voices, such as the immigrants themselves, associations, or experts on the subject. The three mainstream media analyzed for this study utilized the terms <em>El Problema de la Inmigración</em> (The Problem of Immigration) as sub headlines in the majority of their coverage during those years. News media covered the presence of non-European immigrants mainly as a social conflict, not as part of the new need for foreign workers due to the expanding Spanish economy (Retis, 2006).</p>
  <figure>
    <h3>
      Figure 3. Public Perception of Main Problems in Spain<br />
      (September 2000 – November 2001)
    </h3>
    [FIGURE 3 GOES HERE]
    <figcaption>
      <em>Figure 3. Respondents were asked, “What are the three main problems affecting Spain?”<br />
      Source: Centro de Investigaciones Sociológicas, monthly reports.</em>
    </figcaption>
  </figure>
  <p>Three national dailies were selected because they were the newspapers of greatest distribution in Spain: <em>El País</em>, <em>El Mundo</em>, and <em>ABC</em>. Data were collected from January 2001 to January 2002, the time during which the immigration reform was being debated publicly in the country and when Latin Americans started being covered by these news outlets. These three mainstream media conformed the main public scenario for the political debate. Each one of them is related to specific groups within the political parties and economic elites in Spain. Starting with its book publishing business (Editorial Santillana) and on becoming the main shareholder of the national newspaper <em>El País</em>, the Grupo Promotora de Informaciones, S.A., came about in the context of media concentration, and its plans for expansion into radio and television broadcasting benefitted from the support of the successive governments of the Spanish Socialist Workers’ Party (PSOE). Since 1996, the Popular Party (PP) backed Telefónica––the old telecommunications state-owned monopoly—in its efforts to become a multimedia conglomerate, easing the legal barriers for corporate acquisitions, and granting broadcasting licenses and legal modifications. Grupo Correo Prensa Española, the publisher of the newspaper <em>ABC</em>, also took a conservative stance from the start, while Grupo Unidad Editorial, the publisher of <em>El Mundo</em>, which denounced PSOE for harassment during PP’s first mandate, benefitted from a number of concessions (Reig, 1994; Retis, 2006). Moreover, these news sources were chosen not only because of their wide circulation but also because they are referred as sources for other media, including TV and radio newscasts.</p>
  <p>Most of our social and political knowledge and our beliefs about the world emanate from the information we read or hear every day (Van Dijk, 1997). Therefore, at the turn of the century, Latin American immigrants in Spain began to be known more through their presence in mainstream news media than through daily intercultural interactions. Spaniards began to hear about Latin Americans from news and feature stories and from interviews with sources that tended mainly to relate to their presence in social conflict (Retis, 2006). The idea of “Latin American immigrants” in Spain was built collectively, giving the entire group characteristics that did not represent their actual nature, but resulted in a symbolic construction that constituted an “imagined immigrant” (Santamaría, 2002). While Latin American immigration is the result of multiple factors operating at different levels, the crossing or intersection between local and global contexts is rarely acknowledged in the genre of news. A complex and heterogeneous situation is turned into symbolic representations of “them,” the Latin Americans, versus “us,” the Spaniards (Retis, 2006).</p>
  <p id="note-line-6">An initial search was used to identify which news stories made distinctions between the largest national groups of Latin American immigrants.<sup><a href="#note-6">[6]</a></sup> Results confirmed that mainstream media concentrated their attention on Ecuadorean and Colombian groups when portraying Latin Americans. So it was decided to conduct searches with the terms “Ecuadorean” and “Ecuadorean immigrants,” and “Colombians” and “Colombian immigrants.” A selection was also made of news stories that included a thematic correlation with the country of origin. On this basis, a number of lists were drawn up for each national group and for each of the three newspapers under study. A total of 3,464 news items were encountered, of which 1,025 corresponded to Ecuadoreans (246 in ABC, 311 in El Mundo, 468 in El País) and 1,328 to Colombians (388 in <em>ABC</em>, 621 in <em>El Mundo</em>, 319 in <em>El País</em>). </p>
  <p>This article presents part of a broader study (Retis, 2006) and centers the analysis on two events that generated the greatest press coverage at the turn of the century: the accident involving Ecuadorean workers in Lorca, Murcia, and the confrontation between Colombian criminals in Madrid. A selection of the news coverage of those events is discussed in these pages. Within each news story, a content analysis was implemented to categorize the headlines, the characters involved in the news stories, how they are named in the narratives, and the language used to depict Ecuadorean and Colombian immigrants. This approach relates comparable methodologies used by frame analysis (Benson, 2013; Benson &amp; Saguy, 2005; Jefferies, 2009), discourse analysis (Gee, 1996; Santa Ana, 1999, 2002) and critical discourse analysis (Van Dijk, 1997, 2001; Wodak &amp; Meyer, 2001). I analyzed mainly how linguistic choices are utilized to present the events, the characters implicated, and the main news sources, and how the articles framed emotions of fear and compassion towards immigrants.</p>

  <h3>News Media Discourse of Compassion: Ecuadorean Immigrants in Spain</h3>

  <p>During 2000, there was an intense political debate on immigration regulation, opened by the approval of the Organic Law 4/2000, the events of El Ejido, the electoral debate during the elections, the extraordinary regularization process, and the approval of the Organic Law 8/2000 that entered into force on January 23, 2001. The approval of this last law with the majority of votes from the PP and the opposition of PSOE generated a climate of confrontation. It is crucial to take into account this climate to understand why the events analyzed here generated a large volume of news media coverage. </p>
  <p id="note-line-7">The emergence of the Ecuadoreans in the discourse on non-EU immigration in Spain came about due to a shocking road accident in which 12 workers on their way to harvest broccoli in Lorca, Murcia, died on Jan. 3, 2001. The magnitude of the event and its coverage in the mass media fostered the opening of a social debate comparable only to two previous incidents: the murder of the Dominican immigrant Lucrecia Pérez in Madrid, which was considered the first hate crime in Spain<sup><a href="#note-7">[7]</a></sup> and the events in El Ejido, which were considered the first racist confrontation in the country (Retis, 2006). The news coverage of the murder of Lucrecia Pérez brought for the first time in the news media the figure of Latin American immigrants arriving to take care of the elderly and of children in Spain. The debate on the increase of racist attitudes was echoed by the news media, but ended a few days later (Calvo, 1993). News of the events of El Ejido on Feb. 5 and 6, 2000, echoed the coverage of immigration as “a problem” and the idea that Spain was receiving “too many” immigrants, a narrative that “is not informative but connotative,” reproducing the metaphor of “the avalanche” and “invasion” of Europe by foreigners (“the new barbarians”), thus supporting the increase of “xenophobic” discourse (Calvo, 2000, p. 52). Until then, Spaniards tended to perceive mainly Moroccans and Sub-Saharan Africans as immigrants (Centro de Investigaciones Sociológicas, 2000).</p>
  <p>The accident of 12 immigrant workers in Murcia became a milestone in the discursive representation of Ecuadoreans in Spain. Until then, the image of Ecuadoreans in the context of non-European immigration had not been covered with such intensity, and news media had not particularly paid attention to the increased arrivals of Ecuadoreans. Moreover, until then, these stories had not generally occupied front pages or main headlines (Retis, 2006). The analysis of the media coverage seeks to understand not only the ways in which Ecuadoreans are depicted as <em>Them</em>, but also the ways in which Spaniards are depicted as <em>Us</em>. Such an analysis focuses on the ways that events and their participants were represented in the texts, and looks at whether the structures of the text convey a generally positive or negative opinion about <em>Us</em> versus <em>Them</em> (Van Dijk, 2000). </p>
  <p>During the time period analyzed, news media covered public debates involving various characters: representatives of political parties, labor unions, machinists’ union, national/regional/local authorities, members of the Catholic church, NGOs, and immigrants themselves. The analysis demonstrated that access to media discourse favored mainly Spanish authorities and local administration rather than giving voice to immigrants (Retis, 2006). </p>
  <p>From Jan. 4, a Thursday, to Jan. 7, a Sunday, the three national newspapers presented the events very similarly. The first day, a photograph of the train, placed on the upper left corner in a preferred position on the front page, offered a widely circulated visual. The headlines were very similar: “Twelve Ecuadoreans die run over by a train in Lorca” (<em>ABC</em>), “Twelve Ecuadoreans die by being run over by a train in Murcia” (<em>El País</em>), “Twelve Ecuadoreans killed as train hits crammed minivan” (<em>El Mundo</em>). The designations were the same: first, the word Ecuadoreans in the headline, highlighting the nationality, <em>the others</em>; second, the word “immigrants,” a form of designation first used in the early 1990s that involves a series of symbolic connotations: “those who come to settle in our country, probably without proper documentation” (Martin, 2003); third, the three news media outlets highlighted the information concerning labor inspection and the search for the culprit in this accident, delving into the more immediate and local perspective of the phenomenon, without extending this discussion to global conditions or explaining to the readers the relationship between immigration senders and receivers or the international division of labor (Granados, 2002). <em>El País</em> wrote: “Labor Inspectors investigate their working conditions” (<em>El País</em>). ABC presented two other epithets, “The tragedy has shocked the large Ecuadorean community in the region,” highlighting the designation of “others” as an “imagined community” (Santamaría, 2002), as “different.” and also “numerous”––an idea presented in the media discourse referring to immigration in the sense of whether they are “many” or “too many” immigrants in the country.</p>
  <p>Moving from the front pages to the inside sections, the study found more similarities: photographs of dead bodies covered with blankets and visual graphics replicating the accident. The stories were presented as “the tragedy in Lorca, Murcia,” capturing the emotion of the event and centering attention on that region, and also in relation to “the problems of immigration,” as <em>El País</em> captioned. These trends are not unique to the Spanish press; it has been shown that European media generally tend to relate immigration with negative connotations, social problems, and crimes (Lowander, 2003), as the discursive dimensions of racism have a central meaning in Europe (Wodak, 2000).</p>
  <p>News coverage frames immigrants as victims. In these particular stories, the “humanitarian” frame highlighted the economic, social, and political suffering of Ecuadoreans. The news coverage of the funeral exemplifies this aspect. <em>El País</em> published: “Relatives and friends of the victims followed the funeral from the front row, assisted at all times by a team of psychologists from Red Cross Civil protection. The 12 coffins, covered with bouquets and dozens of wreaths, were at the altar...” In <em>ABC</em>: “The 12 coffins, covered with bouquets and dozens of crowns, were at the altar ...  Relatives and friends of the victims followed the funeral from the front row, assisted at all times by a team of psychologists from Red Cross and Civil Protection...” As noted, the quotations are virtually identical and thus show a comparable version of the events. </p>
  <p>The three news media outlets used the same sources of information. As a consequence, even if they are supposed to belong to diverse editorial perspectives, they reproduced the same quotes, almost in the same type of news stories. The (re)presentation of those involved in this debate is also indicative of how there is a consensus in the national press to polarization, i.e. positive self-presentation and negative representation of <em>the other</em> (Van Dijk, 1997). In this case, the “global economy” frame emphasizes the problem of poverty. Ecuadorean immigrants are presented as passive and exploited actors, but also as undocumented, i.e. as violators of the law, highlighting the criterion of national origin as symbolic border of exclusion, utilizing the “legal” frame. At the other pole of representation, labor unions and political parties, as actors, were positively represented as those assuming the voice of protest over the working conditions of “others”––the “immigrants” in Spanish fields. “The 14 occupants were of Ecuadorean nationality, some of them allegedly undocumented immigrants, and the fact that they were traveling in an overcrowded wagon gave rise to protests from unions and political parties on the treatment of many immigrants who work in the Spanish fields” (<em>El País</em>).</p>
  <p>News media outlets presented members of the in-group that look compassionately to Ecuadorean immigrants and seek those responsible for the accident. The “humanitarian” and “racism” frames are utilized to cover the presence, for example, of the representative of the national government: <em>El País</em> published, “The government delegate for immigration, Enrique Sánchez-Miranda, traveled to Murcia to comfort the relatives of the deceased immigrants. He refused to explain whether this is a new case of exploitation and undocumented workers” (<em>El País</em>). <em>El Mundo</em> highlighted, “Machinists blame the driver.” The “public order” and “legal” frames are utilized when covering confrontations between representatives of political parties. An example is this headline, which addressed how PP representatives are attacked by PSOE representatives utilizing immigration and other “social problems” in Spain: “PSOE brands as ‘slackers’ the government ministers [already] overwhelmed by immigration, leukemia and ‘mad cows’” (<em>El Mundo</em>).</p>
  <p>The analysis of the characters involved and how they are named in the narratives, and the language used to depict struggles or tensions in the stories, showed an unequal presentation of government authorities and immigrants. In the three news outlets, Ecuadoreans tend to appear unidentified and their statements are never quoted directly: “In this regard, reports <em>Europa Press</em>, a compatriot of the deceased, who declined to give his name, said that the only one who had regularized his situation was the driver of the van” (<em>El Mundo</em>). On the one hand, Ecuadoreans are presented as victims of the tragedy, of the working conditions and of the exploitation. In particular, the (re)presentation of the survivor of the accident––a 12-year-old girl named Nancy––denotes the configuration of the metaphor of poverty and suffering, which inspires the reaction of compassion. On the other hand, Ecuadorean immigrants are also presented as the least responsible for the accident; the treatment of the driver, Nelio López, is an example. They are depicted as victims or victimizers, but are still those “others” who inspire compassion or rejection (Rizo, 2001).</p>
  <p>For the mainstream media, the girl symbolizes extreme labor exploitation, the miserable working conditions, the sadness, and the cry for compassion: “Young Nancy wanted to ‘help bring money home’” (<em>El País</em>, Jan. 4, 2001). On Jan. 5, the three newspapers highlighted a photograph of Nancy convalescing and with bandages on her forehead in her hospital bed. <em>ABC</em> highlighted this news in its summary; <em>El País</em> extended the size of the photograph and revealed the image of the mother and sister, highlighting the sadness in their faces. <em>El Mundo</em> moved the same EFE News Agency photograph to its front page, and highlighted in the caption: “An Ecuadorean girl injured in the Lorca accident.” On page 6, <em>ABC</em> did not show the photograph but highlighted Nancy in a headline: “‘Beware! The train is coming,’ shouted the 13-year-old girl injured in the accident.”</p>
  <p><em>ABC</em> published an editorial on Jan. 4 utilizing several elements of the “humanitarian” and “racism/xenophobia” frames in the tone of compassion and threat. The piece not only highlighted the appalling working conditions, but also presented the driver as “the other,” “ignorant,” and “inept,” a person who could not, or did not know, how to recognize the signs when crossing the train rails: “It was still at night. Fourteen people crammed into a seven-seat minivan were traveling to a nearby farm to pick broccoli. The driver, Ecuadorean, and probably little acquainted with traffic signs, did not see the level crossing without barriers ... The most terrible [circumstance] is the demeaning working and transportation conditions of some immigrants in Spain” (<em>ABC</em>).</p>
  <p>The analysis also showed the structure and strategies of these texts and how they are related to the social or political context. Some of them focus on local meanings, such as coherence or implications that construct semantic liaisons to conform metaphors of immigrants as victims but also as criminals. On Jan. 4, for example, ABC included in the same section a police report titled “The crime rate in Spain fell by almost 10%. The Civil Guard found 9,000 immigrants up to September 2000.” We noted that numbers are declining, but the fact that this story is placed close to the story on the accident of Ecuadorean immigrants reinforces the ideological relation of immigration with crime. On Jan. 6, the same newspaper published, “The entrepreneur who illegally hired the Ecuadoreans who died has been captured” and, in the same page, published this other story, “A jeweler dies after being docked by three Maghreb immigrants.” This type of thematic coherence implies news media coverage associating immigration with crime and delinquency.</p>
  <p>The implementation of the reform of the Immigration Act on Jan. 23, 2001, generated a series of public demonstrations. These groups of immigrants, especially represented in the news media by Ecuadoreans, were referred as a new “avalanche” following the accident at Lorca. Thus we read a headline: “Ecuadoreans” without papers “in Lorquí start a third confinement” (<em>El País</em>, Jan. 18, 2001). Again we find the figure of “paperless” as a matter of illegality and confinement in protest by Ecuadoreans. The news story referred to the president of the Association of Immigrants of Lorquí, Lenin Duque, without reproducing his words, commenting that he “justified the decision to join the protests, which began in Lorca in the early hours of Monday, [by noting] the impact that the new Immigration Act will have on the immigrant community ‘in general.’” The reporter used quotation marks to highlight Duque’s statement emphasizing that there is another group of “general,” i.e., “legal” immigrants. The analysis demonstrated that the use of euphemisms when categorizing non-Europeans is recurrent in the news media discourse. </p>
  <p>As researchers have demonstrated, metaphoric mappings are a major process of human understanding (Lakoff &amp; Johnson, 1980), and when discourse analysis is implemented, one finds major and minor metaphors in a text (Chilton &amp; Ilyin, 1993; Santa Ana, 1999). Santa Ana, for example, found that the dominant metaphor utilized by the <em>Los Angeles Times</em> depicted immigrants as animals, while less frequently a set of secondary metaphors included immigrants as debased people, weeds, commodities, and so on (Santa Ana, 1999, p. 198). In the present study, it was found that Ecuadoreans were depicted not only as “poor” in the sense of low-income condition, but also in the sense of lack of character. News media coverage tended to present Ecuadorean immigrants as exploited and living in sub-standard conditions. This metaphor is extended to the representation of the country of origin. The clearest image of Ecuador in Spanish news media was that of a country living through a stampede, battered by economic crisis and corruption. As a consequence, Ecuadoreans are presented as fleeing en masse, as the “avalanche” of new poor, “new conquerors.” On the other hand, Spain is portrayed as “El Dorado,” a paradise, the place where they come to seek fortune. Headlines published on Jan. 7 exemplify this pattern: “Ecuador, a country stampede,” and a subhead: “The US is no longer the only <em>El Dorado</em>”; “Spain is the escape hatch for 50,000 people” (<em>El País</em>); “The Ecuadorean ‘desert’; There are places like <em>el Pueblo de las Mujeres Solas</em> (the town of lonely women), where there are no husbands left because they have emigrated in search of fortune. Years ago they immigrated to the US; now Spain is the dream destiny” (<em>El Mundo</em>). “The conquerors of the 20th century” (<em>ABC</em>). “What are Ecuadoreans fleeing from?” (<em>El País</em>, Jan. 23, 2001).</p>
  <p>Although the three newspapers in this study have diverse ideological affiliations, the analysis showed that coverage of news events was similar.  Five key topics were utilized to frame the news media discourse: 1) the tragic accident seen as the ‘exposure’ of many other ‘social problems’ related to non-EU immigrants; 2) the surprising discovery of the recent increase in Ecuadorean immigrants in Murcia; 3) the precarious work conditions of Ecuadoreans in the Spanish agricultural industry; 4) the lack of inspectors regulating the temporary labor market; and 5) the corruption of Spanish employers recruiting immigrant workers by irregular means.</p>

  <h3>News Media Discourse of Fear: Colombian Immigrants in Spain</h3>

  <p>If the social debate on immigration during 2001 opened with the news coverage of the accident at Lorca, that year was particularly significant for the approval of the Immigration Act 8/2000, the group of immigrants who confined themselves as public demonstration of their rejection of the new legislation, accusations from the opposition political party that the new law was unconstitutional, as well as the control and treatment of immigration by the government and the approval of the law known as Royal Decree 864/2001. For Latin American immigrants in particular, there was another event presented in the public discourse with the “legal” and “racism/xenophobic” frames: the launch of the Ludeco Operation by the Directorate-General of the Police. This operation was publicized during mid-October 2001, emphasizing the battle against crimes committed by Colombian and Ecuadorean immigrants in Spain. The direct antecedent of this measure was the previous Operación Café (Operation Coffee), launched in September of 2001 in response to the death of four Colombians in the district of Vallecas, in Madrid. A series of events that occurred after the implementation of these operations was covered by mainstream media, presenting a thematic correlation of immigration bringing crime and delinquency from Latin America.</p>
  <p>The link between crime and immigration is one of the pairings with the greatest presence in social debate in Spain (Wagman, 2002), which helps reinforce the criminalization of people for the simple fact of being immigrants (Aierbe, 2002). If the debate on immigration at the turn of the century was especially relevant due to the implementation of the Immigration Act 8/2000 and the Royal Decree 864/2001, also important to Latin Americans was the launching of the so-called “Operation Ludeco” by the Directorate-General of the Police by means of a pamphlet in which emphasis was placed on crimes committed by Colombians and Ecuadoreans. </p>
  <p>According to the statistics published by the Madrid City Council, during 2001 Colombian immigrants almost doubled (from 22,000 to nearly 38,000). The numbers increased mainly due to the announcement that Colombians would no longer be exempt from visa requirements starting on January 2002, in the first attempt by the Spanish government to control and reduce Colombian immigration flows. During those years, a study by two universities in Madrid (Aparicio &amp; Giménez, 2003) examined the main characteristics of Colombians in Spain: 63% were between 25 and 44 years old, 24.6% worked in housekeeping, 21.1% in construction, 15.8% in hospitality, and 10.3% in sales. (According to this survey, roughly 75% of Colombians were working, and four out of five arrived in Spain as tourists when no visa was required. The authors argued with these figures that Colombians should not be identified mostly as criminals and drug dealers, because so many (45,000 by then) were working legally and contributed 180 million Euros to the Social Security system.</p>
  <p>Unlike the compassionate attitude towards the Ecuadoreans, the appearance of Colombians in news coverage of immigrants in 2001 was accompanied by an attitude of fear. On Jan. 15, 2001, the police arrested four members of a criminal gang. An analysis showed that, in the dispute over the police budget, each political group adopted strategic positions of confrontation, and the headlines the following day illustrated the difference between the editorial stance of each newspaper: “Police arrest Colombian gang who extorted money from a jeweler and attacked his wife” (<em>ABC</em>); “Police bust criminal gang that tried to extort money from a jeweler” (<em>El País</em>); and “Arrested for swindling a jeweler” (<em>El Mundo</em>).</p>
  <p>The media construction of fear in the face of the threat posed by the presence of Colombian immigrants offers stark contrast with the findings of scientific studies that indicate, among other things, the average level of education of Colombians residing in Spain was the same as, or higher than. that of the Spaniards (Aparicio &amp; Jiménez, 2003). An analysis of the journalistic discourse on Colombians revealed a discursive metonymy; they were first branded as Colombian criminals, then the demonym was used as a synonym for crime: “Police convinced that Colombian violence will have a spillover effect on society as a whole” (<em>ABC</em>, Sept. 1, 2001). In the entire analysis, only one example was found that cautioned against applying this analogy to the collective as a whole: “Ansuátegui stresses that Colombian criminals are a minority” (<em>El País</em>, Oct. 3, 2001).</p>
  <p>The media construction of fear toward Colombians was based on several frames that portrayed immigrants or immigration as a threat. The “public order” frame emphasized law breaking. As Benson (2013) argued, “the immigration lawyers who promote ‘victim’ coverage and the reporters who follow these leads do not perceive themselves as promoting anti-immigration attitudes, although it is possible that some readers predisposed to such attitudes will find evidence in such coverage to reinforce their worldviews” (Benson, 2013, p. 7). On the other hand, as Van Dijk (2000) argues, most Spanish readers have few daily experiences with minorities, and most readers have little alternative information about minorities. The media emphasize <em>Us</em> and <em>Them</em> polarization by focusing on various problems and threats for <em>Us</em>. Meanwhile, minority groups do not have enough power to publicly oppose biased reporting (Van Dijk, 2000, p. 37).</p>
  <p>The depiction of Colombian immigrants as a threat was based on two main topics. On the one hand, the majority of the articles on these groups during the time analyzed were related to drug trafficking: “Police dismantle Colombian drug trafficking network operating on the Internet and making payments with emeralds” (<em>ABC</em>, May 29, 2001). On the other hand, a second topic appeared––news related to robberies and kidnapping: “Firemen rescue a Colombian kidnapped for 10 days” (<em>El País</em>, Jan. 18, 2001); “Hired assassins and dangerous criminals arrested in one of the biggest operations to date against Colombian gangs” (<em>ABC</em>, Nov. 25, 2001); “Police dismantle dangerous Colombian gang that raided more than 50 chalets and flats” (ABC, June 28, 2001).  </p>
  <p>Similar to what happened when analyzing the portrayal of Ecuadoreans and Ecuador in the Spanish press, this study encountered a thematic relation between the way mainstream media covered Colombian immigrants and the news media coverage of Colombia. As Reguillo (2002) argues, “For governments and the international press, Colombia has become the ‘metaphor of horror’ and this means chaos, lawlessness, excessive violence, institutions controlled by drug traffickers, institutional collapse” (Reguillo, 2002, p.63). </p>
  <p>The linking of Colombian immigrants with the increase of crime in Madrid, and by extension in Spain, was mainly due to the greater coverage of the police as the main source of these news stories. While the information on the crimes carried out by Colombians was a recurring theme through the year, the exacerbation of “fear” to the “crime wave” coincides with the exaltation of international news coverage after Sept. 11. In this climate of fear, “the others” framed in global public discourse emphasized the figure of radical Islamists and, by extension, Arab immigrants. In the Spanish context and referring to non-EU immigrants and specifically Latin Americans, the study found a direct relationship between images of Colombians and immigration and fear of increased insecurity. The three news media outlets focused on the statements of the administrative authorities, representatives of unions, and official reports. The press echoed these statements, but also produced its own investigative reporting and exclusive interviews. In other words, newspapers not only opened this framing of immigrants as a threat but also participated in this particular social debate. </p>
  <p>In contrast to what happened with news coverage of Ecuadoreans, the figure of the Colombian did not appear in the news as a surprise, but came as slow but constant reporting in which Colombian criminals were gaining prominence inside the newspaper, at certain times appearing in the front page of the “Madrid” section or in the sections devoted to “National” news or news of Spain­­––even sometimes on the front page. In other words, what the study found is the “logic of continuity.” One of the strategies used was the emphasis on “truthfulness,” that is, including official statistics in the news. The media tended to report on the number of immigrants residing in Spain, but also on how many were in prison and/or committing crimes: “Foreign mafias triggered the killings,” or “Police missing closure to 60 murders in Madrid, under the shadow of Jonathan,” or “Nearly half of the dead are foreigners and only 12 cases are pending” (<em>ABC</em>, Jan. 6, 2001).</p>
  <p>The lead of the news story emphasizes the alarmist discourse on the presence of foreigners in Spain, highlighting that the killings “have skyrocketed” in Madrid, and that members of the police must work “to the rhythm of the heart,” and that “alarms are skyrocketing” because the result of accounting statistics reveals that half of the offenders are not Spaniards. This is one of the first items in the chronological analysis of how mainstream media portrayed Colombians. And it shows a trend that became recurrent in the media discourse on Colombians ––“the metaphor of horror” related to the country of origin. One of the paragraphs of this story, for example, is captioned with the phrase “When the city seems to be Bogotá.” The use of the Colombian capital presupposes that the journalist shares prior connotations with the readers. “Madrid is not Bogota” implies that the Spanish capital should not have the same characteristics of violence and crime as Colombia. In the phrase, “Colombians, once more ...” the sense of continuity of the “wave of violence” increases with the emphasis on the national category of Colombians. In the quote used by the reporter to illustrate the opinion of the researchers, we see how Colombians are not classified as international criminals, but that the crimes are attributed to a cultural difference: “The key is the appearance of organized criminal groups, which begins to take its toll on people’s lives. They claim unpaid debts, mostly related to drug trafficking and money laundering. Hiding part of a drug shipment, quarrels over its distribution, a betrayal… those things belong to cultures in which life does not have the same values as we do, researchers explain.” (<em>ABC</em>, Jan. 6, 2001).</p>
  <p>The analysis of the media discourse on Colombian immigrants revealed classifications related to fear and aversion.  First, the situation of immigrants was thematically related to violence in the country of origin: “Immigrants reporting a Gandía businessman fear reprisals. In Colombia, if someone threatens you, you’re dead” (<em>El País</em>, Jan. 21, 2001); “Border police at Barajas deny entry to 3,712 foreigners during the year 2000” (<em>El Mundo</em>, Feb. 12, 2001); “Colombia says that visa demands punish everyone and that drug traffickers are a minority” (<em>ABC</em>, March 28, 2001). Second, drug trafficking was a recurrent theme in news stories: “Cocaine seized in Vinarós would have a street value of 35,000 million pesetas” (<em>El País</em>, Jan. 14, 2001); “Police dismantle Colombian drug trafficking network operating on the Internet and making payments with emeralds” (<em>ABC</em>, May 29, 2001). Third, crime, violence and extortion was also a recurring theme: “Police bust criminal gang that tried to extort money from a jeweler” (<em>El País</em>, Jan.16, 2001); “Firemen rescue a Colombian kidnapped for 10 days” (<em>El País</em>, Jan. 18, 2001); “Nine Colombians arrested for burglaries and murder” (<em>El Mundo</em>, Feb. 11, 2001); “Police dismantle dangerous Colombian gang that raided more than 50 houses and apartments” (<em>ABC</em>, June 18, 2001). Fourth, news about Colombia related to the guerrillas, corruption and extreme poverty: “ELN guerrillas kidnap Latin American motorcycle champion in Colombia” (<em>ABC</em>, Jan. 4, 2001); “Colombia, on the threshold of terror” (<em>El Mundo</em>, March 16, 2001).</p>
  <p>The analysis showed that news media outlets tend to focus on homicides, clashes between criminals and gang showdowns. Comparative analysis found that <em>ABC</em> is the newspaper that most uses the word “Colombians” in its headlines and reproduces the government’s official version of the story. <em>El Mundo</em> didn’t emphasize the nationality of offenders, although, in contrast, it favored play with more melodramatic strategies. <em>El País</em> used the national origin of foreign delinquents to a lesser extent in the headlines, although it tended to be collected in the stories and often using a confrontational tone by including statements from opposition sectors from both regional and national officials.</p>
</section>
<hr />
<section>
  <h2>Conclusions</h2>
  <p>Many people still lack information about the magnitude, reach, and socio-economic context of migration.  As a consequence, support for immigration has gradually decreased in Western countries, this being particularly evident from the mid-1990s onwards (IOM, 2011). This article focused on the central role played by the Spanish mainstream media in the symbolic construction of migrants as <em>others</em>. As demonstrated, there are clear trends in the forms of representation of Latin American immigrants. As non-European immigrants, they are perceived, generally, either as a problem or as a threat.  News coverage sets symbolic boundaries geographically, tends to specify their nationality when reporting social conflict, extrapolates criminal conditions of a minority group in general, and ignores the positive aspects of their presence in the country. In comparative terms, there is evidence of a compassionate view toward Ecuadoreans and of fear toward Colombians. Polarizing strategies depicting <em>Others</em> and <em>Us</em> are applied to the coverage of immigrants. These trends are not unique to the Spanish press, as they apply to most of the European media. Journalism professional associations recognize their shortcomings and have developed codes of conduct as guidelines for self-criticism of journalistic work, but there is still much work to do in order to overcome these trends.</p>
</section>
<hr />
<section>
  <h2>References</h2>
  <p class="references">Aierbe, P. (2002). Inmigración y delincuencia, un binomio interesado. <em>Análisis de prensa 2002. Inmigración racismo y xenophobia</em>. San Sebastián: Mugak.</p>
  <p class="references">Arango, J. (2000). Becoming a country of immigration at the end of the twentieth century: The case of Spain. In R. King, J. Lazardix, &amp; C. Tsardanids (Eds.), <em>Eldorado or fortress? Migration in Southern Europe</em> (pp. 253-276). London: Macmillan.</p>
  <p class="references">Arango, J. (2002). La inmigración en España a comienzos del siglo XXI: Un intento de caracterización. In F. García &amp; C. Muriel, (Eds.), <em>La inmigración en España: contextos y alternativas, vol. II</em>. Granada: Laboratorio de Estudios Interculturales.</p>
  <p class="references">Aparicio, R., &amp; Giménez, C. (2003). <em>Migración colombiana en España</em>. Brussels: International Organization for Migrations.</p>
  <p class="references">Appadurai, A. (1996). <em>Modernity at large: Cultural dimensions of globalization</em>. Minneapolis: University of Minnesota Press.</p>
  <p class="references">Bañón, A. (2002). <em>Discurso e inmigración: Propuestas para el análisis de un debate social</em>. Murcia: Universidad de Murcia.</p>
  <p class="references">Benson, R. (2013). <em>Shaping immigration news. A French-American comparison</em>. New York: Cambridge University Press.</p>
  <p class="references">Benson, R., &amp; Saguy, A. (2005). Constructing social problems in an age of globalization: A French-American comparison. <em>American Sociological Review, 70</em>, 233-259.</p>
  <p class="references">Berger, P., &amp; Luckmann, T. (1966). <em>The social construction of reality: A treatise in the sociology of knowledge</em>. New York: Anchor Books.</p>
  <p class="references">Bustamante, E. (1982). <em>Los amos de la información en España</em>. Madrid: Akal.</p>
  <p class="references">Calvo, T.  (1993). <em>El crimen racista de Aravaca</em>. Madrid: Editorial Popular.</p>
  <p class="references">Calvo, T. (2000). El conflicto estructural en El Ejido: “A la caza del moro.” <em>Sociedad y Utopía, 16</em>, 39-55.</p>
  <p class="references">Casilda, R. (2002). <em>La década dorada. Economía e inversiones españolas en América Latina 1990-2000</em>. Madrid: Ediciones de la Universidad de Alcalá.</p>
  <p class="references">Centro de Investigaciones Sociológicas (CIS). (1996-2002). Barometers – Studies Num. 2511, 2468, 2459, 2441, 2409, 2383, 2310.</p>
  <p class="references">Chilton, P. A., &amp; Ilyin, M. (1993). Metaphor in political discourse: The case of the “Common European House.” <em>Discourse and Society, 4</em>(1), 7-31.</p>
  <p class="references">Colectivo Ioé (2003a). La sociedad española y la inmigración extranjera. <em>Papeles de Economía Española, 98</em>, 16-31.</p>
  <p class="references">Colectivo Ioé (2003b). <em>Inmigración y ciudadanía. España en el contexto de las migraciones internacionales</em>. Madrid: Fundamentos.</p>
  <p class="references">Cottle, S. (2000). <em>Ethnic minorities and the media: Changing cultural boundaries</em>. Buckingham: Open University Press.</p>
  <p class="references">Dader, J. (1999). La retórica mediática frente a la cultura política autóctona: La encrucijada de la comunicación política electoral entre la “americanización” y el pluralismo democrático tradicional. <em>Cuadernos de Información y Comunicación, 4</em>, 63-87.</p>
  <p class="references">Domingo, A. (2005). Tras la retórica de la hispanidad: La migración latinoamericana en España entre la complementariedad y la exclusion. <em>Papers de Demografía</em>, No. 254. Barcelona: Centro de Estudios Demográficos.</p>
  <p class="references">Fernández, J. (1991). Introduction: Confluents of inquiry. In J. Fernández (Ed.), <em>Beyond Metaphor: The theory of tropes in anthropology</em> (pp. 3–13). Stanford, CA: Stanford University Press.</p>
  <p class="references">Fundación Iberoamérica Europa. (1999-2003). <em>Inmigración y racismo: Análisis de radio, televisión y prensa española</em>. Madrid: IMSERSO.</p>
  <p class="references">Galán, E., &amp; Retis, J. (2012). “Mujer” e “inmigrante”: La doble discriminación. Análisis en la prensa escrita y la ficción televisiva en España. In N. García (Ed.), <em>Al descubierto. El poder democrático de los medios</em> (pp. 68-100). Madrid: Fragua. </p>
  <p class="references">García, P., &amp; Retis, J. (2011). Jeunes et minorités ethniques dans la presse européenne. Les medias et les émeutes parisiennes de 2005. <em>Global Media Journal, 4</em>(1), 77-92.</p>
  <p class="references">Gee, J. P. (1996). <em>Social linguistics and literacies: Ideology in discourses</em>. London: Taylor &amp; Francis.</p>
  <p class="references">Granados, A. (2002). ¿Es virtual la realidad de la inmigración?: La construcción mediática de la inmigración extranjera en España. In F. García, &amp; M. López (Coord.). <em>La inmigración en España: contextos y alternativas</em>, Vol, II (pp. 437-448). Granada: Laboratorio de Estudios Interculturales.</p>
  <p class="references">Harré, R. (Ed.). (1986). <em>The social construction of emotions</em>. Oxford: Basil Blackwell.</p>
  <p class="references">Herranz, Y. (1998). La inmigración latinoamericana en distintos contextos de recepción. <em>Migraciones, 3</em>, 31-51.</p>
  <p class="references">Hegde, R. (2016).  <em>Mediating migration</em>.  New York:  Polity. </p>
  <p class="references">Imbert, G. (1993). El sujeto europeo y el otro. <em>Archipiélago, 12</em>, 46-51.</p>
  <p class="references">IOM (International Organization for Migration). (2011). <em>World Migration Report 2011</em>. Geneva: IOM.</p>
  <p class="references">Iyengar, S. (1991). <em>Is anyone responsible? How television frames political issues</em>. Chicago: University of Chicago Press.</p>
  <p class="references">Izquierdo, A., López, D., &amp; Martínez, R. (2002). Los preferidos del siglo XXI: La inmigración latinoamericana en España. In F. García &amp; C. Muriel (Eds.). <em>La inmigración en España: Contextos y alternativas</em> (pp.  232-250). Granada: Laboratorio de Estudios Interculturales.</p>
  <p class="references">Jefferies, J. (2009). Do undocumented students play by the rules? Meritocracy in the media. <em>Critical Inquiry in Language Studies, 6</em>(1-2), 15-38.</p>
  <p class="references">Lakoff, G., &amp; Johnson, M. (1980). <em>Metaphors we live by</em>. University of Chicago Press: Chicago.</p>
  <p class="references">Levitt, P., &amp; Glick Schiller, N. (2004). Conceptualizing simultaneity: A transnational social field perspective on society. <em>International Immigration Review, 38</em>(145), 595-629.</p>
  <p class="references">Lowander, B. (2003). European research on immigrants and the mass media. Work document of the European Monitoring Centre on Racism and Xenophobia, Austria.</p>
  <p class="references">Martín Rojo, L. (2003). El análisis crítico del discurso. Fronteras y exclusión social en los discursos racistas. In Iñiguez, L. (Ed.) <em>Análisis del discurso. Manual para ciencias sociales</em> (pp. 161-196). Madrid: UOC.</p>
  <p class="references">Martín Rojo, L., &amp; Van Dijk, T. (1997). There was a problem and it was solved! Legitimizing expulsion of illegal migrants in Spanish parliamentary discourse. <em>Discourse and Society, 8</em>(4), 523-566.</p>
  <p class="references">Martínez, R. (2003). <em>La reciente inmigración latinoamericana a España</em>. Santiago de Chile: CEPAL.</p>
  <p class="references">McCombs, M. (2004). <em>Setting the agenda</em>. Cambridge: Polity.</p>
  <p class="references">Oso, L. (1998). <em>La inmigración hacia España de mujeres jefas de hogar</em>. Madrid: Instituto de la Mujer.</p>
  <p class="references">Pellegrino, A. (2003). <em>La inmigración internacional en América Latina y el Caribe: Tendencias y perfiles de los migrantes</em>. Santiago de Chile: CEPAL.</p>
  <p class="references">Pellegrino, A., (2004). Migration from Latin America to Europe: Trends and Policy Challenges. <em>International Organization for Migration Research Series, 16</em>.</p>
  <p class="references">Reig, R., (1994). <em>La mente global. Un estudio sobre estructura y análisis de la información</em>. Madrid: Libertarias.</p>
  <p class="references">Reguillo, R., (2002). El otro antropológico. Poder y representación en una contemporaneidad sobresaltada. <em>Anàlisi, 29</em>, 63-79.</p>
  <p class="references">Retis, J. (2006). <em>El discurso público sobre la inmigración extracomunitaria en España. Análisis de la construcción de las imágenes de los inmigrantes latinoamericanos en la prensa de referencia</em> (Doctoral dissertation). Universidad Complutense de Madrid, Madrid.</p>
  <p class="references">Retis, J. (2008). <em>Espacios mediáticos de la inmigración en Madrid: Génesis y evolución</em>. Madrid: OMCI.</p>
  <p class="references">Retis, J. (2011). <em>Estudio exploratorio sobre el consumo cultural de los inmigrantes latinoamericanos en España: El contexto transnacional de las prácticas culturales</em>. Madrid: Fundación Alternativas.</p>
  <p class="references">Retis, J. (2013). Immigrant Latina images in mainstream media: Class, race, and gender in public discourse in the United States and Spain. In M. Martinez (Ed.), <em>Discourses on immigration in times of economic crisis: A critical perspective</em> (pp. 29-59). New Castle: Cambridge Scholars Publishing. </p>
  <p class="references">Retis, J., &amp; García, P. (2010). Jóvenes inmigrantes latinoamericanos en la prensa española. Narrativas mediáticas de la alteridad: El caso de las violencias urbanas. <em>Revista Mexicana de Ciencias Políticas y Sociales, 52</em>(209), 135-159.</p>
  <p class="references">Rey Morato, J. (1988). <em>Crítica de la razón periodística. Un análisis desde la teoría general de la información</em>. Madrid: Universidad Complutense.</p>
  <p class="references">Rizo, M.  (2001). Miedo y compasión: Dos estrategias de movilización afectiva en el discurso informativo sobre el inmigrante. <em>Comunica, 2</em>.</p>
  <p class="references">Rizo, M. (2011). Movilización afectiva en el discurso televisivo sobre la inmigración en el estado español. <em>Versión, 26</em>, 119-140.</p>
  <p class="references">Rodrigo, M.  (1992). Notas propedéuticas para el estudio de las pasiones comunicativas. <em>Contratexto, 5</em>, 39-52.</p>
  <p class="references">Rodrigo, M.  (1996). La información como comunicación intercultural mediada. <em>Reflexiones, 45</em>, 17-28.</p>
  <p class="references">Rodrigo, M. (1997). Las emociones en la comunicación. <em>Comunicación y Estudios Universitarios, 7</em>, 147-153.</p>
  <p class="references">Rodrigo, M., &amp; Martínez, M. (1997). Minories etniques I premsa europea d’elit. <em>Analysis, 20</em>, 13-36.</p>
  <p class="references">Santa Ana, O. (1999). “Like an animal I was treated”: Anti-immigrant metaphor in US public discourse. <em>Discourse and Society, 10</em>(2), 191-224.</p>
  <p class="references">Santa Ana, O. (2002).  <em>Brown tide rising: Metaphors of Latinos in contemporary American public discourse</em>. Austin: University of Texas Press.</p>
  <p class="references">Santamaría, E. (2002). <em>La incógnita del extraño. Una aproximación a la significación sociológica de la inmigración no comunitaria</em>. Barcelona: Anthropos.</p>
  <p class="references">Sassen, S. (2001). <em>The global city: New York, London, Tokyo</em>. New York: Princeton University Press.</p>
  <p class="references">Smith, P., &amp; Guarnizo, L. (Eds.). (1998). <em>Transnationalism from below</em>. New Brunswick, NJ: Transaction Publishers.</p>
  <p class="references">SOS Racismo. (2000-2002). <em>Informe anual sobre el racismo en el estado español</em>. Barcelona: Icaria.</p>
  <p class="references">Tuchman, G. (1978). <em>Making news: A study in the construction of reality</em>. New York: Free Press.</p>
  <p class="references">Van Dijk, T. (1991). <em>Racism and the press</em>. London: Routledge.</p>
  <p class="references">Van Dijk, T.  (1997). Racismo y análisis crítico de los medios. Barcelona: Paidós. </p>
  <p class="references">Van Dijk, T. (2000). New(s) racism. A discourse analytical approach. In Simon Cottle (Ed.) <em>Ethnic minorities and the media</em> (pp. 33-49). London: Open University Press.</p>
  <p class="references">Van Dijk, T. (2001). Multidisciplinary CDA: a plea for diversity. In R. Wodak, &amp; M. Meyer (Eds.), <em>Methods of discourse analysis</em> (pp. 95-120). London: Sage. </p>
  <p class="references">Wagman, D. (2002). Imágenes sobre la inmigración: Estadística, delito e inmigrantes. <em>Mugak, 19</em>.</p>
  <p class="references">Weaver, D., McCombs, M., &amp; Shaw, D. (2004). Agenda-setting research: Issues, attributes, and influences. In L. Kaid (Ed.), <em>Handbook of Political Communication Research</em> (pp. 257-282). Mahwah, NJ: Erlbaum.</p>
  <p class="references">Wodak, R. (2000, April 7-8). Discurso de exclusión: Estudio comparativo europeo. Speech at the opening of the European Observatory Against Racism and Xenophobia, Vienna. </p>
  <p class="references">Wodak, R. &amp; Meyer, M. (2001). <em>Methods of discourse analysis</em>. London: Sage.</p>
  <p class="references">Woolard, K. (1989). Sentences in the Language Prison: The rhetorical structuring of an American language policy debate. <em>American Ethnologist, 16</em>(2), 268-278.</p>
</section>
<hr />
<section>
  <h2>Notes</h2>
  <p id="note-1"><sup>1</sup> In relation to the ‘early starters’ in Europe which, according to Arango (2002), were countries with a longer tradition of receiving immigration and who have experienced the process gradually and over the time. <a href="#note-line-1">[top]</a></p>
  <p id="note-2"><sup>2</sup>Immigration in Spain has been distributed as follows: in the 1980s immigrants were mainly Europeans. In the 1990s, the first major group was Moroccans, and by extension North Africans. From 1991 to 2001 the weight of Latin Americans rose by four points (from 23% to 27% of immigrants) This increase was mainly driven by two regularization processes and especially a strong impetus from the political arena such as the signing of bilateral agreements with Ecuador, Colombia, and Dominican Republic (Izquierdo,  López, &amp; Martínez, 2002) <a href="#note-line-1">[top]</a></p>
  <p id="note-3"><sup>3</sup>In the 1980s and the first half of the 1990s, the growth of non-European immigrants was led by Moroccans and other North African countries. On Feb. 5, 2000, a young boy stabbed a young woman in El Ejido, Almería (southern Spain). The event originated a confrontation between locals and agricultural workers from Morocco. It became the symbol of the rise of racism against Moroccans in Spain. <a href="#note-line-3">[top]</a></p>
  <p id="note-4"><sup>4</sup>The review of the development and promulgation of legislative measures since 1985 demonstrated that the debate on non-European immigration during electoral processes became profitable for the political parties (Retis, 2006).  <a href="#note-line-3">[top]</a></p>
  <p id="note-5"><sup>5</sup>During those years there were agreements on dual citizenship with Chile (1958), Peru (1959, modified in 2000), Paraguay (1959, amended in 1999), Nicaragua (1961, amended in 1997), Guatemala (1961, amended in 1999), Bolivia (1961, amended in 1961 and 2000), Ecuador (1964, amended 1995), Costa Rica (1964, modified in 1997), Honduras (1966, amended in 2002), Dominican Republic (1968, amended in 2002), Argentina (1969, amended in 2001), and Colombia (1979, modified in 1998). <a href="#note-line-3">[top]</a></p>
  <p id="note-6"><sup>6</sup>An initial approach to the print media sample at the end of 2002 made it possible to establish that not all Latin American nationalities appeared with the same assiduousness and frequency. The preliminary results always suggested the important role played by Colombians, Argentines, and Ecuadoreans throughout 2001. Accordingly, searches were conducted in digital archives at different stages of the study, using the same characteristics: in January 2003; in June 2004; lastly, the process was repeated in May 2005. This article includes news stories related only to Ecuadoreans and Colombians. <a href="#note-line-6">[top]</a></p>
  <p id="note-7"><sup>7</sup>On November 13, 1992, four people killed Dominican immigrant Lucrecia Pérez in the neighborhood of Aravaca, in Madrid. Ten years later, news media outlets remembered this event as “An anonymous immigrant who became a martyr. Today is the 10th anniversary of the murder of Lucrecia Perez, a 33-year-old Dominican. A policeman and three youngsters killed her and committed the first hate crime in Spain” (El País, Nov. 13, 2002). <a href="#note-line-7">[top]</a></p>
</section>
