var jobTitles = [
  "Digital Community Promotions Producer",
  "Communications Leader",
  "Financial Representative",
  "Media Designer and Sales Representative",
  "System Support Specialist",
  "Business Finance Manager",
  "Assistant Planner",
  "Associate Media Buyer",
  "Client Sales",
  "Sales and Catering Coordinator",
  "Program Center Manager",
  "Sales Representative",
  "Public Relations Intern",
  "Account Executive",
  "Personal Assistant",
  "Content Specialist",
  "Marketing and Communications Intern",
  "Digital Web Consultant",
  "Donor Engagement Manager",
  "Creative Opening Specialist",
  "Government and Public Service Internship Coordinator",
  "Program Development Coordinator",
  "Development Specialist",
  "Social Media Marketing Manager",
  "Unit Coordinator of Professional Documents",
  "Social Media Coordinator",
  "Conference Associate",
  "SEO Intern",
  "Marketing Director",
  "Brand Planning Intern",
  "Brand Solutions Coordinator",
  "Social Media Strategist",
  "Advertising Sales Representative",
  "Marketing Coordinator",
  "Broadcast Coordinator",
  "Sales Development Representative",
  "Inside Account Executive",
  "Video Producer",
  "Photographer",
  "Director of Photography",
  "Sports Information Coordinator",
  "Promotions Assistant",
  "Photojournalist",
  "Marketing Coordinator",
  "Web Editor/Social Media Director",
  "Editorial Intern",
  "Reporter/Producer/Co-Anchor for Trends & Friends",
  "Sales Assistant",
  "Staff Reporter",
  "Reporter & Video Producer",
  "Chief Operating Officer",
  "Anchor/Reporter",
  "Customer Support & Services Intern",
  "Promotions Assistant",
  "Content Manager",
  "Transfer Admissions Counselor",
  "Marketing Representative",
  "Branch Coordinator",
  "Producer",
  "Content Development Specialist",
  "Multimedia Journalist",
  "Recruiter",
  "Graphic Design Intern",
  "Account Executive/Membership Sales",
  "Office Manager/Project Coordinator",
  "Multimedia Account Executive",
  "Marketing & Account Services",
  "Marketing Consultant",
  "Project Manager",
  "Project Associate",
  "Account Management",
  "Juris Doctor (J.D.)",
  "Graphic Designer",
  "Account Executive",
  "Community Relations Coordinator",
  "Freelancer",
  "Advertising Account Manager",
  "Account Coordinator",
  "Digital Marketing Specialist",
  "Account Executive",
  "Branding Sales Executive",
  "Graphic Designer & Creative Specialist",
  "Digital Media Coordinator",
  "Marketing Specialist",
  "Marketing Coordinator",
  "Director of Marketing and Advertising",
  "Media Sales Assistant",
  "Advertising & Marketing Specialist",
  "Advertising and Social Media Consultant",
  "Account Manager",
  "Account/Social Media Coordinator",
  "Owner/Account Manager/ Media Director",
  "Campaign Manager",
  "Executive Assistant",
  "Merchandiser",
  "Online Operations Manager",
  "Golf Professional",
  "Telesales Executive",
  "Unit Coordinator",
  "Education Support Coordinator",
  "Recruiter",
  "Engagement Manager",
  "Account Coordinator",
  "Traffic Coordinator",
  "Photographer and Owner",
  "Graphic Designer",
  "Guerilla Marketing Specialist",
  "Purchasing Admin",
  "Sports Video Production Assistant",
  "Athletics Production Assistant",
  "Brand Solutions Coordinator",
  "Sales Assistant",
  "Weekend Weather Anchor and Weekday Reporter",
  "Creative Services Producer",
  "Digital Content Specialist",
  "Business Systems Analyst",
  "Administrative Specialist ",
  "Photographer",
  "Marketing and Promotions Intern",
  "Associate Media Planner",
  "Commercial & Industrial Sales",
  "Funding Specialist",
  "Talent Acquisition Program Manager",
  "Sales Representative",
  "Inside Account Executive",
  "Contract Coordinator",
  "Camera Operator",
  "Administrative Associate",
  "Account Executive",
  "Travel Recruiter",
  "Account Executive",
  "Editor/Producer",
  "Coordinator",
  "Programmatic Advertising Account Manager",
  "Local/Regional Sales Assistant",
  "Press Office Assistant",
  "Social Media Marketing Coordinator",
  "Marketing Coordinator",
  "Office/Box Office Manager",
  "Content Marketing and Social Media Coordinator",
  "Inside Account Executive",
  "CEO/Founder",
  "Associate",
  "Business Development Manager",
  "Marketing Communications Consultant",
  "Sales Representative",
  "Marketing Coordinator",
  "Human Resources Training & Communications Generalist",
  "Marketing and Public Relations Specialist",
  "Account Coordinator",
  "Director of Sales and Marketing",
  "Early Intervention Specialist",
  "Technology",
  "Director of Member Services",
  "Wind Club Coordinator/Direct Shipping Manager",
  "Assistant Account Executive",
  "Corporate Communications Coordinator",
  "Research Assistant",
  "IT Recruiter",
  "Digital Media Coordinator",
  "Intern",
  "Market Manager",
  "Sales/Estimating",
  "Corporate Recruiter",
  "Branch Manager/Financial Officer",
  "ACH Specialist",
  "Protocol Office",
  "Business Development/Marketing Assistant",
  "Agency Owner",
  "Account Executive",
  "Dean of Reese Center",
  "Loan Officer",
  "OEM Sales Manager",
  "Director of Communication",
  "Client Services Manager",
  "Marketing Executive",
  "Community Manager",
  "Professor of Rhetoric and Media Studies",
  "Assistant General Manager",
  "Manager",
  "Management Assistant to the City Secretary",
  "Owner",
  "Deputy General Counsel",
  "Director",
  "Associate Director",
  "Executive Director of Intervention Services",
  "Speech Communication Professor& Director of Intervention Services",
  "Professor",
  "International Event Coordinator",
  "Human Resources Assistant",
  "Minister",
  "Consultant",
  "Sales & Events Coordinator",
  "Professor of Communication",
  "Attorney at Law",
  "Sales representative",
  "Marketing & Sales",
  "Assistant Director",
  "Associate Librarian for Education",
  "Human Resources Manager",
  "Economic Development Program Specialist",
  "Auto Damage Adjuster",
  "Product Specialist",
  "Marketing Programs Manager",
  "Staff Development Specialist",
  "Community Manager",
  "Chief Warrant Officer of Workplace Relationships",
  "Director of Operations",
  "Account Manager",
  "Business Development Representative",
  "Financial System Coordinator",
  "Ready-to-Wear Women's Designer",
  "Vice President-Transaction & Associate General Counsel",
  "Instructor",
  "Area Sales Manager",
  "Owner",
  "Editor and Project manager",
  "Quality Engineer",
  "Direct Sales Manager",
  "Chief Information Officer",
  "Website Designer",
  "Director",
  "ERP Consultant & Architect",
  "Pastor",
  "Certified Ophthalmic Assistant",
  "Technology Consultant",
  "Management Trainee",
  "President",
  "Account Executive/Membership Sales",
  "Customer Management Account Representative",
  "Assistant Director",
  "Assistant Brand Manager of Business and Marketing",
  "Assistant Professor of Speech Communications",
  "Lead Communications Faculty",
  "Coordinator",
  "District Sales Representative",
  "Admissions Director",
  "Instructor"
];

var jobLocations = [
  "KCBD-TV-Lubbock, Texas",
  "Society of St. Vincent de Paul, Diocesan Council-Dallas, Texas",
  "Capital Wealth Strategies, LLC,-Irving, Texas",
  "TYECO Roofing & Construction-New Deal, Texas",
  "Texas Health and Human Services Commission-Austin, Texas",
  "Ethos Group-Irving, Texas",
  "Optimedia-Dallas, Texas",
  "Southwest Media Group-Dallas, Texas",
  "Echo Global Logistics-Dallas, Texas",
  "Overton Hotel and Conference Center-Lubbock, Texas",
  "Ruffalo Noel Levitz-Colorado Springs, Colorado",
  "Glazer’s Distributors-Dallas/Fort Worth, Texas",
  "Edelman-Houston, Texas",
  "On Point Promos-Dallas/Fort Worth, Texas",
  "Leen 95-Lubbock, Texas",
  "HCK2 Partners-Dallas, Texas",
  "Dallas Convention & Visitors Bureau-Dallas, Texas",
  "DexMedia-Dallas/Fort Worth, Texas",
  "Cal Farley’s-Amarillo, Texas",
  "Bahama Buck’s Franchise Corp.-Lubbock, Texas",
  "Texas Tech University-Lubbock, Texas",
  "Dallas Independent School District-Dallas, Texas",
  "March of Dimes-Midland, Texas",
  "Primitive Social-Lubbock, Texas",
  "Rawls Career Management Center-Lubbock, Texas",
  "Razonia McClellan Public Relations-Lubbock, Texas",
  "Dallas Children’s Advocacy Center-Dallas, Texas",
  "Builder Homesite Inc.-Austin, Texas",
  "ecurie25 USA-Houston, Texas",
  "The Richards Group-Dallas, Texas",
  "OOH Moroch Partners-Dallas, Texas",
  "Conviction Digital LLC-Austin, Texas",
  "The Daily Toreador-Lubbock, Texas",
  "HumanKind HR- Lynchburg, Virginia",
  "RD Thomas Advertising-Lubbock, Texas",
  "SoftwareONE-Dallas, Texas",
  "SHI International Corp.-Austin, Texas",
  "St. John’s University-Queens, New York",
  "KAMC and KLBK-Lubbock, Texas",
  "The Daily Toreador-Lubbock, Texas",
  "South Plains College-Levelland, Texas",
  "94.9 KLTY-Arlington, Texas",
  "KCBD-TV-Lubbock, Texas",
  "Starmount-Austin, Texas",
  "Ramar Communications KJTV/FOX 34-Lubbock, Texas",
  "Fort Worth Texas Magazine-Fort Worth, Texas",
  "KLBK (Nexstar)-Lubbock, Texas",
  "iHeartMedia (Katz Media Group)-Dallas, Texas",
  "Star Local Media-Dallas/Fort Worth, Texas",
  "Dallas Mavericks-Dallas/Fort Worth, Texas",
  "OptIn-Los Angeles, California",
  "KCBD News Channel 11-Lubbock, Texas",
  "Southwest Airlines-Dallas, Texas",
  "CBS Radio-Dallas/Fort Worth, Texas",
  "Chris Kaiser Builder-Fredericksburg, Texas",
  "Texas Tech University Houston Office-Houston, Texas",
  "Austin Convention Center-Austin, Texas",
  "IDR, Inc.-Addison, Texas",
  "Ramar Communications-Lubbock, Texas",
  "Aars | Wells-Dallas-Dallas, Texas",
  "KTAB/KRBC-Abilene, Texas",
  "Insight Global-Dallas, Texas",
  "Momentum Factor-Austin, Texas",
  "Dallas Wings-Arlington, Texas",
  "Schaffer Construction, LLC-Frisco, Texas",
  "Houston Press-Houston, Texas",
  "Spry Creative Group-Houston, Texas",
  "Malkan Interactive Communications LLC-Corpus Christi, Texas",
  "Children’s Home Healthcare-Dallas/Fort Worth, Texas",
  "alliantgroup-Houston, Texas",
  "TracyLocke-Chicago, Illinois",
  "Southwestern Law School-Los Angeles, California",
  "OCJ Apparel-Dallas/Fort Worth, Texas",
  "LeadsOnline-Plano, Texas",
  "The Salvation Army-Lubbock, Texas",
  "Austin, Texas",
  "Refund Advisory Corp-Dallas, Texas",
  "HZDG-New York, New York",
  "New Horizons Computer Learning Centers-Austin, Texas",
  "GriffinWink Advertising-Lubbock, Texas",
  "etc group, inc.-Arlington, Texas",
  "Lubbock, Texas",
  "RD Thomas Advertising-Lubbock, Texas",
  "Workforce Solutions South Plains-Lubbock, Texas",
  "Food Concepts International/Abuelo’s-Lubbock, Texas",
  "Arrow Ford-Abilene, Texas",
  "Nexstar Broadcasting Group, Inc.-Lubbock, Texas",
  "Visit Lubbock/Lubbock Economic Development Alliance-Lubbock, Texas",
  "COAST Magazine: Santa Ana, California",
  "Revolver Brewing-Fort Worth, Texas",
  "Miller Ad Agency-Dallas, Texas",
  "Foxhound Media & Digital Communications-Lubbock, Texas",
  "Fight Club Media-Austin, Texas",
  "Texas Tech University Humanities Center-Lubbock, Texas",
  "Southern Wine & Spirits-Denver, Colorado",
  "T.C. Elli’s-Lubbock, Texas",
  "Elin Arvidsson Golf-Falkenberg, Sweden",
  "DHL-Irving, Texas",
  "International Partnerships at TTUISD-Lubbock, Texas",
  "University of New Mexico Continuing Education-Albuquerque, New Mexico",
  "San Antonio, Texas",
  "IDR, Inc.-Dallas/Fort Worth, Texas",
  "Vantiv-Denver, Colorado",
  "Alpha Media USA-Lubbock, Texas",
  "Alyssa Beth Photography-Lubbock, Texas",
  "Lubbock National Bank-Lubbock, Texas",
  "Jimmy John’s-Urbana-Champaign, Illinois",
  "AZUMA Leasing-Austin, Texas",
  "University of Texas-Austin, Texas",
  "Texas Tech University-Lubbock, Texas",
  "Moroch Partners-Dallas, Texas",
  "HRP-Dallas, Texas",
  "KJCT News 8 and KKCO 11 News-Grand Junction, Colorado",
  "Gray Media-WTOK TV-Meridian, Mississippi",
  "Banjo-Las Vegas, Nevada",
  "Epsilon-Irving, Texas",
  "Restaurant Solutions Inc.-Littleton, Colorado",
  "After Dark Entertainment-Lubbock, Texas",
  "Texas Tech University Athletics  [Lubbock, Texas]",
  "Southwest Media Group-Dallas, Texas",
  "Joe W. Fly Co., Inc.-San Antonio, Texas",
  "GM Financial-Dallas/Fort Worth, Texas",
  "HMS-Dallas/Fort Worth, Texas",
  "Glazer’s Distributors-Houston, Texas",
  "SHI International Corp-Austin, Texas",
  "Delta Media-Colleyville, Texas",
  "Dillard's-Plano, Texas",
  "MedSynergies-Dallas/Fort Worth, Texas",
  "Anovia Payments-Las Colinas, Texas",
  "The Delta Companies-Dallas/Fort Worth, Texas",
  "Digitas LBi-Chicago, Illinois",
  "Dallas Cowboys-Dallas, Texas",
  "Frontline Source Group-Dallas/Fort Worth, Texas",
  "MultiView-Dallas/Fort Worth, Texas",
  "KCBD News Channel 11-Lubbock",
  "inHouse Communications-London, England",
  "Idera Software-Austin",
  "The Roof-Lubbock",
  "Midland RockHounds-Midland, Texas",
  "WrightIMC-Plano, Texas",
  "SHI International Corporation-Austin",
  "Vozra app",
  "ISN-Dallas",
  "James Wood Motors-Decatur, Texas",
  "HexaGroup-Houston, Texas",
  "Glazer’s Wholesale Distributers-Dallas, Texas",
  "Clean Scapes, LP, -Austin, Texas",
  "Gaylord Hotels-Dallas/Fort Worth, Texas",
  "Cigar Cigar!-Sugar Land, Texas",
  "SHIFT Communications-Austin, Texas",
  "All Star Ford Kilgore-Kilgore, Texas",
  "DePuy Synthes Mitek Sports Medicine-Lubbock, Texas",
  "Abernathy Independent School District-Abernathy, Texas",
  "House or Representatives Committee on Science, Space and Technology-Washington D.C.",
  "Llano Estacado Winery-Lubbock, Texas",
  "Edelman-Chicago, Illinois",
  "Community First Health Plans-San Antonio, Texas",
  "Orasi Economic Development-Fort Worth, Texas",
  "Prestige Staffing-Dallas, Texas",
  "Special Audience Marketing-Austin, Texas",
  "Viacom/MTV-New York, New York",
  "Tanteo Spirits-New York, New York",
  "Venture Mechanical, Inc.-Irving, Texas",
  "Smith Co.-Houston, Texas",
  "Alliance Federal Credit Union-Lubbock, Texas",
  "Amplify Credit Union-Austin, Texas",
  "Communications & Government Affairs, Idaho National Laboratory-Idaho Falls, Idaho",
  "Five States Energy Company, LLC.-Dallas, Texas",
  "AllState-San Angelo, Texas",
  "Oklahoma City Barons-Oklahoma City, Oklahoma",
  "South Plains College-Levelland, Texas",
  "First Mortgage Corporation-Frisco, Texas",
  "Granbury Restaurant Solutions-Grapevine, Texas",
  "Limestone Medical Center-Groesbeck, Texas",
  "Dallas by Definition-Irving, Texas",
  "Orion Drilling Company-Corpus Christi, Texas",
  "Dakota Arms Apartment Homes-Lubbock, Texas",
  "Willamette University, Salem, Oregon",
  "Barnes & Noble College Booksellers-Lubbock, Texas",
  "Western Union-Englewood, Colorado",
  "City of Lubbock- Lubbock, Texas",
  "Rapid Tag & Label-Oakland, New Jersey",
  "Law Office Gila River Indian Community-Sacaton, Arizona",
  "WTAMU Church of Christ Bible Choir-Canon, Texas",
  "Mentor Tech-Texas Tech University-Lubbock, Texas",
  "Coppell Independent School District-Coppell, Texas",
  "North Lake College of the Dallas County Community College District-Irving, Texas",
  "Clarion University of Pennsylvania Communications Department-Clarion, PA",
  "Anthony Travel-Dallas, Texas",
  "Core Laboratories-Houston, Texas",
  "Quaker Avenue Church of Christ-Lubbock, Texas",
  "Interactive Digital Marketing, Chick-Fil-A, Inc.-Atlanta, GA",
  "Courtyard by Marriot-Midland, Texas",
  "Angelo State University-San Angelo, Texas",
  "Barlow Jones L.L.P.-Houston, Texas",
  "Petersen Aluminum Corporation-Tyler, Texas",
  "PricewaterhouseCoopers, L.L.P.-Dallas, Texas",
  "Event Services United Spirit Arena Texas Tech University-Lubbock, Texas",
  "Texas Tech University Libraries-Lubbock, Texas",
  "Shearer's Foods-Lubbock, Texas",
  "Panhandle Regional Planning Commission-Amarillo, Texas",
  "Geico Car Insurance-Lubbock, Texas",
  "PMT Corporation-Chanhassen, Minnesota",
  "Core Trace-Austin, Texas",
  "The Medical Center of Plano, Center for Learning-Plano, Texas",
  "American Cancer Society Income Development, West Texas Region-Midland, Texas",
  "The Associates, LLC. Orlean, Virginia",
  "The Classic Theater-San Antonio, Texas",
  "Baher Hughes INTEQ North American Region-Irving, Texas",
  "OfficeWise Furniture & Supply-Lubbock, Texas",
  "Texas Lottery Commission-Austin, Texas",
  "Saks Fifth Avenue-New Orleans, Louisiana",
  "Entertainment Properties Trust-Kansas City, Missouri",
  "Northwest Missouri State University-Maryville, Missouri",
  "Ben E. Keith Company-Denton, Texas",
  "Croft ClaimWorks, L.C.-Richardson, Texas",
  "Atlantic Publishing-Ocala, Florida",
  "Industrial Molding Corporation-Lubbock, Texas",
  "iChill Beverages, Inc.-Irving, Texas",
  "Technical Solutions-Mahwah, New Jersey",
  "Beyond the Building-Dallas, Texas",
  "Partners Products & Services, Basecamp Technology Expeditions-Sammamish, Washington",
  "Fortiori Services - Scottsdale, Arizona",
  "The Refuge-Lubbock, Texas",
  "Houston Eye Associates-Houston, Texas",
  "Halco Life Safety Systems-Houston, Texas",
  "Enterprise-Morehead City, North Carolina",
  "The Foundation for a Better Life-Denver, Colorado",
  "Greater Waco Chamber of Commerce-Waco, Texas",
  "Frito-Lay North America-El Paso, Texas",
  "Support Operations for Academic Retention (SOAR)-Texas Tech University-Lubbock, Texas",
  "CEV Pathways for Career Success",
  "South Plains College-Levelland, Texas",
  "Front Range Community College Westminster Campus-Westminster, Colorado",
  "University of North Texas-Denton, Texas",
  "Expeditors International-Washington, D.C.",
  "Graduate School, Texas Tech University-Lubbock, Texas",
  "Communication Studies Department, Texas Tech University-Lubbock, Texas"
];

$(document).ready(function() {

  var rotatingCube = setInterval(function() { rotateForward() }, 10000);

  $('#controls .back').click(function(e) {
    e.preventDefault();
    stopRotating();
    rotateBack();
  });
  $('#controls .forward').click(function(e) {
    e.preventDefault();
    stopRotating();
    rotateForward();
  });

  var rotation = 0;
  var cubeSides = ['front', 'top', 'back', 'bottom'];
  var cubeSideNumber = 0;
  var jobNumber = 0;

  function rotateForward() {

    if (jobNumber != 237) {
      jobNumber++;
    } else {
      jobNumber = 0;
    }

    if (cubeSideNumber != 3) {
      cubeSideNumber++;
    } else {
      cubeSideNumber = 0;
    }

    cubeSide = 'cube-face-' + cubeSides[cubeSideNumber];

    var job = jobTitles[jobNumber] + ' - <em>' + jobLocations[jobNumber] + '</em>';
    $('#career-cube .cube .' + cubeSide + ' p').html(job);

    // Rotate cube
    rotation = rotation - 90;
    $('#career-cube .cube').css('transform', 'rotateX(' + rotation + 'deg)');

  }

  function rotateBack() {

    if (jobNumber != 0) {
      jobNumber--;
    } else {
      jobNumber = 237;
    }

    if (cubeSideNumber != 0) {
      cubeSideNumber--;
    } else {
      cubeSideNumber = 3;
    }
    cubeSide = 'cube-face-' + cubeSides[cubeSideNumber];
    job = jobTitles[jobNumber] + ' - <em>' + jobLocations[jobNumber] + '</em>';
    rotation = rotation + 90;

    $('#career-cube .cube .' + cubeSide + ' p').html(job);
    $('#career-cube .cube').css('transform', 'rotateX(' + rotation + 'deg)');
  }

  function stopRotating() {
    clearInterval(rotatingCube);
  }

});
